### ISSUE TITLE
Low hashrates on Ryzen 2700X

### ISSUE THREAD

**Issue by openxbmc** [tevador/RandomX#100]
platform:Ryzen 2700x/MSI X470/8G DDR4
os:Win10 Pro 64bit
command:randomx-benchmark.exe --mine --init 8 --threads 8 --nonces 100000 --jit --largepages
Performance is 1600~1700

I think this CPU should be 4000+(Becasue I found Ryzen 1700 is 4000+)

**Comment by tevador** [comment]
> `--largepages`

try `--largePages` (case sensitive)

**Comment by SChernykh** [comment]
Maybe something else is using your CPU when you run the benchmark? And it should be with capital P:
```
--largePages
```

**Comment by mistfpga** [comment]
Hi,

To eliminate the issue of apps running in the background and the all round headache that is a windows install and testing of this too (to be clear, this is from a testing standpoint, not usability)

There are quite a few things that windows needs done for it to work properly (all the latest updates for one, Linux requires this as well if you want to get a decent hashrate - not applying the updates cuts the hashrate by 50%)

Here is a step by step guide I created to creating a persistent USB unbuntu install just for testing RandomX

**Comment by openxbmc** [comment]
> > `--largepages`
> 
> try `--largePages` (case sensitive)

Thank you but new issue occur

ERROR: Cache allocation failed
To use large pages, please enable the "Lock Pages in Memory" policy and reboot.

I queried via Google. This problem is related to SQL server.
Do you also have this problem?

**Comment by openxbmc** [comment]
> Maybe something else is using your CPU when you run the benchmark? And it should be with capital P:
> 
> ```
> --largePages
> ```

Thank you~

**Comment by mistfpga** [comment]
> --largepages
> 
> try --largePages (case sensitive)
> 
> Thank you but new issue occur
> ERROR: Cache allocation failed
> To use large pages, please enable the "Lock Pages in Memory" policy and reboot.
> I queried via Google. This problem is related to SQL server.
> Do you also have this problem?

I address this in the start of the thread I linked. To enable largePage support

- Press start and type gpedit, this should bring up the Local Group Policy Editor
Windows settings -> security settings -> local policies -> user rights assignment
- Now scroll down to Lock Pages In Memory
- Double click it
- Add the user which will be doing the testing. I normally just add administrotor
- Click check name, to make sure it is the correct name - if you sign in with an @example.com then you need to add that.
- Reboot.
- Dont forget if you only added LOCAL-PC/Administator you will need to run the command prompt as admin

**Comment by openxbmc** [comment]
> Hi,
> 
> To eliminate the issue of apps running in the background and the all round headache that is a windows install and testing of this too (to be clear, this is from a testing standpoint, not usability)
> 
> There are quite a few things that windows needs done for it to work properly (all the latest updates for one, Linux requires this as well if you want to get a decent hashrate - not applying the updates cuts the hashrate by 50%)
> 
> Here is a step by step guide I created to creating a persistent USB unbuntu install just for testing RandomX
> 
> * oops, hit send too early.
>   https://forum.zcashcommunity.com/t/an-introdction-to-randomx-and-its-benchmarking-tool/33807/10
>   (that thread is a bit of a mess, I will get around to tidying it up after I have done the ryzen stuff)
> 
> That is for creating a Live Ubuntu install. - the First post in that thread covers configuring stuff in windows. (although with an older release of the randomx tool)
> 
> I highly recommend that you follow the Ubuntu instructions. It includes how to work out what the optimum parameters are for your hardware too. That thread will be updated with Ryzen 2600 results and overclocking/ram frequency under linux. (as well as various hardware and ram configurations)
> 
> Post in the thread over there if you have any further issues using my ubuntu instructions, that is not a place to report RandomX bugs, etc. It is just a community space I am using to document my progress and to try to help Privacy coin advocates repurpose their hardware to Monero when the fork comes.
> 
> It and I am in no way affiliated or associated with RandomX or their dev team. - To that regard, tevador, feel free to use any of the info on your page verbatim. I will also keep a wiki up to date with instructions on GitHub if that is what you would prefer.
> 
> I do mine monero, and I am a strong supporter of privacy coins.
> 
> Hope this helps.

You are so good.Thanks a lot!

**Comment by mistfpga** [comment]
> You are so good.Thanks a lot!

No problem.  If you have any problems at all, please post in that thread.  the idea is to get a decent baseline everyone can use to compare against.  

Any issues you have with the instructions I would really like feedback on, that way hopefully the next person wont have the same issue. (please keep that feedback on that forum though and not on this GitHub) - If the instructions worked for you please state that then close this GitHub issue. (I think that is the right protocol for here)

I am trying to make it as newbie friendly as possible and little to no understanding of Linux is required to get the basic setup and benchmarking done.

I will be adding error messages (like the largePages one on windows) and basic troubleshooting too.
I have just added some images for uefi/bios boot config checks.

Hope this helps.  and feel free to PM me on the forum or send me a message via GitHub.
