### ISSUE TITLE
A few observations about RANDOMX_DATASET_*_SIZE

### ISSUE THREAD

**Issue by doegox** [tevador/RandomX#102]
RandomX default `RANDOMX_DATASET_EXTRA_SIZE` is 33554368 which can be written 0x7ffff * 64 or (2**19 - 1) * 64
According to `configuration.md`: _Permitted values: Non-negative integer divisible by 64_
According to `specs.md`:
_The datasetOffset is calculated by bitwise AND of quadword 13 and the value RANDOMX_DATASET_EXTRA_SIZE / 64. The result is multiplied by 64._

But the actual code is not using an AND but a modulo:
in `virtual_machine.cpp`
```c
91:   datasetOffset = (program.getEntropy(13) % 
           (randomx::DatasetExtraItems + 1)) * randomx::CacheLineSize;
```
with `DatasetExtraItems = RANDOMX_DATASET_EXTRA_SIZE / RANDOMX_DATASET_ITEM_SIZE` so in the default configuration DatasetExtraItems=2**19

The spec and the code are equivalent in RandomX only because of the special structure of the chosen `RANDOMX_DATASET_EXTRA_SIZE`.

Our recommendation is:
* configuration.md Permitted values for RANDOMX_DATASET_EXTRA_SIZE should enforce that property
* compilation asserts should verify that property

According to specs.md (4.6.2 Loop execution):
_6. A 64-byte Dataset item at address datasetOffset + mx % RANDOMX_DATASET_BASE_SIZE is prefetched from the Dataset (it will be used during the next iteration)._

However, the code is doing the following:
```c
88: datasetPrefetch(datasetOffset + mem.mx);
```
That is, the `% RANDOMX_DATASET_BASE_SIZE` is missing which can lead to an out-of-bounds access.

Something similar happens in step 7:
_7. A 64-byte Dataset item at address datasetOffset + ma % RANDOMX_DATASET_BASE_SIZE is loaded from the Dataset. The 64 bytes are XORed with all integer registers in order r0-r7._

Where the actual code does:
```c
89: datasetRead(datasetOffset + mem.ma, nreg.r);
```

Note that both functions, datasetPrefetch and datasetRead, do not perform any kind of boundary check.

Note also that the modulus operation should apply to the sum of datasetOffset and mx/ma.

**Comment by tevador** [comment]
> The datasetOffset is calculated by bitwise AND of quadword 13 and the value RANDOMX_DATASET_EXTRA_SIZE / 64. The result is multiplied by 64.
>
>But the actual code is not using an AND but a modulo

That's a mistake in the specification and not in the code. Originally, `RANDOMX_DATASET_EXTRA_SIZE / 64` was always meant to be in the form of <code>2<sup>N</sup>-1</code>, in which case bitwise AND and modulo are equivalent. Later, this restruction was dropped, so modulo and bitwise AND could give different results, so the use of `%` in the code is correct.

> in the default configuration DatasetExtraItems=2**19

No, <code>DatasetExtraItems = 2<sup>19</sup>-1 = 524287</code>

> Permitted values for RANDOMX_DATASET_EXTRA_SIZE should enforce that property

It is already enforced:

https://github.com/tevador/RandomX/blob/c433f6d3a81c830e007bc494bc09e3be084af866/src/common.hpp#L46

> According to specs.md (4.6.2 Loop execution):
> _6. A 64-byte Dataset item at address datasetOffset + mx % RANDOMX_DATASET_BASE_SIZE is prefetched from the Dataset (it will be used during the next iteration)._
> 
> However, the code is doing the following:
> 
> ```c
> 88: datasetPrefetch(datasetOffset + mem.mx);
> ```
> 
> That is, the `% RANDOMX_DATASET_BASE_SIZE` is missing which can lead to an out-of-bounds access.
> 

The modulo operation is performed here:

https://github.com/tevador/RandomX/blob/07293a9378c4c589e68da752f6e9b9be875526f1/src/vm_interpreted.cpp#L87

Note that `RANDOMX_DATASET_BASE_SIZE` is a power of 2, so bitwise AND and modulo are equivalent.

> Something similar happens in step 7:
> _7. A 64-byte Dataset item at address datasetOffset + ma % RANDOMX_DATASET_BASE_SIZE is loaded from the Dataset. The 64 bytes are XORed with all integer registers in order r0-r7._
> 
> Where the actual code does:
> 
> ```c
> 89: datasetRead(datasetOffset + mem.ma, nreg.r);
> ```
> 

The only place where `mem.ma` is assigned is here:

https://github.com/tevador/RandomX/blob/07293a9378c4c589e68da752f6e9b9be875526f1/src/vm_interpreted.cpp#L90

And the modulo operation has already been applied to `mem.mx`, so there is no need to apply it again to `mem.ma`.

>
> Note also that the modulus operation should apply to the sum of datasetOffset and mx/ma.

No. This would restrict all Dataset access to the first `RANDOMX_DATASET_BASE_SIZE` bytes, which is not what we want.

**Comment by doegox** [comment]
> > The datasetOffset is calculated by bitwise AND of quadword 13 and the value RANDOMX_DATASET_EXTRA_SIZE / 64. The result is multiplied by 64.
> > But the actual code is not using an AND but a modulo
>
> That's a mistake in the specification and not in the code.

ok

> > in the default configuration DatasetExtraItems=2**19
>
> No, DatasetExtraItems = 2<sup>19</sup>-1 = 524287

sorry I meant the modulo value, i.e. `DatasetExtraItems+1` 😅

> > Permitted values for RANDOMX_DATASET_EXTRA_SIZE should enforce that property
> 
> It is already enforced:

We meant enforcing the (2<sup>N</sup>-1)*64 property. Now that you indicated the spec was wrong, that's another story. There is no need to change permitted values anymore, just to fix the definition of `datasetOffset` in the spec.

> > That is, the `% RANDOMX_DATASET_BASE_SIZE` is missing which can lead to an out-of-bounds access.
> 
> The modulo operation is performed here:

ok sorry we missed it.

> > Note also that the modulus operation should apply to the sum of datasetOffset and mx/ma.
> 
> No. This would restrict all Dataset access to the first `RANDOMX_DATASET_BASE_SIZE` bytes, which is not what we want.

indeed `DatasetSize = RANDOMX_DATASET_BASE_SIZE + RANDOMX_DATASET_EXTRA_SIZE`, with `datasetOffset` within `RANDOMX_DATASET_EXTRA_SIZE` and `mx` within `RANDOMX_DATASET_BASE_SIZE-64` so there is no out-of-bounds access.

In the code, alignment of `mx` is done together with the `% RANDOMX_DATASET_BASE_SIZE` via `mem.mx &= CacheLineAlignMask;` with `CacheLineAlignMask = (RANDOMX_DATASET_BASE_SIZE - 1) & ~(CacheLineSize - 1);` but in the specifications we don't see the 64b alignment of `mx`. 

It's directly:
```
4.5.3 Registers ma and mx are initialized using the low 32 bits of quadwords 8 and 10 in little endian format.
4.6.2.5. The mx register is XORed with the low 32 bits of registers readReg2 and readReg3 (see Table 4.5.3).
4.6.2.6. A 64-byte Dataset item at address datasetOffset + mx % RANDOMX_DATASET_BASE_SIZE is prefetched from the Dataset (it will be used during the next iteration).
```
We think 64b alignment of `mx` should be added to the specs in 4.6.2.5 (loop) and similarly alignment of `ma` should be added in 4.5.3 (initialization) or 4.6.2.7. In the code `ma` is aligned during initialization.
