### ISSUE TITLE
RandomX Integration

### ISSUE THREAD

**Issue by txchangecoin-project** [tevador/RandomX#104]
I ran test on my fork, it it ran through, and i had to integrate it to the mainnet, surprisingly i got a huge network hash rate, though am working to see why, i was surprised though. On test net i had 1 thread of CPU giving a reasonable hashrate but not on the mainnet. Am just curious though.

**Comment by SChernykh** [comment]
Can you give a link to your coin's blockchain explorer? Have you forked to RandomX on mainnet already?

**Comment by txchangecoin-project** [comment]
https://explorer.txchangecoin.online, yeah i have fork already on mainnet. @SChernykh

**Comment by SChernykh** [comment]
You have difficulty 353320 there, network hashrate 1.177 kh/s and last block over 2 days ago. It looks like no one is mining it now.

**Comment by txchangecoin-project** [comment]
mining is going on at https://pools.txchange.online,  the hashrate is 2.94 kH/sec, even on the wallet after the hardfork. I was wondering why though, i have been looking through. @SChernykh

**Comment by SChernykh** [comment]
This pool can't mine a block for some reason. Probably some pool/node incompatibility.

**Comment by txchangecoin-project** [comment]
The pool is ok, you can use the xmrig miner https://github.com/txchangecoin-project/xmrig @SChernykh

**Comment by txchangecoin-project** [comment]
You are right, i have been on it since then, @SChernykh

**Comment by txchangecoin-project** [comment]
All have been solved thanks for your tip @SChernykh

**Comment by txchangecoin-project** [comment]
check it out https://forum.zcashcommunity.com/t/an-introdction-to-randomx-benchmarking-tool-and-pool-solo-mining/33807/14
