### ISSUE TITLE
Guide run randomx

### ISSUE THREAD

**Issue by hoainama8** [tevador/RandomX#106]
Hi @tevador 
Could you show me use randomx to mine xmr on ubuntu 18.04

**Comment by mistfpga** [comment]
Here you go.

Please post in the thread on the forums if you have any issues with the instuctions.  I will help and support you over there. (please do not post me questions about the setup on this GitHub ticket)

https://forum.zcashcommunity.com/t/an-introdction-to-randomx-and-its-benchmarking-tool/33807/10?u=mistfpga

If my instructions help you please close this issue saying that.

Thanks.

**Comment by jbmustaq** [comment]
I have gone through your instructions but there is nothing mentioned on how to mine monero with randomx. can you please provide a layman instruction of specifically mining monero pool with your miner. we will be thankfull.
