### ISSUE TITLE
compilation error under termux on pocof1 armv8 clang8

### ISSUE THREAD

**Issue by BenjaminWegener** [tevador/RandomX#107]
data/data/com.termux/files/home/build/RandomX/src/allocator.cpp:39:15: error:
      use of undeclared identifier 'aligned_alloc'
                void *mem = rx_aligned_alloc(cou...
                            ^
/data/data/com.termux/files/home/build/RandomX/src/intrin_portable.h:388:39: note:
      expanded from macro 'rx_aligned_alloc'
#define rx_aligned_alloc(size, align) aligned_al...
                                      ^
1 error generated.
make[2]: *** [CMakeFiles/randomx.dir/build.make:154: CMakeFiles/randomx.dir/src/allocator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:184: CMakeFiles/randomx.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by osensei** [comment]
I was able to build it using an Ubuntu proot environment in termux: https://wiki.termux.com/wiki/Ubuntu

**Comment by BenjaminWegener** [comment]
thx, works, but hangs on root@localhost:~/RandomX/build# ./randomx-benchmark --softAes --verify                                         
RandomX benchmark v1.0.4                                 
- light memory mode (256 MiB)                           
- interpreted mode                                      
- software AES mode
 - small pages mode                                     
Initializing ...                                        
Memory initialized in 1.85462 s                         
Initializing 1 virtual machine(s) ...                   
Running benchmark (1000 nonces) ...

**Comment by osensei** [comment]
Are you sure it hangs? I would guess it just didn't finish. Try using less nonces.

**Comment by BenjaminWegener** [comment]
update

got a result:
root@localhost:~/RandomX/build# ./randomx-benchmark --softAes --verify --nonces 16 --threads 8                  
RandomX benchmark v1.0.4
 - light memory mode (256 MiB)                          
 - interpreted mode                                     
 - software AES mode                                    
 - small pages mode                                    
Initializing ...                                        
Memory initialized in 1.84931 s                         
Initializing 8 virtual machine(s) ...                   
Running benchmark (16 nonces) ...                       
Calculated result: 8ff69d3cd8d4f0cc0cfc083c09b214e02ca89ca19621806b977aea74534b7c17
Performance: 355.417 ms per hash
