### ISSUE TITLE
mac support? ERROR: Dataset allocation failed

### ISSUE THREAD

**Issue by moonwater** [tevador/RandomX#115]
./randomx-benchmark --mine --jit --threads 6 --init 6 --largePages

RandomX benchmark v1.0.4
 - full memory mode (2080 MiB)
 - JIT compiled mode
 - hardware AES mode
 - large pages mode
Initializing (6 threads) ...
ERROR: Dataset allocation failed
To use large pages, please run: sudo sysctl -w vm.nr_hugepages=1250

---------------
Is there a way to allocate hugepages on Mac OS X?

**Comment by tevador** [comment]
The command line is correct.

You just need to make sure that your operating system is configured for large pages and you have enough free RAM.

**Comment by moonwater** [comment]
> The command line is correct.
> 
> You just need to make sure that your operating system is configured for large pages and you have enough free RAM.

I searched the web about "large pages"  "huge pages" +"mac OS", tried  to enable lage pages for mac OS. but there is no answer..

tevador,  can you do something from the coding to support mac os?
Thanks.

**Comment by mistfpga** [comment]
So what happens when you run

sudo sysctl -w vm.nr_hugepages=1250

Can you paste the output of the command into the ticket please.

You can also adjust the page size support. but I dont own a mac, so cant test it. but the above command should work. and enable largePages.

**Comment by tevador** [comment]
> tevador, can you do something from the coding to support mac os?

RandomX already supports large pages on macos. You just have to enable it on the OS level (and make sure you have >2.5 GB of free RAM).

https://github.com/tevador/RandomX/blob/c433f6d3a81c830e007bc494bc09e3be084af866/src/virtual_memory.cpp#L112-L113

**Comment by AntlerDM** [comment]
Large Pages works for me, but only after a restart. After you run/quit a bunch of applications, the error occurs.

**Comment by hyc** [comment]
@AntlerDM that's normal. You have to reserve large pages at boot time if you want to make sure they're available. After the system has been running for a while memory will become too fragmented to find enough contiguous memory for them.
