### ISSUE TITLE
RanxomX Benchmark on 4xOpteron not Working Properly

### ISSUE THREAD

**Issue by Desolatepuppy** [tevador/RandomX#120]
Hi guys, I had an old server with 4xOpteron 6282SE. I tried to run Randomx-benchmark v1.0.4 on Ubuntu 18.04 with copying and pasting
seq 0 7 | xargs -p 0 -i node numactl -n node ./randomx-benchmark --mine --largepages --jit --nonces 100000 --init 8 --threads 7

But it gave me such feedback
seq 0 7 | xargs -p 0 -i node numactl -n node ./randomx-benchmark --mine --largepages --jit --nonces 100000 --init 8 --threads 7 0 1 2 3 4 5 6 7 ?...1

Just bumping out such series after the code:  0 1 2 3 4 5 6 7 ?...1

It was not producing any result. Any idea of this problem? I'm a newbie to Ubuntu, any help is much appreciated!

**Comment by scheglina** [comment]
hello, query must contain upper case letters : seq 0 7 | xargs -**P** 0 -**I** node numactl  -**N** node ./randomx-benchmark --mine --largepages --jit --nonces 100000 --init 8 --threads 7
