### ISSUE TITLE
Signature-based detection of Botnet Miners

### ISSUE THREAD

**Issue by PlaneB** [tevador/RandomX#123]
As I understand the discusson on RandomX targeting CPUs vs. GPUs there are basically three concerns:

1.) Lost investment for GPU miners
2.) Spike in security/difficulty due to "server farm attacks"
3.) Botnets

This issue is about point 3. 

AFAIK, Botnets are mostly a concern on less secure operating systems miner, i.e. they run remote CPU minin software on Windows and to a lesser degree on Apple-Stuff.

However these systems usually have some sort of antivirus software installed. Couldn't we use that, by enforcing some sort of publically known signature string in the PoW? Like a valid PoW is a number less then the difficulty, concatenated with a fixed signature? 

Then antivirus software can easily detect a bot that must generate this string all the time. And then the antivirus software handles the rest...

Another direction would be thinking of a way to enforce a pattern string in the mining software itself. Don't know if thats possible, though

**Comment by SChernykh** [comment]
These AES keys have to be included in any RandomX miner: https://github.com/tevador/RandomX/blob/master/src/aes_hash.cpp#L40
https://github.com/tevador/RandomX/blob/master/src/aes_hash.cpp#L117

So there's already a part of RandomX that can be used for signature.

**Comment by PlaneB** [comment]
Interesting, because this is nowhere mentioned in the CPU-mining => Botnet discussion

**Comment by tevador** [comment]
AES keys can be easily obsfuscated, so this technique would detect only malware that uses the reference source code.

However, there are other techniques of detecting a RandomX miner that are much more difficult to hide from. For example, the 2+ GiB memory footprint cannot be avoided and there are some other signatures that could be used to heuristically detect RandomX even in heavily obfuscated malware.

All this could help antiviruses, but unfortunately, a lot of people still run outdated and unpatched operating systems and no antivirus software.

> Another direction would be thinking of a way to enforce a pattern string in the mining software itself.

No such thing can be enforced on the protocol level.

**Comment by PlaneB** [comment]
> > Another direction would be thinking of a way to enforce a pattern string in the mining software itself.
> 
> No such thing can be enforced on the protocol level.

Can you give, at least, some reason, for such an impossibility claim.

**Comment by PlaneB** [comment]
> AES keys can be easily obsfuscated, so this technique would detect only malware that uses the reference source code.

**Comment by tevador** [comment]
Relevant: https://github.com/tevador/randomx-sniffer

**Comment by PlaneB** [comment]
Interesting. THanks.

 
 

Gesendet: Freitag, 29. November 2019 um 21:35 Uhr
Von: "tevador" <notifications@github.com>
An: tevador/RandomX <RandomX@noreply.github.com>
Cc: "Nanao Ei" <mark.neuhaus@email.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [tevador/RandomX] Signature-based detection of Botnet Miners (#123)


Relevant: https://github.com/tevador/randomx-sniffer
