### ISSUE TITLE
Cannot compile under VS2017

### ISSUE THREAD

**Issue by maoxs2** [tevador/RandomX#126]
![image](https://user-images.githubusercontent.com/12538215/65391030-adaade00-dd96-11e9-9bdb-bfd0f6cc030e.png)

same error under vs2019

master branch

**Comment by SChernykh** [comment]
It's a known error in Debug configuration in Visual Studio. Release should compile fine.

**Comment by tevador** [comment]
Yeah, just switch to Release and the error will go away. 

I could remove the assert in debug mode, but at least it shows that JIT mode won't work when compiling in debug mode in Visual Studio.
