### ISSUE TITLE
SWIG support?

### ISSUE THREAD

**Issue by seibelj** [tevador/RandomX#129]
Do you want [SWIG](http://www.swig.org/) support? I am working on it for Python. If you want it, I'll open a PR within a few weeks. My plan is to have it be optionally compiled with a cmake flag `-DSWIG=enabled`. If not, I'll just maintain a fork and use this as upstream. If done properly it shouldn't require any changes in your library code.

**Comment by chilipepperhott** [comment]
Is it possible to build RandomX as a dynamic lib? Not sure, but isn't that required for much of the interop that SWIG provides?
