### ISSUE TITLE
FPU underutilized

### ISSUE THREAD

**Issue by tevador** [tevador/RandomX#13]
Currently, the floating point scheduler is empty about 50% of the time (measured with Ryzen 1700). This means the FPU is underutilized.

Possible solutions:

* Increasing the portion of floating point instructions.
* Adding a simple floating point operation to all integer instructions.

**Comment by hyc** [comment]
There's a large penalty in moving data between general registers and SSE registers. I'd avoid your 2nd choice.

**Comment by tevador** [comment]
I'm aware of that. But we don't have to move anything if we operate only with FPU registers.

For example a single instruction `addpd xmm3, xmm4` (registers could be random). We can add instructions as long as the decoder doesn't become a bottleneck.

**Comment by tevador** [comment]
It seems that the biggest problem will be fitting the extra instructions in the 32K code budget for x86.

Currently, average program is over 30 KiB, so the available space is less than 4 bytes per instruction.

**Comment by tevador** [comment]
Correction: FPU scheduler is empty less than 25% of the time, so the underutilization is not nearly as bad.
