### ISSUE TITLE
CGO Bindings Support

### ISSUE THREAD

**Issue by harryrford** [tevador/RandomX#138]
Not sure how conventional it would be for a go file to live inside the testing files but an API example using cgo bindings would certainly help push adoption and possible re-implementations in other languages.

On a side note, I'm open and ready to contribute to a pure Go implementation of RandomX. If contributors are interested or available let me know.

**Comment by maoxs2** [comment]
https://github.com/maoxs2/go-randomx

I'm using the static lib `librandom.a` to build a cgo binding for random-x. Because I have failed to directly include the `random.h` from random-x source. It seems that golang doesn't support sub-folder(like asm and blake2 this repo) in a cgo project.

**Comment by harryrford** [comment]
Thanks a tone, this clears up the issues I've had when trying to build.

**Comment by maoxs2** [comment]
But this cannot coexist random-x and its variants like random-xl & random-wow, because the static lib `librandomx.a` cannot be modified by different `configuration.h`.

If you have any better solution, we can take a try.
