### ISSUE TITLE
Optimized integer division

### ISSUE THREAD

**Issue by tevador** [tevador/RandomX#14]
Currently, an average program contains 4 integer division instructions (out of 512).

I'm planning to increase it to 32 division instructions. 28 would be divisions by a runtime constant and 4 divisions by a runtime variable.

Integer division by a runtime constant can be [optimized into a multiplication by a fixed-point reciprocal](https://en.wikipedia.org/wiki/Division_algorithm#Division_by_a_constant).

I have implemented this optimization in the JIT compiler and there is no measurable performance drop with 32 divisions per program. Without this optimization, performance drops by around 10% (Intel Sandy Bridge).

This attempts to force an ASIC to do some sort of compilation step or face 8 times more division instructions.

**Comment by SChernykh** [comment]
> This attempts to force an ASIC to do some sort of compilation step or face 8 times more division instructions.

Reciprocal can be calculated once before the execution starts with just a few additional instructions or even a specialized circuit. I don't see how division by a constant can improve anything.

**Comment by SChernykh** [comment]
It can be combined with code generation because you know divisor at generation time. Just scan all instructions and add reciprocal where needed. So pipeline will be `generate->preprocess->execute`

**Comment by tevador** [comment]
@SChernykh The divisor is 32 bits, but the reciprocal is 64 bits, so it will not fit into the original 128 bit instruction. The ASIC would need its own microinstructions, which would require some translation from RandomX code into ASIC native code, just like a CPU.

> So pipeline will be `generate->preprocess->execute`

As opposed to `generate -> execute` if there was no division that can be optimized.

I think this change increases the amount of logic that an ASIC needs (= increased power consumption and costs), while having negligible cost for CPUs.
