### ISSUE TITLE
Trying compile on Msys2 Windows

### ISSUE THREAD

**Issue by BearBang7** [tevador/RandomX#146]
I am tring compile .exe version on windows by MSYS2.
But i got  "Failed to run MSBuild command".
Is there any complate guide to compile from source code on windows via MSYS2?

Here is my log :

<samp>
Gaming-PC@Admin2 MINGW64 ~

$ cmake --version
cmake version 3.12.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

Gaming-PC@Admin2 MINGW64 ~
$ gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 8.2.1 20181214
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Gaming-PC@Admin2 MINGW64 ~
$ git clone https://github.com/tevador/RandomX.git
Cloning into 'RandomX'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 3034 (delta 0), reused 1 (delta 0), pack-reused 3027
Receiving objects: 100% (3034/3034), 2.79 MiB | 135.00 KiB/s, done.
Resolving deltas: 100% (2332/2332), done.

Gaming-PC@Admin2 MINGW64 ~
$ cd RandomX

Gaming-PC@Admin2 MINGW64 ~/RandomX
$ mkdir build && cd build

Gaming-PC@Admin2 MINGW64 ~/RandomX/build
$ cmake -DARCH=native ..
-- Building for: Visual Studio 14 2015
CMake Error in CMakeLists.txt:
  Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 14.0.25420.1
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 10/26/2019 11:35:03 PM.
    Project "C:\Msys2\home\Gaming-PC\RandomX\build\CMakeFiles\3.12.4\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140\Toolset.targets(34,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Msys2\home\Gaming-PC\RandomX\build\CMakeFiles\3.12.4\VCTargetsPath.vcxproj]
    Done Building Project "C:\Msys2\home\Gaming-PC\RandomX\build\CMakeFiles\3.12.4\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Msys2\home\Gaming-PC\RandomX\build\CMakeFiles\3.12.4\VCTargetsPath.vcxproj" (default target) (1) ->
    (Desktop_PlatformPrepareForBuild target) ->
      C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140\Toolset.targets(34,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Msys2\home\Gaming-PC\RandomX\build\CMakeFiles\3.12.4\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.08

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/Msys2/home/Gaming-PC/RandomX/build/CMakeFiles/CMakeOutput.log".

Gaming-PC@Admin2 MINGW64 ~/RandomX/build
</samp>

**Comment by maoxs2** [comment]
```bash
cmake -G "Unix Makefiles" ..
```

**Comment by tevador** [comment]
Visual Studio support was added in #144
