### ISSUE TITLE
Program overhead

### ISSUE THREAD

**Issue by tevador** [tevador/RandomX#15]
Machine code of a RandomX instruction:

![Imgur](https://i.imgur.com/oFa0q27.png)

This ADD_64 instruction needs a total of 60 bytes of code, of which only one 3-byte instruction is the actual addition operation.

The overhead code consists of:
* Checking the termination condition (`bd0`, `bd2`). This is required because of control flow instructions like JUMP/CALL make the sequence of instructions unpredictable.
* Scratchpad read address generation (`bd8`, `bdf`, `bec`)
* Reading from the dataset (`be2`, `be5`, `be7`)
* Scratchpad write address generation (`bf8`-`c03`)

This overhead creates a lot of unavoidable dependency chains which limit the throughput to ~2 instructions per clock.

I've been thinking about a different structure of the program, which somewhat resembles CryptonightR by @SChernykh.

The program would be a loop exactly long enough to fit into the uOP cache of new CPUs (about 1000 instructions in total). Reading from the scratchpad would be done at the beginning of the loop - all 16 registers would be loaded at once. Then only register-register instructions would be executed (long chain) and at the end, registers would be written to the scratchpad and the loop would continue from the beginning.

Since the instruction reorder buffer of x86 CPUs is >100 instructions, they could essentially eliminate all dependency chains in the loop body and execute close to 4 instructions per clock.

Initial tests show that we could generate and execute 16 chained programs with this structure and still get a performance boost over the old scheme.

Advantages:
* higher instruction throughput (= higher latency for in-order ASIC designs)
* lower power consumption due to the use of the uOP cache (decoders can be powered off)
* 16 chained programs to eliminate nonce skipping

Disadvantages
* lower number of random accesses - 8 registers are loaded at once
* no JUMP/CALL/RET instructoins are possible - this is somewhat compensated by the fact that we are generating 16 different programs

**Comment by SChernykh** [comment]
@tevador 1000 instructions with only register operands? But how will you saturate memory bandwidth? And scratchpad updates? Besides, you only have 16 integer and 16 XMM registers (32 AVX registers if we device to use them).

**Comment by tevador** [comment]
> 1000 instructions with only register operands? But how will you saturate memory bandwidth? 

Reading from the 4 GiB dataset would have about the same frequency. The whole 1000-instruction loop is roughly the same length as current 64 VM instructions.

Scratchpad is a little worse. 2 random reads (64 B) and 2 random writes (64 B) per loop iteration, x1024 iterations per program, x16 programs = total of 2 MiB read and 2 MiB written. All writes are into L2, reads are split 3:1 between L1:L2. I think 2 MiB of writes is acceptable for 1 MiB scratchpad. Each program uses a different 256 KiB scratchpad window.

However, there are only 32768 random reads from the scratchpad per hash (down from 1048576) and 32768 random writes (down from 524288). This is the only weakness and may allow the use of external RAM for scratchpads (still many DRAM channels would be required).

**Comment by tevador** [comment]
@SChernykh Done.

Example ASM here: https://github.com/tevador/RandomX/blob/master/tests/small-prog.asm

Comments show the actual RandomX code (256 instructions).

Average program is ~520 μOPs on Ryzen and ~560 μOPs on Skylake ([reference](https://www.agner.org/optimize/instruction_tables.pdf)), so there is still room to add more instructions, but this length matches the original performance.

**Comment by SChernykh** [comment]
@tevador Maybe I miss something, but this program only reads from scratchpad and doesn't write to it. I didn't find any instructions that have memory location as destination operand.

**Comment by tevador** [comment]
All writes happen at the end of the loop (total of 128 bytes per interation). This is the body of the loop, which has no writes, only reads from the scratchpad.

Is it important to write to the scratchpad in the loop body?

**Comment by SChernykh** [comment]
> Is it important to write to the scratchpad in the loop body?

Why not? CPU can do 2 accesses to L1 cache per cycle (2 reads, 2 writes or 1 read+1 write), it's almost free. Writes to L2 are slower, but we surely can do a few.

**Comment by tevador** [comment]
I added store instructions with roughly 1:2 ratio with reads.

Performance is up ~10%, but that's because the program now does fewer actual calculations (some instructions were replaced by stores). So you were right, low amount of writes is essentially free.

With this change, the total amount of writes to the scratchpad is ~5 MiB per hash.

**Comment by tevador** [comment]
I have implemented a new JIT compiler for the short programs and ran some tests.

Some changes have been made to the general structure of the program. The scratchpad is divided into 3 levels:

* L3 = 1024 KiB
* L2 = 256 KiB (first 1/4 of L3)
* L1 = 16 KiB (first 1/16 or L2)

A hash is calculated as follows:
```
hash = Blake2b(input)
InitializeScratchpad(hash);
for i = 0 to 15:
    InitializeProgram(hash)
    ExecuteProgram()
    hash = Blake2b(registerFile)
scratchpadHash = AesHash(scratchpad)
result = blake2b(hash || scratchpadHash)
```
Program is structured like this:
```
for i = 0 to 1023:
    LoadIntegerRegisters(L3)
    LoadFloatingPointRegisters(L3)
    LoopBody()
    MixIntegerRegisters(dataset)
    StoreIntegerRegisters(L3)
    StoreFloatingPointRegisters(L3)
```
LoopBody consists of N random instructions. Instructions operate only with L1 and L2 with a 3:1 access ratio.

Here is an example loop body with 128 instructions: https://github.com/tevador/RandomX/blob/master/tests/small-prog.asm

Depending on N (length of the loop body), we can operate on a scale between a memory-bound PoW and a compute-bound PoW:

N | hashes/s | IPC |  power [W] | comment
-- | -- | -- | -- | --
0 | 6900 | 0.34  | 50 | memory bound
64 | 6400 | 0.78  | 59 | 
**128** | **6000** | **1.12** | **66** |
192 | 5650 | 1.54 | 75 |
256 | 5250 | 1.84 | 81 |
384 | 4350 | 2.18 | 85 |
512 | 3600 | 2.34 | 87 | compute bound

(Tested on Ryzen 1700 with 16 threads).

I think N = 128 is a good choice, because we want to be a little memory bound, since an ASIC can outcompete a CPU in a compute-bound algorithm.

With N = 128, there would be:

* 2 L3 accesses per iteration (64 B each)
* 6 L2 accesses per iteration (8 B each)
* 18 L1 accesses per iteration (8 B each)

There are 16384 iterations per hash. Nonce skipping is not possible due to 16 chained programs.

@SChernykh @hyc comments/ideas?

**Comment by SChernykh** [comment]
Did you try to increase IPC for the same amount of instructions by adjusting code generator? If it generates more independent instructions, IPC should be higher.

**Comment by tevador** [comment]
@SChernykh If I remove all memory accesses apart L1, the loop body runs at ~3.3 IPC with 2 threads per core and ~2.45 IPC with 1 thread per core. With L1 and L2 accesses (3:1 ratio), the numbers decrease to ~3.1 and ~2.1, respectively.

What rules do you suggest for more independent instructions? I'd prefer to avoid any syntax rules for random programs.

In any case, I'm changing my recommendation from N = 128 to N = 256. I did additional profiling and it seems that the core is stalled too much with a shorter loop body (almost 50% of the time). With N = 256, it's still not too compute-bound, so it seems to be a good compromise.

Another idea is to choose N randomly per program, for example between 128 and 383. It could make potential ASIC designs slighly more complicated.

**Comment by SChernykh** [comment]
~3.1 IPC with memory accesses is very good, so further increase is not needed. By the way, how do you count it? Virtual instructions per clock or actual x86 instructions per clock?

**Comment by tevador** [comment]
I used [perf](https://en.wikipedia.org/wiki/Perf_(Linux)).

`sudo perf stat -e cycles,instructions`

I think it counts retired x86 instructions.
