### ISSUE TITLE
ARMV7 not support 

### ISSUE THREAD

**Issue by mSoftDeveloper** [tevador/RandomX#151]
Please support the new algorithm(RandomX) for armv7 ,Thank~

**Comment by hyc** [comment]
See https://github.com/tevador/RandomX/pull/148
The generic interpreter works on ARMv7 already. There's not much point to optimizing further, a 32bit processor will always be at least 4-6 times slower than a 64bit processor. There's no value in mining on 32bit machines.

**Comment by mSoftDeveloper** [comment]
> See #148
> The generic interpreter works on ARMv7 already. There's not much point to optimizing further, a 32bit processor will always be at least 4-6 times slower than a 64bit processor. There's no value in mining on 32bit machines.

Compiling armv7 to generate the so file is to run on the Android device, but has not found a suitable project to compile

**Comment by tevador** [comment]
> Compiling armv7 to generate the so file

randomx is a static library, so there is no .so file, but a .lib file that you have to statically link to an executable.

This is not related to armv7, which is already supported.

**Comment by xaoyaolee** [comment]
> See #148
> The generic interpreter works on ARMv7 already. There's not much point to optimizing further, a 32bit processor will always be at least 4-6 times slower than a 64bit processor. There's no value in mining on 32bit machines.
Could you please help to figure where is the generic interpreter code?
I just find the jit code.
