### ISSUE TITLE
Compilation failure on Windows with VS 2019

### ISSUE THREAD

**Issue by LeMoussel** [tevador/RandomX#155]
I am trying to compile on Windows 10 with Visual Studio 2019 Community Edition.
But I got "Error [A2008](https://docs.microsoft.com/en-us/cpp/assembler/masm/ml-nonfatal-error-a2008?view=vs-2019): Syntax error: studio". on `RandomX\src\asm\configuration.asm`

_**configuration.asm**_

> Visual Studio 2015 Command Prompt variables set.
> ; File start: ..\src\configuration.h
> RANDOMX_ARGON_MEMORY EQU 262144t
> RANDOMX_ARGON_ITERATIONS EQU 3t
> RANDOMX_ARGON_LANES EQU 1t
> RANDOMX_ARGON_SALT TEXTEQU <"RandomX\x03">
> RANDOMX_CACHE_ACCESSES EQU 8t	
> .......

![VS2019-RandomX](https://user-images.githubusercontent.com/1816573/68706700-9a471280-0590-11ea-8fe8-7716a5ba8695.png)

Is there any complete guide to compile from source code on Windows via VS 2019?

**Comment by tevador** [comment]
> Visual Studio 2015 Command Prompt variables set.

This line should not be there. Not sure where it's coming from. See https://github.com/tevador/RandomX/blob/master/src/asm/configuration.asm

The solution builds fine for me in Visual Studio 2019.

**Comment by LeMoussel** [comment]
I found why there's the presence of the line: _Visual Studio 2015 Command Prompt variables set._
In my PowerShell profile I do : `write-host "Visual Studio 2015 Command Prompt variables set." -ForegroundColor Yellow` as described in this [StackOverflow topic](https://stackoverflow.com/questions/2124753/how-can-i-use-powershell-with-the-visual-studio-command-prompt/2124759#2124759) 

I remove the `write-host` command and now it's OK.

Sorry to have wasted your time.
