### ISSUE TITLE
[Benchmark enhancement] Add getchar() or maybe std::cin.get() for windows platform

### ISSUE THREAD

**Issue by YetAnotherRussian** [tevador/RandomX#159]
"Run as administrator" feature (to use huge pages when this is the only way to do that) requires this for the bench results to be seen.

You may add a better solution btw ;-)

**Comment by tevador** [comment]
Non-issue.

You can run `cmd.exe` as administrator and then run the benchmark in the elevated shell. Or create a batch file a put `pause` at the end.
