### ISSUE TITLE
RandomX on HD6990

### ISSUE THREAD

**Issue by Wacholek** [tevador/RandomX#165]
The RIG: 
2x HD 6990 on Windows 7 Catalys 14.4. 

No problem on other algo but RandomX. 
![image](https://user-images.githubusercontent.com/38529376/69907464-171e1d00-13d6-11ea-99ba-fd5dd14288b0.png)

Any ideas?

**Comment by SChernykh** [comment]
This is a bug in compilator, it doesn't even print proper C/OpenCL error message. RandomX OpenCL code is very complex. GPU drivers and their compilators were never perfect, so there's really nothing I can do here.

**Comment by tevador** [comment]
Issue belongs here: https://github.com/xmrig/xmrig/issues
