### ISSUE TITLE
source contains non-free PDF

### ISSUE THREAD

**Issue by jonassmedegaard** [tevador/RandomX#167]
The file `audits/Report-Kudelski.pdf` contains this final paragraph:
> This report and all its content is copyright (c) Nagravision SA 2019, all rights reserved.

That file contains no licensing information, so the explicit reservation of all rights means that the file is not "Free" by some definitions of the term.
Some interpretations of "Free" ignore non-code files, but others don't.

Please either explicitly document how the document is freely licensed, or avoid including it with the source tarball, as that is a burden for some redistribution - including Debian-based distributions which require all sources to comply with the 4 freedoms defined by Debian.

**Comment by tevador** [comment]
@hyc @veorq can you please comment on this? What is the licensing status of the report?

**Comment by hyc** [comment]
The original terms of our SoWs is that all final reports are to be freely redistributable by the Monero Project. We could perhaps request they re-issue a copy of the report with the copyright statement removed/amended.

**Comment by jonassmedegaard** [comment]
Let me elaborate: The freedoms commonly covered by definitions of "Free" are the freedom to use, study, share and modify.  See e.g. [GNU](https://en.wikipedia.org/wiki/The_Free_Software_Definition) and [Debian](https://www.debian.org/intro/free) definitions.

I read "FOR PUBLIC RELEASE" as explicitly permiting free _sharing_ but no other freedoms.

Or put differently, I _do_ see a meaning of "all rights reserved" in this context: Except for explicit permissions (i.e. permission to share as-is), all rights are reserved (i.e. you are not permitted to e.g. make a fork of the document or to reverse engineer it or to share subsets of it).

**Comment by tevador** [comment]
@jonassmedegaard Does this help? #169

**Comment by jonassmedegaard** [comment]
Quoting tevador (2019-12-01 16:41:43)
> @jonassmedegaard Does this help? #169

Dropping the explicit "all rights reserved" helps, yes.

Alternatively, adding explicit licensing whereever explicit copyright 
and/or explicit (non-)licensing (like "all rights reserved") is stated, 
helps as well.

Thanks for considering,

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by hyc** [comment]
I guess in that case "all rights reserved" still carries weight. Certainly no one else has any business modifying their text in any fashion.

**Comment by jonassmedegaard** [comment]
Quoting hyc (2019-12-01 19:08:49)
> I guess in that case "all rights reserved" still carries weight. Certainly no one else has any business modifying their text in any fashion.

Fair enough.  So that means it is closer comparable to the Creative 
Commons "no-derivatives" licenses or RFC documents, neither of which are 
permitted in Debian.

That is very good to have clarified.  I will make sure to strip them 
from the Debian redistribution of this project, and I suggest that you 
double-check if you are permitted to distribute it on Github (and even 
if you are, I encourage you to consider removing it to ease 
redistribution by others).

Kind regards,

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by tevador** [comment]
> I will make sure to strip them from the Debian redistribution of this project

That should be solved in PR #169, which removes the PDFs from the source archive. 

> double-check if you are permitted to distribute it on Github

I'm not a lawyer, but I'd say "FOR PUBLIC RELEASE" would imply yes. AFAIK that was a requirement of the audits that the Monero community funded.

**Comment by veorq** [comment]
Yeah as @hyc commented, Kudelski Security had a agreed that the report be published and was ok to have it in the public repo. Don't remember if these terms are in the SoW, but they're definitely in email records. If needed I can ask for another confirmation by email.

**Comment by jonassmedegaard** [comment]
Quoting Jean-Philippe Aumasson (2019-12-02 09:26:41)
> Yeah as @hyc commented, Kudelski Security had a agreed that the report be published and was ok to have it in the public repo. Don't remember if these terms are in the SoW, but they're definitely in email records. If needed I can ask for another confirmation by email.

Please not that the issue I am raising here is *not* if the PDFs fit distribution requirements for Github - that is only another _related_ issue.

The issue I am raising is that some _other_ distribution channels do not 
permit distribution of free-to-distribute-but-not-to-edit material 
(regardless of Github).

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
