### ISSUE TITLE
Blake2 code wrongly attributed to Argon2 authors

### ISSUE THREAD

**Issue by jonassmedegaard** [tevador/RandomX#168]
Files `src/blake2/bla*` include the following:
> /* Original code from Argon2 reference source code package used under CC0 Licence
> * https://github.com/P-H-C/phc-winner-argon2
> * Copyright 2015
> * Daniel Dinu, Dmitry Khovratovich, Jean-Philippe Aumasson, and Samuel Neves
> */

...but that differ fundamentally from what is stated upstream e.g. at <https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2-impl.h>:
> /*
>    BLAKE2 reference source code package - reference C implementations
>    Copyright 2012, Samuel Neves <sneves@dei.uc.pt>.  You may use this under the
>    terms of the CC0, the OpenSSL Licence, or the Apache Public License 2.0, at
>    your option.  The terms of these licenses can be found at:
>    - CC0 1.0 Universal : http://creativecommons.org/publicdomain/zero/1.0
>    - OpenSSL license   : https://www.openssl.org/source/license.html
>    - Apache 2.0        : http://www.apache.org/licenses/LICENSE-2.0
>    More information about the BLAKE2 hash function can be found at
>    https://blake2.net.
> */

Seems it was wrongly copied from argon2 file.

**Comment by tevador** [comment]
RandomX uses Blake2 from the Argon2 repository, which has this attribution:

https://github.com/P-H-C/phc-winner-argon2/blob/master/src/blake2/blake2b.c

**Comment by jonassmedegaard** [comment]
Ah, indeed. Sorry for the noise!
