### ISSUE TITLE
Design considerations to make potential ASICs more general purpose

### ISSUE THREAD

**Issue by Gingeropolous** [tevador/RandomX#17]
The most common critique of any effort to create an ASIC-proof PoW is that any PoW can be made into an ASIC. The general thought has been to design the PoW such that the eventual ASIC is as costly or efficient as consumer grade hardware. 

What if instead we consider design choices that would make a potential ASIC useful for other applications. This would affect the real-world side of the ASIC-problem - manufacturing centralization, distribution. 

Basically, a CPU is going to run RandomX at 100%. A RandomX ASIC could possibly run RandomX at 200%. But what if a randomX co-processor could be integrated with commodity CPUs to make the final consumer product (some next gen CPU or motherboard) perform consumer-grade tasks at 170% of a standard CPU?
 
Its effectively the same model as integrated graphics. 

So instead of an ASIC manufacturer only having the option of making RandomX ASICs to mine monero, the same circuitry (or IP) could be packaged (or sold) for other purposes. This would get us to the commoditization faster - because what is more profitable if you stumble across a genius design to hack RandomX, printing a bunch of hardware and setting up mines or just selling the IP to intel or AMD? From what I know, these companies are struggling to find ways to make new CPUs better and faster. 

For instance, this type of design choice may re-open #2 , because any advances in branch prediction would provide a boon for *any* situation where a CPU is tasked with running an operating system, or anything (if I understand things correctly).

**Comment by tarris034** [comment]
they are already doing it, AES-NI.
looking at the benchmarks of new CPU's, they are far from struggling to get them faster.

I doubt any of big fishes like Intel / AMD will ever consider adding hardware hashing function specifically for some coin.

**Comment by Gingeropolous** [comment]
so I think cjd is working on something like this. RandomX seems to doing what randomx is doing. so i'll close.
