### ISSUE TITLE
Pre-complied windows binaries fail to start on server 2016

### ISSUE THREAD

**Issue by SN944** [tevador/RandomX#172]
benchmark.exe fails to start on Windows Server 2016 due to the following missing DLLs:

- VCRUNTIME140.dll
- VCRUNTIME140_1.dll
- MSVCP140.dll

**Comment by tevador** [comment]
You have to install the MSVC libraries.

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Should be vc_redist.x64.exe
