### ISSUE TITLE
Intel Skylake microarchitecture document link is wrong

### ISSUE THREAD

**Issue by gsora** [tevador/RandomX#176]
In section [2.8.1](https://github.com/tevador/RandomX/blob/master/doc/design.md#281-scratchpad-levels) the links 25 and 26 are the same.

I believe 26 should be [this](https://en.wikichip.org/wiki/intel/microarchitectures/skylake_(client)#Memory_Hierarchy).

**Comment by tevador** [comment]
Fixed. Thanks.
