### ISSUE TITLE
Generated binaries are not portable due to AVX2

### ISSUE THREAD

**Issue by kpcyrd** [tevador/RandomX#177]
We're currently looking into an issue at archlinux because AVX2 support is tested at buildtime. This is true for the machine used to build the package, but the binary is causing issues for some archlinux users with cpus that don't support this. I assume similar issues are going to show up with AES and SSSE3. We're currently considering building monero with a patched CMakeLists.txt but would rather have an option upstream we can use to build binaries that are supposed to be distributed.

Ideally this would be done with runtime detection though.

Thanks!

**Comment by kpcyrd** [comment]
I managed to fix the arch package by building with `-D ARCH=default`, this disables AVX2 for all users though.

**Comment by tevador** [comment]
> AVX2 support is tested at buildtime

AFAIK the only thing that's tested at build time is if the compiler accepts the `-mavx2` option.

Only the following code files are compiled by default with special instruction sets enabled:

* aes_hash.cpp with `-maes`
* argon2_avx2.c with `-mavx2`
* argon2_ssse3.c with `-mssse3`

The functions that use special instruction sets have to be selected at runtime, so it should not cause problems on machines that don't support them.

**Comment by tevador** [comment]
Advice for the next time: don't pass any `ARCH` options to cmake if you want portable binaries.

**Comment by kpcyrd** [comment]
@tevador I didn't, not passing an explicit value causes the monero build scripts to select a value that enables hardware specific instructions.

**Comment by tevador** [comment]
Yes, hardware-specific instruction sets are enabled for the 3 code files listed above and the implementations have to be selected at runtime using the respective flags (`RANDOMX_FLAG_HARD_AES`, `RANDOMX_FLAG_ARGON2_SSSE3`, `RANDOMX_FLAG_ARGON2_AVX2`). The binaries are still portable. See the API documentation in [randomx.h](https://github.com/tevador/RandomX/blob/master/src/randomx.h) for details.

**Comment by tevador** [comment]
FYI, the randomx library is used by [Monero](https://github.com/monero-project/monero/blob/master/src/crypto/rx-slow-hash.c) and it works just fine on machines without AVX2. The safe way to use the library is to first call `randomx_get_flags()` to see which special instruction sets can be used on the current CPU.
