### ISSUE TITLE
Backward-compatibility

### ISSUE THREAD

**Issue by ldmberman** [tevador/RandomX#180]
Hi,

Is v1.1.7 backward-compatible with the previous releases? I could not find any compatibility notes around.

Thank you in advance,

**Comment by tevador** [comment]
Yes, all versions since v1.1.0 give the same hashes and the API changes didn't affect old functions, only new functions have been added to the interface since then.

So it should be backwards compatible, i.e. code written for v1.1.0 will work with v1.1.7.

**Comment by ldmberman** [comment]
Awesome, thanks

**Comment by ldmberman** [comment]
@tevador could you, please, whether I understand it correctly that the new `randomx_calculate_hash_first` and `randomx_calculate_hash_first` are not in turn backward-compatible, but they account for most of the performance increase in the recent updates?

**Comment by tevador** [comment]
The three new functions (`randomx_calculate_hash_first`, `randomx_calculate_hash_next` and `randomx_calculate_hash_last`) didn't exist in the previous versions, so in that sense they are not 'backwards compatible'. But they still give the same hashes as the original `randomx_calculate_hash` function.

> they account for most of the performance increase in the recent updates

Yes. The largest performance uplift comes from the new batch functions.

**Comment by ldmberman** [comment]
@tevador thank you for the clarification. According to my tests, v1.1.7 is compatible with v1.1.0, but does not seem compatible with v.1.0.4, even if the instruction frequency changes are rolled back, is it true?

**Comment by tevador** [comment]
@ldmberman No. If you undo the instruction frequency changes, then the current master branch will give the same hashes as v1.0.4.

**Comment by ldmberman** [comment]
@tevador oh, I am sorry, I meant to say v1.0.3. For v1.0.3 I get different hashes (with frequencies reverted). Is there an easy way by any chance to make v1.1.7 compatible with v1.0.3?

**Comment by SChernykh** [comment]
The difference between 1.0.4 and previous versions is #76

**Comment by tevador** [comment]
Yes, v1.0.3 and older will give different hashes due to some changes to the AesGenerator used to generate the VM code. In particular, #76 fixes [this issue](https://github.com/tevador/RandomX/issues/64) reported by the Kudelski Security audit. I don't recommend reverting the change.

**Comment by ldmberman** [comment]
Got it, thank you!
