### ISSUE TITLE
librandomx shouldn't throw exceptions

### ISSUE THREAD

**Issue by hyc** [tevador/RandomX#181]
The library exports a C API. C callers can't handle exceptions.

Causing log spam in https://github.com/monero-project/monero/issues/6473

**Comment by tevador** [comment]
AFAIK the library catches all exception it throws, so they don't propagate to the caller of the API.

E.g. 

https://github.com/tevador/RandomX/blob/01381ccef32da29ef4c64209980eb2b1415fc6a4/src/randomx.cpp#L320

If some exceptions leak from the API then it's a bug that should be fixed.

**Comment by moneromooo-monero** [comment]
monero logs exceptions as a debug aid, that exception is not actually leaving the randomx code AFAIK.
