### ISSUE TITLE
example nog working on windows

### ISSUE THREAD

**Issue by xmr-dev** [tevador/RandomX#194]
Hii

I want to build a node addon for randomX but unfortunately your  examples api-example2 and api-example1 are not working. 
Are there any requirements for windows that I should note to? 
When I start press F5 there is nothing happening. The command prompt appears and disappears within seconds

**Comment by tevador** [comment]
The console window closes as soon as the program exits. Try running the executable from a cmd.exe window.

To keep the console window open in Visual Studio, you have to do the following:

1) Right click the api-example project, select Properties.
2) Navigate to Linker -> System
3) Under the SubSystem option, select Console (/SUBSYSTEM:CONSOLE)
4) Build the project.
5) Launch with F5. The console window will stay open.

**Comment by xmr-dev** [comment]
Thank you for your quick response. 

First I got an error that it was complaining about the lib isn't a valid win32 application. That error went away when I set the api-example to `set as startup project`

Then I got a new error
![errror](https://user-images.githubusercontent.com/73394958/97106828-15cba200-16c4-11eb-83d4-af132fb53934.PNG)

**Comment by tevador** [comment]
Switch to the Release build and it should work.

JIT compiler doesn't work when compiling Debug mode in Visual Studio.

**Comment by xmr-dev** [comment]
Thank you for your help, it's working now. 
I will give this project credits for the help in the node-randomx-addon

This can be closed :-)
