### ISSUE TITLE
Branch prediction

### ISSUE THREAD

**Issue by tevador** [tevador/RandomX#2]
Currently, branches are taken/not taken randomly. This is not ideal for CPUs as they rely heavily on branch prediction.

Conditions for branching instructions should be designed such that they produce random repeating patterns.

**Comment by tevador** [comment]
I've done some testing.

In [tests/branch_prediction,](https://github.com/tevador/RandomX/tree/master/tests/branch_prediction) there is a RandomX program translated into C. Only CALL and RET instructions are implemented, the rest is NOP. The program contains 128 CALL/RET instructions and 896 NOPs.

The program has 4 versions with different braching patterns:
* **branch_always** - CALL/RET is always taken.
* **branch_predictably** - One global counter is used to make random regular branching patterns for all CALL/RET instructions.
* **branch_randomly** - CALL/RET is randomly taken/not taken (each instruction has a different probability). An inline [LCG ](https://en.wikipedia.org/wiki/Linear_congruential_generator)is used for random number generation.
* **branch_mixed** - there are 2 types of CALL instructions: first type has the "predictable" branching pattern and a small number of CALL instructions have the "random" branching pattern.

The program uses the perf_event_open syscall to measure the number of hardware branch mispredictions.

```
> ./branch_mixed 1000000
0       1012727
1       1713
2       2586030
VM branches: 135239
```

Index 0 is the number of hardware branch instructions executed, index 1 is the number of mispredictions and index 3 is the runtime measured by the CPU timer.

As expected, the results vary a lot depending the CPU architecture. I have tested Intel Ivy Bridge (Core i3-3220) and AMD Ryzen (R7-1700).

#### Intel Ivy Bridge


  | HW branches | mispred.| runtime | VM branches (VMB) | mispred. per VMB | runtime per VMB
-- | -- | -- | -- | -- | -- | --
branch_always | 1185261 | 278 | 3929248 | 111110 | 0.3% | 112%
branch_predictably | 1000985 | 12233 | 4242161 | 125011 | 9.8% | 107%
branch_randomly | 1271279 | 61055 | 4401908 | 139093 | 43.9% | 100%
branch_mixed | 1012728 | 6897 | 4099282 | 135239 | 5.1% | 96%

#### AMD Ryzen


  | HW branches | mispred.| runtime | VM branches (VMB) | mispred. per VMB | runtime per VMB
-- | -- | -- | -- | -- | -- | --
branch_always | 1185261 | 338 | 2739858 | 111110 | 0.3% | 111%
branch_predictably| 1000984 | 9 | 2543498 | 125011 | 0.0% | 92%
branch_randomly | 1271278 | 62410 | 3077600 | 139093 | 44.9% | 100%
branch_mixed | 1012727 | 1773 | 2587964 | 135239 | 1.3% | 86%

Some interesting observations:

* For this particular program, "always taken" strategy is actually slower per branch than the random strategy
* AMD Ryzen can predict the "predictable" pattern with 100% accuracy
* The "mixed" strategy is the fastest on both CPUs.

The only branch patterns that are usable for RandomX are the random one and the mixed one. However, the performance advantage of the mixed strategy will diminish significantly once the remaining computations are included.

If someone has access to a Linux machine with another CPU architecture, please test the 4 strategies and report results. Makefile is included to build the 4 tests. Run with 1000000 instructions like the example above. Beware that in some cases, the results vary widely between runs, so it's best to run multiple times and calculate the average.

**Comment by wowario** [comment]
Intel Core i5-8250U CPU @ 1.60GHz, average over 10 runs

```
./branch_always 1000000
0	1185262
1	84
2	4956039
VM branches: 111110

./branch_predictably 1000000
0	1000985
1	59
2	5301558
VM branches: 125011

./branch_randomly 1000000
0	1304653
1	49918
2	5590118
VM branches: 139093

./branch_mixed 1000000
0	1012729
1	1986
2	5131497
VM branches: 135239
```

**Comment by fuwa0529** [comment]
How is "runtime per VMB" calculated?

**Comment by fuwa0529** [comment]
#### Ryzen 2200G

  | HW branches | mispred. | runtime | VM branches (VMB) | mispred. per VMB | runtime per VMB
-- | -- | -- | -- | -- | -- | --
branch_always | 1185262 | 139 | 2909838 | 111110 | 0.1% | ?%
branch_predictably | 1262032 | 5386 | 2825920 | 134598 | 4.0% | ?%
branch_randomly | 1304653 | 55902 | 2885222 | 139093 | 40.2% | ?%
branch_mixed | 1364016 | 13485 | 2854595 | 131967 | 10.2% | ?%

**Comment by tevador** [comment]
@fuwa0529 It's the runtime divided by VMB scaled so that branch_randomly = 100%.

For you, it's ~126%, ~101%, 100% and ~104%. Strangely, random is the fastest.

**Comment by fuwa0529** [comment]
I did notice some variation of the result, yet I was being lazy and only ran the test once ...
