### ISSUE TITLE
Guessing all the easy blocks

### ISSUE THREAD

**Issue by linas** [tevador/RandomX#200]
You may dislike what I'm about to say, so sorry, in advance.

It seems as if someone knows how to guess when the easy blocks are going to show up. 

QRL, the ["Quantum Resistant Ledger"](https://github.com/theQRL) uses RandomX. It's a small coin, about 14 MH/sec grand total network hashrate.  [Pool2mine](http://pool2mine.com/#) is a small pool for QRL, about 84KH/sec. So, about 3x or 4x per day, someone joins this pool, mines at a rate of 2-5MH/sec for 2-5 minutes, and then leaves. When they mine, they pick up almost every block, and every block they pick up has a difficulty of 1% to 50%. 

Its as if ... you might think, suspect, that, maybe ... this miner knows exactly when the easy blocks will show up.  Here's some recent activity:
```
Date                 Block     Difficulty of block sequence
24 December  11:30PM 1319505 - 76% 88% 55% 93% 52% 38% 76% 37% 48%
25 December  4:44PM  1320554 - 16%
26 December: 7:51PM  None
27 December  2:03AM  1322615 - 66% 8% 50% 73% 1% 80% 7% 21%
             3:36AM  1322748 - 53% 75%
             9:16AM  1323005 - 20%, 29% 16% 14%
             8:36PM  None
             9:17PM  None
28 December  3:09AM  1324078 - 27% 7% 8%
             5:31AM  1324194 - 94%
             6:55AM  1324248 - 11%, 8% 6% 12% 14%
             4:11PM  1324858 - 62%
``` 
So -- 27 December is a good example. They show up at the indicated time, with maybe 5MH/sec(? see below) hash power (this is maybe(?) 1/3rd(?) of total hash power for this coin), then, starting with block 1322615 they mined almost every block in a row, every 5 to 30 seconds, and then they leave about 7 minutes later.  The network rate is supposed to be one block per minute.

You can view the above at the [Pool Blocks](http://pool2mine.com/#pool_blocks) page.  The hash rate spikes are visible at the [Dashboard](http://pool2mine.com/#). Note that the spikes there are are the hash-rate averaged over half an hour; the instantaneous rate is much higher.  The miner is Q010300...91977ef and is visible in the [top ten charts](http://pool2mine.com/#top10miners)

* This activity has been going on for several months (I'm hoping the pool admin will add to this report, and provide more reliable dates)
* The miner is Q010300...91977ef They've submitted a total of 1985466073088 hashes for about 2335 blocks (so, about $2500 USD) - this is about 60% of the grand total hashes processed by this pool.
* We're guessing it is someone who normally mines monero, where their hash rate is maybe 0.2% of the total monero network rate. But 2x to 4x a day, they show up at QRL to make a quick buck. 

I'm hoping that the pool2mine admin will show up here, and report more precise details on the actual hash rate

You're welcome to dismiss this bug report as a crackpot theory that indicates excessive paranoia, but, for me, this seems like strong evidence that someone knows how to guess exactly when the easy blocks show up.  

I don't know if the coder here is also the mathematician who came up with RandomX, or just the implementation, but someone should take a look at this, and explain to me how I'm wrong. (FWIW I know bucketloads of math, just not very much crypto.)

**Comment by SChernykh** [comment]
Or maybe pool's difficulty % calculation is just biased when such large hash power joins.

**Comment by tevador** [comment]
Unlike some of the previous PoW algorithms, RandomX changes the program every nonce and not every block, so there may be "easy nonces", but there is no such thing as an "easy block".

How we tackled the "easy nonce problem" is explained in the [documentation](https://github.com/tevador/RandomX/blob/master/doc/design.md#12-the-easy-program-problem).

The low pool effort numbers you are seeing are probably caused by the pool underestimating the hashrate of the miner. Pools estimate hashrate based on submitted shares and when a miner connects only for a few minutes, there may not be enough time to properly estimate the hashrate.

The reason the large miner is mining only a few blocks every time is because they are gaming the difficulty adjustment algorithm. It has nothing to do with RandomX.

**Comment by linas** [comment]
@tevador and @SChernykh Thank you! I like that explanation! (I'll dig into it a bit more... this may take a few days ...)

**Comment by linas** [comment]
I'm going to append notes and remarks here, as I find things. I'll keep editing this one comment to add new findings. Hopefully, this will minimize the noise.

* [MiningOcean](https://qrl.miningocean.org/) is seeing the same thing - every few hours, someone comes in with 25MH/sec to 30MH/sec which is 2x the network rate.
* [Herominers](https://qrl.herominers.com/) Is not seeing spiking behavior.

**Comment by linas** [comment]
Thanks, closing. I'll update above comment as I find out more. Meanwhile, I reported this to the pool software via dvandal/cryptonote-nodejs-pool#620
