### ISSUE TITLE
JIT Access violation, epilogueSize less than Zero

### ISSUE THREAD

**Issue by alexander-toschev** [tevador/RandomX#214]
Hello,

On windows 10, 1.19 i found the problem using the --jir switch in JITCompilerX86 init while running benchmark
Exception thrown at 0x00007FFEF04212DE (vcruntime140d.dll) in randomx-benchmark.exe: 0xC0000005: Access violation writing location 0x000001F27FCF355A.

```
code = (uint8_t*)allocMemoryPages(CodeSize);
		memcpy(code, codePrologue, prologueSize);
		memcpy(code + epilogueOffset, codeEpilogue, epilogueSize);	

```

Codesize=77824
prologueSize=150
i believe problem in wrogn epilogue calculation
epilogueSize=-1370

Can you help me?

**Comment by SChernykh** [comment]
It happens if you compile in Visual Studio using Debug or RelWithDbgInfo configurations. Only Release configuration works there.

**Comment by alexander-toschev** [comment]
Thanks!
