### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by oliverw** [tevador/RandomX#215]
Is it safe to call `randomx_calculate_hash` using the same VM argument from multiple threads simultaneously or does the VM have to be guarded by a mutex?

**Comment by SChernykh** [comment]
VM is used to calculate single hash at a time, it's not thread safe. Miner uses one VM per thread.

**Comment by oliverw** [comment]
Thanks!

**Comment by gmpassos** [comment]
When creating multiple VMs, can I reuse the same `dataset` (created by `randomx_alloc_dataset`)?

I'm just trying to optimize the memory allocation of the process.
