### ISSUE TITLE
Benchmark fails to run on 2012 Macbook in v1.1.9 (works in v1.1.8)

### ISSUE THREAD

**Issue by cryptonote-social** [tevador/RandomX#216]
Machine details:

>   Model Name:	MacBook Pro
>   Model Identifier:	  Model Name:	MacBook Pro
>   Model Identifier:	MacBookPro8,2
>   Processor Name:	Intel Core i7
>   Processor Speed:	2.2 GHz
>   Number of Processors:	1
>   Total Number of Cores:	4
>   L2 Cache (per Core):	256 KB
>   L3 Cache:	6 MB
>   Memory:	4 GB
>   Boot ROM Version:	87.0.0.0.0
>   SMC Version (system):	1.69f4MacBookPro8,2
>   Processor Name:	Intel Core i7
>   Processor Speed:	2.2 GHz
>   Number of Processors:	1
>   Total Number of Cores:	4
>   L2 Cache (per Core):	256 KB
>   L3 Cache:	6 MB
>   Memory:	4 GB
>   Boot ROM Version:	87.0.0.0.0
>   SMC Version (system):	1.69f4

Steps to reproduce:

> 1233][oldlaptop][~/src/github.com/tevador/RandomX/build]: git checkout v1.1.9
> HEAD is now at fe4324e Merge pull request #213 from hyc/m1typo
> [1234][oldlaptop][~/src/github.com/tevador/RandomX/build]: make -j 3
> [  8%] Building C object CMakeFiles/randomx.dir/src/argon2_ssse3.c.o
> ...
> [100%] Linking CXX executable randomx-tests
> [100%] Built target randomx-tests
> [1235][oldlaptop][~/src/github.com/tevador/RandomX/build]: ./randomx-benchmark --mine --jit --auto
> RandomX benchmark v1.1.8
>  - Argon2 implementation: SSSE3
>  - full memory mode (2080 MiB)
>  - JIT compiled mode 
>  - hardware AES mode
>  - small pages mode
>  - batch mode
> Initializing (8 threads) ...
> Memory initialized in 14.4383 s
> Initializing 1 virtual machine(s) ...
> ERROR: Cannot create VM with the selected options. Try using --softAes

Note that if I use v1.1.8 everything is fine:

> [1236][oldlaptop][~/src/github.com/tevador/RandomX/build]: git checkout v1.1.8
> Previous HEAD position was fe4324e Merge pull request #213 from hyc/m1typo
> HEAD is now at 5ce5f49 add --noBatch benchmark option
> [1237][oldlaptop][~/src/github.com/tevador/RandomX/build]: make -j 3
> CMake Deprecation Warning at CMakeLists.txt:29 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- Setting default build type: Release
> -- Setting CXX flag -maes
> -- Setting C flag -maes
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/dad/src/github.com/tevador/RandomX/build
> Consolidate compiler generated dependencies of target randomx
> [  8%] Building CXX object CMakeFiles/randomx.dir/src/cpu.cpp.o
> ...
> [ 26%] Linking CXX static library librandomx.a
> [ 79%] Built target randomx
> Consolidate compiler generated dependencies of target randomx-tests
> Consolidate compiler generated dependencies of target randomx-codegen
> Consolidate compiler generated dependencies of target randomx-benchmark
> [ 82%] Linking CXX executable randomx-codegen
> [ 88%] Building CXX object CMakeFiles/randomx-benchmark.dir/src/tests/benchmark.cpp.o
> [ 88%] Building CXX object CMakeFiles/randomx-tests.dir/src/tests/tests.cpp.o
> [ 91%] Built target randomx-codegen
> [ 94%] Linking CXX executable randomx-benchmark
> [ 97%] Built target randomx-benchmark
> [100%] Linking CXX executable randomx-tests
> [100%] Built target randomx-tests
> [1239][oldlaptop][~/src/github.com/tevador/RandomX/build]: ./randomx-benchmark --mine --jit --auto
> RandomX benchmark v1.1.8
>  - Argon2 implementation: SSSE3
>  - full memory mode (2080 MiB)
>  - JIT compiled mode 
>  - hardware AES mode
>  - small pages mode
>  - batch mode
> Initializing (8 threads) ...
> Memory initialized in 13.4588 s
> Initializing 1 virtual machine(s) ...
> Running benchmark (1000 nonces) ...
> ...

**Comment by hyc** [comment]
See if this helps
[diff.txt](https://github.com/tevador/RandomX/files/6871483/diff.txt)

**Comment by cryptonote-social** [comment]
Works! Thank you @hyc

**Comment by hyc** [comment]
Actually, just to be sure - can you test it the opposite way too? Add this change as well:
````
diff --git a/src/virtual_memory.cpp b/src/virtual_memory.cpp
index 117e0a2..e3cc3c8 100644
--- a/src/virtual_memory.cpp
+++ b/src/virtual_memory.cpp
@@ -36,7 +36,7 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #ifdef __APPLE__
 #include <mach/vm_statistics.h>
 #include <TargetConditionals.h>
-# if defined(__aarch64__) && TARGET_OS_OSX
+# ifdef TARGET_OS_OSX
 # define USE_PTHREAD_JIT_WP    1
 # include <pthread.h>
 # endif
````
