### ISSUE TITLE
`code-generator.cpp` appears to use the wrong hash function when generating native

### ISSUE THREAD

**Issue by ChrisKitching** [tevador/RandomX#221]
Shouldn't this:
https://github.com/tevador/RandomX/blob/master/src/tests/code-generator.cpp#L72

Be a call to `fillAes4Rx4` instead of `fillAes1Rx4`?

As-is, it appears that generateNative makes its random program using `AesGenerator1R` instead of `AesGenerator4R`?

... Or am I just being dense ? :D

**Comment by tevador** [comment]
You are right, this was overlooked when the hash function was changed in #46 

Fixed in #224
