### ISSUE TITLE
Need ARMv8 support

### ISSUE THREAD

**Issue by hyc** [tevador/RandomX#23]
Are you planning to write the ARM support or do we need someone to do this?
It's not clear to me how much needs to be ported at the moment.

**Comment by tevador** [comment]
For hash verification, the interpreted VM is meant to be portable, so no ARM-specific code is needed there.

Only the JIT compiled VM must be ported into ARMv8 for efficient mining. The equivalent of [JitCompilerX86.cpp](https://github.com/tevador/RandomX/blob/master/src/JitCompilerX86.cpp) is needed plus some static assembly files that are found in [src/asm](https://github.com/tevador/RandomX/tree/master/src/asm).

I'm not familiar with ARMv8 assembly enough to write it myself.

**Comment by hyc** [comment]
For future reference, not even sure if this was needed for an ARM backend
````
geekbox@geekbox:/home/software/RandomX$ make
g++ -std=c++11 -march=armv8-a+crypto -O3 -flto -c src/CompiledVirtualMachine.cpp -o obj/CompiledVirtualMachine.o
In file included from src/CompiledVirtualMachine.hpp:25:0,
                 from src/CompiledVirtualMachine.cpp:20:
src/intrinPortable.h: In function ‘__m128d load_cvt_i32x2(const void*)’:
src/intrinPortable.h:178:27: error: ‘_mm_cvtepi32_pd’ was not declared in this scope
  return _mm_cvtepi32_pd(ix);
                           ^
makefile:60: recipe for target 'obj/CompiledVirtualMachine.o' failed
make: *** [obj/CompiledVirtualMachine.o] Error 1
````
cvtepi32_appears to take a vector of 2 32bit ints and return a vector of 2 64bit floats.
On ARMv8 I didn't find an exactly corresponding instruction; the vector float conversions only
return a result of the same size. E.g. 2 32bit ints -> 2 32bit floats, or 2 64bit ints -> 2 64bit floats.

**Comment by tevador** [comment]
@hyc This part is not yet fully portable, it uses x86 intrinsics at the moment, but I'm working on a portable version.

As for the conversion instruction, the corresponding ARM VFP instruction should be `vcvt.f64.s32` based on what I could find online.

**Comment by hyc** [comment]
OK, if this part isn't meant to be portable then probably not worth worrying about for now.

VCVT is only part of the AARCH32 instruction set, removed in AARCH64. Look around for ARM_v8_Instruction_Set_Architecture_(Overview).pdf for info.

**Comment by tevador** [comment]
> VCVT is only part of the AARCH32 instruction set, removed in AARCH64

I wasn't aware of that. It will be important for the ARMv8 JIT compiler, which needs to implement the equivalent of `cvtdq2pd` because it's used to convert floating point operands loaded from the scratchpad. So ARM will need at least 1 load and 2 scalar conversions.

**Comment by hyc** [comment]
Current code now running on ARMv8
````
geekbox@geekbox:/home/software/RandomX$ bin/randomx --softAes
Using software AES.
RandomX - verification mode
Initializing...
Cache (256 MiB) initialized in 4.0222 s
Initializing 1 virtual machine(s)...
Running benchmark (1000 nonces) ...
Calculated result: fe31e8fd7ed1cec773e87c0684b66b38e58b23ab255e8f9c6b62745e43a26851
Reference result:  fe31e8fd7ed1cec773e87c0684b66b38e58b23ab255e8f9c6b62745e43a26851
Performance: 447.91 ms per hash
````

This box has only 2GB RAM so I can't run the mining mode test.

**Comment by tevador** [comment]
@hyc I realized that porting [SquareHash ](https://github.com/tevador/RandomX/blob/master/doc/dataset.md#squarehash) into ARMv8 is probably more critical for verification performance than AES.

The x86 assembly version is linked in the documentation above. I think it should be pretty straightforward to translate.

**Comment by foRevp2p** [comment]
Any progress on the matter?

`ERROR: JIT compilation is not supported or cache allocation failed`

Seems like jit will be mandatory for ARM mining competition.

Getting around 60 h/s on "MoneroX" ( 8 threads ). ( no jit )

**Comment by esfomeado** [comment]
> 
> 
> Any progress on the matter?
> 
> `ERROR: JIT compilation is not supported or cache allocation failed`
> 
> Seems like jit will be mandatory for ARM mining competition.
> 
> Getting around 46 h/s on "MoneroX" ( 8 threads ). ( no jit )

With what processor you get 46 h/s?

**Comment by rbthomp** [comment]
I'm getting around 45 h/s on ARMv8 3GB ( 8 threads ). Curious what performance gains JIT would bring.

**Comment by konstantintuev** [comment]
Has someone added JIT support for arm64 unofficially (in a fork) or is at least trying to?

**Comment by bitcoin-hub** [comment]
> I'm getting around 45 h/s on ARMv8 3GB ( 8 threads ). Curious what performance gains JIT would bring.

Could you tell me how to compile on ARM device and run it on Android? Thank you, please.

**Comment by esfomeado** [comment]
> Could you tell me how to compile on ARM device and run it on Android? Thank you, please.

Without JIT support is just a wast of time.

**Comment by SChernykh** [comment]
https://github.com/tevador/RandomX/pull/125

**Comment by esfomeado** [comment]
RPi4
```
root@ubuntu:/home/ubuntu/xmr/RandomX/build# ./randomx-benchmark --verify --jit --softAes
RandomX benchmark v1.1.1
 - light memory mode (256 MiB)
 - JIT compiled mode
 - software AES mode
 - small pages mode
Initializing ...
Memory initialized in 2.32189 s
Initializing 1 virtual machine(s) ...
Running benchmark (1000 nonces) ...
Calculated result: 10b649a3f15c7c7f88277812f2e74b337a0f20ce909af09199cccb960771cfa1
Reference result:  10b649a3f15c7c7f88277812f2e74b337a0f20ce909af09199cccb960771cfa1
Performance: 79.0238 ms per hash
root@ubuntu:/home/ubuntu/xmr/RandomX/build# ./randomx-benchmark --mine --jit --softAes
RandomX benchmark v1.1.1
 - full memory mode (2080 MiB)
 - JIT compiled mode
 - software AES mode
 - small pages mode
Initializing (1 thread) ...
Memory initialized in 116.203 s
Initializing 1 virtual machine(s) ...
Running benchmark (1000 nonces) ...
Calculated result: 10b649a3f15c7c7f88277812f2e74b337a0f20ce909af09199cccb960771cfa1
Reference result:  10b649a3f15c7c7f88277812f2e74b337a0f20ce909af09199cccb960771cfa1
Performance: 46.811 hashes per second
```

Shouldn't be faster in mine mode?

**Comment by SChernykh** [comment]
You need to enable large paes: `--largePages` and also improve cooling on your RPi. RandomX is very heavy on CPU, heatsink and airflow is a must.

**Comment by tevador** [comment]
> Shouldn't be faster in mine mode?

It is faster.

Verification mode: `1000 / 79 = 12.7 H/s`.
Mining mode: `46.8 H/s`

~4x faster in mining mode.

Your CPU has 4 cores, so you can increase the hashrate with `--threads 4`.
