### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KilimSerg** [tevador/RandomX#232]
I apologize in advance, but my lack of knowledge of the English language was translated with the help of Google translator.

Hello!
Unfortunately, I don't have a lot of C + + programming experience,
but I really want to experiment with the RandomX library.
I figured out a little about the principle of the miner program using an example
Python 'Stratum miner' - https://github.com/jtgrassie/monero-powpy
Now I want to try to work directly with the RandomX library in C + +, but I have problems how to properly prepare the data for the function:
"Randomx_calculate_hash (myMachine, & myInput, sizeof myInput, hash)"
Using the example of a real task from the pool, you can explain what data you need to take in order to properly prepare the input parameters for the “randomx_calculate_hash (..)” function

Pool task:
{
"blob":"0e0eb5dfac8d06f83becaad30671039b62073f666d9ab6d3ff68ea0558abd3c583945603e9a93f0000000088a3bd91ce349ee0e730ff2479e0c87a31fde9bae14ce3b25ce688da8af1604121", 
"job_id": "c2097fba-66f6-4c1c-90aa-bed41323b8a2", 
"target": "a4000200", 
"id": "3d3edc1d-c720-4e17-b9ca-587224517c4c", 
"timestamp": 1638608881008, 
"height": 2507377, 
"algo": "rx/0", 
"variant": "rx/0", 
"seed_hash": "5ab039574d1c5b6cf294edeb4d7012e448b8eaa89e546ed33a26aad8c5ea31f3"
}

How to prepare data correctly:

const char myKey [] = "RandomX example key";

const char myInput [] = "RandomX example input";

Thanks in advance Sergey.

**Comment by SChernykh** [comment]
https://github.com/tevador/RandomX/blob/master/src/tests/api-example2.cpp

**Comment by KilimSerg** [comment]
In the api-example2.cpp example, there is no way to correctly form “const char myKey []“  and “const char myInput []“.
But just how to split the task into two threads.
And I need to get these two parameters from the data that the pool gives.

**Comment by SChernykh** [comment]
myKey = seed_hash
myInput = blob
Convert both from hex to binary first.

**Comment by KilimSerg** [comment]
Thank you!.
And in Python 'Stratum miner' - https://github.com/jtgrassie/monero-powpy, the "height" block number was also used, but for what purposes is it needed there?

**Comment by SChernykh** [comment]
> Thank you!. And in Python 'Stratum miner' - https://github.com/jtgrassie/monero-powpy, the "height" block number was also used, but for what purposes is it needed there?

Because it uses `rx_slow_hash` function from the Monero codebase. The API example I gave doesn't require `height` parameter.

**Comment by KilimSerg** [comment]
OK!
Thank you.

**Comment by KilimSerg** [comment]
Tell me, do you need to convert “string to binary to char” or “char to binary” at once?

**Comment by KilimSerg** [comment]
I did as you recommended by analogy with the example api-example1.cpp and everything worked out for me
CODE № 1.
With seed hash1 = "5ab039574d1c5b6cf294edeb4d7012e448b8eaa89e546ed33a26aad8c5ea31f3"
and blob + nonce = "0e0ec5deac8d0698faba839506b0ad612c9279f1cc6c52742fe98746e11af01003843883
aa14543a2200009610ff8702652a54bdce747107eca58543a0211bbefc6bf8010080c9ea148f6613 "
I got   hash = 975FEDA574F5126C2CA2E7A928213CDBA55E1EF4AD0131B7EF3AAACC96B90000
I know for sure that this hash is correct.

In the api-example1.cpp example, the RandomX library runs in slow mode.
I decided to switch it to fast mode as in the api-example2.cpp example.
But I didn't add threads as it was done in the example api-example2.cpp CODE № 2.
The RandomX library started to work faster, but the hash is completely different, although the preparation in the data has not changed.
Instead of correct hash = 975FEDA574F5126C2CA2E7A928213CDBA55E1EF4AD0131B7EF3AAACC96B90000
CODE № 2 gives
Hash=
9D26E1481B0B7885EDD49BF0FF55CBADD77445EC6DFB9BACE72FEA4EF7FBEE29

Please see what I did wrong in CODE № 2.

CODE №1.
#include "randomx.h"
#include <string>
#include <iostream>
#include <stdio.h>
#include <boost/algorithm/hex.hpp>

using namespace boost::algorithm;
using namespace std;

int main()
{
    std::string output;
    output.resize(32);
    // seed_hash
    std::string seed_hash1 = "5ab039574d1c5b6cf294edeb4d7012e448b8eaa89e546ed33a26aad8c5ea31f3";
    // blob + nonce
    std::string blob1 = "0e0ec5deac8d0698faba839506b0ad612c9279f1cc6c52742fe98746e11af01003843883aa14543a2200009610ff8702652a54bdce747107eca58543a0211bbefc6bf8010080c9ea148f6613";

    std::string seed_hash = unhex(seed_hash1);
    std::string blob = unhex(blob1);

    const char* myKey = seed_hash.c_str();
    const char* myInput = blob.c_str();
   
    randomx_flags flags = randomx_get_flags();
    randomx_cache* myCache = randomx_alloc_cache(flags);
    randomx_init_cache(myCache, myKey, seed_hash.size());
  
    randomx_vm* myMachine = randomx_create_vm(flags, myCache, NULL);

    randomx_calculate_hash(myMachine, myInput, blob.size(), &output[0]);

    std::string s = hex(output);
    std::cout << "hash = " << s << std::endl;
  
    randomx_destroy_vm(myMachine);
    randomx_release_cache(myCache);

    system("pause");
    return 0;
}

CODE №2.
#include "randomx.h"
#include <string>
#include <iostream>
#include <stdio.h>
#include <boost/algorithm/hex.hpp>

using namespace boost::algorithm;
using namespace std;

int main()
{
    std::string output;
    output.resize(32);
    // seed_hash
    std::string seed_hash1 = "5ab039574d1c5b6cf294edeb4d7012e448b8eaa89e546ed33a26aad8c5ea31f3";
    // blob + nonce
    std::string blob1 = "0e0ec5deac8d0698faba839506b0ad612c9279f1cc6c52742fe98746e11af01003843883aa14543a2200009610ff8702652a54bdce747107eca58543a0211bbefc6bf8010080c9ea148f6613";

    std::string seed_hash = unhex(seed_hash1);
    std::string blob = unhex(blob1);

    const char* myKey = seed_hash.c_str();
    const char* myInput = blob.c_str();
   
    randomx_flags flags = randomx_get_flags();
    flags |= RANDOMX_FLAG_LARGE_PAGES;
    flags |= RANDOMX_FLAG_FULL_MEM;
    randomx_cache* myCache = randomx_alloc_cache(flags);
    if (myCache == nullptr) {
        std::cout << "Cache allocation failed" << std::endl;
        return 1;
    }

    randomx_init_cache(myCache, myKey, seed_hash.size());

    randomx_dataset* myDataset = randomx_alloc_dataset(flags);
    if (myDataset == nullptr) {
        std::cout << "Dataset allocation failed" << std::endl;
        return 1;
    }
    randomx_release_cache(myCache);

    randomx_vm* myMachine = randomx_create_vm(flags, nullptr, myDataset);
    if (myMachine == nullptr) {
        std::cout << "Failed to create a virtual machine" << std::endl;
        return 1;
    }

    randomx_calculate_hash(myMachine, myInput, blob.size(), &output[0]);

    std::string s = hex(output);
    std::cout << "hash = " << s << std::endl;
  
    randomx_destroy_vm(myMachine);
    randomx_release_dataset(myDataset);

    system("pause");
    return 0;
}

**Comment by KilimSerg** [comment]
Hello!
I managed to figure out examples of using the RandomX library.
By entering the initial data known to me in advance, I was able to obtain a known cache in both examples.
As I understood the first example api-example1.cpp this is the work of the library in light mode and the speed of calculating 1 hash was 0.027 seconds for me.
The second example api-example2.cpp is the library's work in fast mode and the computation speed 1 hash was 0.006 - 0.007 seconds for me.
The difference in operating speed between light and fast mode is approximately 4.2 times.
In the documentation, I read that the difference in speed between fast and light modes can be up to 8 and in some sources and up to 10 times.
In the documentation, I found only one parameter that is directly related to the speed of work between light and fast modes, this is RANDOMX_CACHE_ACCESSES.
But its change in the range from 2 to 200 did not lead to a change in the speed of the fast mode, as it remained in the region of 0.006 - 0.007 and remains.
Prompt by changing what parameters and within what limits you can increase the speed of the fast mode.
