### ISSUE TITLE
Customizing RandomX for an existing processor

### ISSUE THREAD

**Issue by KilimSerg** [tevador/RandomX#234]
Hello!
I'm trying to write a C++ miner for monero mining, and basically I've already written it and it works.
My computer is quite old because the prices for the current hardware have soared so much that I can’t buy something new yet. At the moment, I get about 150 hashes per core on my computer.
My processor
CPU type QuadCore AMD Phenom II X4 Black Edition 965, 3400 MHz (17 x200)
      Instruction sets x86, x86-64, MMX, 3DNow!, SSE, SSE2, SSE3, SSE4A
      Min/Max CPU multiplier 5.0x / 31.5x
      Engineering Sample No
      L1 code cache 64 KB per core
      L1 data cache 64 KB per core
      L2 cache 512 KB per core (On-Die, ECC, Full-Speed)
      6 MB L3 Cache (On-Die, ECC, NB-Speed)

However, I tried to run “xmrig” on my computer and it manages to overclock 198-199 hashes per core.
To communicate with the RandomX library in my own way, I use the rx-slow-hash(...)
I tried to use the RandomX library directly and it worked but only on one thread. When I tried to use all 4 processor cores, I got an error related to the cache.
And then I tried to change the parameters of the library itself in order to get the maximum
possible hashrate for your hardware.
I modified the “api-example2.c” example, which included the well-known
seed hash = "5ab039574d1c5b6cf294edeb4d7012e448b8eaa89e546ed33a26aad8c5ea31f3"

nonce = 8762 = 3a220000
 
blob + nonce ="0e0ec5deac8d0698faba839506b0ad612c9279f1cc6c52742fe98746e11af0
1003843883aa14543a2200009610ff8702652a54bdce747107eca58543a0211bbefc6bf8010080c9ea148f6613"
 
I know that with such parameters the following hash should be obtained:
hash = 975feda574f5126c2ca2e7a928213cdba55e1ef4ad0131b7ef3aaacc96b90000
I know for sure that this hash is correct.

And with the default RandomX library parameters, I got this hash.
In the description of the library, the parameters of the processor cache were indicated
16 KB L1 cache,
256 KB L2 cache
2 MB L3 cache 
per mining thread

However, in my processor, the L3 cache memory is only 6 MB for the entire processor
Then I tried to reduce the L3 value in the RandomX library to 1 MB so that each flood had 1 megabyte.
The time for calculating 1 hash has really decreased and ideally now it can correspond to about 199-200 hashes per second, but the result has become inconsistent with what it should be.
And no matter how I tried further, what parameters I didn’t change anyway, either I get an error, or the hash turns out to be inconsistent with what it should be.
Naturally, when changing the parameters, I took into account the so-called “unsafe configurations” that are given in the description.
For programming, I use the Visual Studio 2019 program, after each change in parameters, I compile randomx.h and randomx.dll on a new one.
I can't figure out what I'm doing wrong because the description of the library says that the parameters can be changed!

But why do I get the wrong result with every change, and the correct result is obtained only with the default values of the library?
Can you tell me how to properly configure the RandomX library for specific processor parameters, maybe I'm doing something wrong when compiling, maybe I need to compile some other file besides randomx.h and randamx.dll?
Best regards, Sergey.

**Comment by tevador** [comment]
> But why do I get the wrong result with every change, and the correct result is obtained only with the default values of the library?

Obviously, when you change the parameters, you are creating a new PoW function that will give different results.

If you want to mine Monero, you can't change the parameters. You can change the parameters if you want to tweak the algorithm for another cryptocurrency. For example, Wownero has decreased the L3 size to 1 MB.

**Comment by tevador** [comment]
> It’s strange, how then the library works on computers that don’t have an L3 cache at all

It's not strange at all. Have a look [how CPU caches work](https://en.wikipedia.org/wiki/CPU_cache). If there is not enough cache, the CPU will simply use RAM. However, RAM is much slower than cache.

> whether it is possible to somehow configure for a specific processor

There are basically only 2 main "configuration" options for a specific CPU:

* Select the correct number of mining threads. In general, this should be 1 thread per 2 MB of cache.
* Enable the hardware AES implementation, if supported by the CPU. This can be done automatically by using the `randomx_get_flags()` function to obtain the best flags for the current CPU.

If the CPU has less than 2 MB of cache or doesn't support hardware AES, then there is no point in mining as the performance will be poor. But it should still be usable for testing or verification.

**Comment by KilimSerg** [comment]
Thanks for the reply, it cleared things up a bit.
I found the description of the flags in randomx.h, each of them has a numerical expression.
Are these numbers constant?
Or they may change depending on any conditions.
If yes, from what?
