### ISSUE TITLE
Configuration advice to avoid network attacks

### ISSUE THREAD

**Issue by wizeguyy** [tevador/RandomX#238]
In `doc/configuration.md` the following advice is given:
> We recommend each project using RandomX to select a unique configuration to prevent network attacks from hashpower rental services.

Can anyone elaborate on this and perhaps provide context in the doc?

As I see it, to avoid network attacks, it is only necessary to change a single parameter. e.g. changing `RANDOMX_ARGON_SALT` to a project specific string. Changing more parameters beyond that, would only serve to alter the complexity/difficulty of a RandomX implementation; this would only mitigate network attacks if the new parameters disproportionately favor certain types of hardware over the default configuration.

Put differently: as long as the hardware requirements remain approximately equal, changing many parameters affords no greater mitigation against network attacks than merely changing the Argon salt parameter.

Is my understanding correct? If so, it might be a good idea to expand on the tradeoffs a bit in that document. (I'm happy to submit a patch).

Thanks for all the hard work!

**Comment by SChernykh** [comment]
NiceHash has only RandomX Monero variant, so it's impossible to rent their hashpower to attack other coins. MiningRigRentals has multiple RandomX variants, but you can't use rigs mining one RandomX variant to attack some other coin.

**Comment by wizeguyy** [comment]
Thanks for confirming.

> If so, it might be a good idea to expand on the tradeoffs a bit in that document.

How do you feel about adding a comment to this effect:
https://github.com/wizeguyy/RandomX/commit/c7470972fcf9a4ddfdd62348c0c701ed930a84b5

I think its valuable to distinguish the two reasons someone may wish to change parameters:
1) to make their config incompatible with other networks => just change Argon salt
2) to change the hardware performance/requirements => use any of the other 44 parameters

Feel free to shoot me down if this is not helpful. Thanks again!
