### ISSUE TITLE
Low Hash Rate

### ISSUE THREAD

**Issue by jwzheng96** [tevador/RandomX#239]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/32029023/165475645-6c14206f-cae5-47ae-a672-a57559d22d52.png">

**Comment by jwzheng96** [comment]
Benchmark of 1.1.19 version running on MacOS M1 chips shows extremely low hash rates compared to what shown in readme. Does anyone know why?

**Comment by SChernykh** [comment]
The answer is in your own screenshot
```
WARNING: You are using the interpreter mode. Use --jit for optimal performance.
```
Also `--softAes` parameter reduces performance.

**Comment by VYOM00907** [comment]
Greetings,
I am a newbie in this RandomX world I need help with compiling and editing .
Which tools are needed to compile and edit source .
