### ISSUE TITLE
Trying to cross compile RandomX

### ISSUE THREAD

**Issue by Nyuu** [tevador/RandomX#245]
Hi ^^
For the last hours i was trying to crosscompile randomx. i have amd64 (uname -p => X86_64)
If i specified the -DARCH option with different architectures, i still got x86_64 binaries so i looked into the cmake file.
Specifying -DARCH_ID=aarch64 or arm64 or armv8-a did yield different results in that the make now fails with this message: "RandomX/src/jit_compiler_a64_static.S:34: Error: no such architecture: `armv8'"
And the output of every line in the jit_compiler_a64_static.S saying that there is no such instruction.

Specifying -DARCH_ID=ppc64 or ppc64le builds the first binary, but as X86_64 and then fails with:
librandomx.a(randomx.cpp.o): In function `randomx_alloc_cache':
randomx.cpp:(.text+0x277): undefined reference to `randomx::JitCompilerX86::JitCompilerX86()'
randomx.cpp:(.text+0x33c): undefined reference to `randomx::JitCompilerX86::JitCompilerX86()'
librandomx.a(randomx.cpp.o): In function `randomx::CompiledVm<randomx::LargePageAllocator, false, false>::~CompiledVm()'

and much more lines.

I don't know what i am doing wrong :(
Trying the option -DCMAKE_SYSTEM_PROCESSOR to specify the arch did not help either. This was the first thing i did before looking into the cmake file. It gets set when no -DARCH is specified to the current system.

I do not have much experience with building from source yet, especially with cmake so i appreciate your input.

**Comment by hyc** [comment]
Sounds like the compiler you're using doesn't support cross compilation to other architectures.

**Comment by Nyuu** [comment]
Thank you for the reply.
I thought that CMake handles this and creates an architecture specific makefile and selects the correct compilers (or throws errors if none are found).
I will try and figure it out myself now that i have some time and to learn something new.
Thanks ^^
