### ISSUE TITLE
Problem with compiling on win32 " undefined reference to `randomx_get_flags'"

### ISSUE THREAD

**Issue by Dentordev** [tevador/RandomX#252]
![image](https://user-images.githubusercontent.com/92227212/189433173-6bd3e309-6558-4c76-9230-df2137684e4c.png)

I believe this problem might be newer but I copied over api-example.c outside of the library. (Renamed it to test.c) because I'm planning to make a Cython/Python RandomX library for easy compilation for other developers to help with compiling on over to .so and .pyd but I am trouble with making it because of this issue. Does anyone know of a workaround for this kind of problem I'm currently facing? I'm using RandomX 1.1.10.  And I'm newer to C++. Just A note that I am Working with Visual Studio Code and Not Visual Studio. I have a gcc compiler that is  8.1.0  and I'm using mingw. I would use Cmake but I don't know what configuration to do to make it work when compiling with Cython.

**Comment by tevador** [comment]
This is not an issue with this repository.

You have to link to `librandomx.a` if you want to call functions from there. Refer to some gcc tutorial, e.g. https://www.linuxtopia.org/online_books/an_introduction_to_gcc/gccintro_17.html

It's better to use cmake, which will handle all this for you automatically.

**Comment by KaioAlex** [comment]
Thanks a lot for your answer, @tevador! I was trying to compile the tests/ and having the same errors: "undefine reference to:". I had forgotten the static library that had been compiled "librandomx.a". Now it works!

**Comment by Dentordev** [comment]
I figured that you need two things for those who have **Windows** specifically **amd64** (Use the command `Cmake CMakeLists.txt` and some files based on your machine type will generate for you enter into **Visual Studio** in the newly formed RandomX.sln open Visual Studio under **Batch Build** and make randomx for X64 this will allow for cross compiling, the file will then generate a randomx.lib file for you). for compiling to python you need to compile everything using randomx.lib and you need a windows library named AdvAPI32.lib. This is because virtual_memory.cpp depends on it if your on win32, after that your good to go, I forgot to tell you, @tevador  thanks for helping me out. I hope my recent discovery will help people more easily figure out how to use your library.
