### ISSUE TITLE
Perfomance?

### ISSUE THREAD

**Issue by ANPersoNA** [tevador/RandomX#260]
How many clock cycle does a single hash take? (excluding the dataset generation)

**Comment by hyc** [comment]
42

**Comment by MainSilent** [comment]
Including all AES functions?!

**Comment by tevador** [comment]
That depends on the settings and the hardware used.

[Here](https://github.com/tevador/RandomX/blob/master/doc/design.md#c-randomx-runtime-distribution) are some runtime statistics from 2019, showing roughly 4 800 000 cycles per hash for AMD Zen 1. There have been some optimization since then.

**Comment by ANPersoNA** [comment]
Thank you for clarification, As the first answer I was wonder how the 256 instructions would finish in 42 cycle.

**Comment by hyc** [comment]
> As the first answer I was wonder how the 256 instructions would finish in 42 cycle.

It was a nonsense answer to a nonsense question. It not only varies by processor type, which you didn't specify in your question, but even within a specific CPU model the number of cycles for a given instruction is variable.

**Comment by ANPersoNA** [comment]
@hyc  Or you can save time to not answer at all.

**Comment by Gingeropolous** [comment]
but that would be boring
