### ISSUE TITLE
Can `spAddr0  + 16 * i` and `spAddr1 + 8 * i` be the same value?

### ISSUE THREAD

**Issue by ghost** [tevador/RandomX#263]
After running the program we save register r and f to scratchpad, How possible is it that the address for saving registers overlap?
For instance is it possible after saving register r to scratchpad, We get the same address for saving one of the register f values?

**Comment by SChernykh** [comment]
I would say add a check for this run the code to see. It probably can happen randomly. Note that "saving" registers means just XORing them back into scratchpad. What's really saved is the entropy produced by the current iteration of the loop.

**Comment by tevador** [comment]
The probability that the store locations for the integer and float registers overlap is 2<sup>-15</sup>.
