### ISSUE TITLE
Linking error on aarch64 (ARM64) architecture

### ISSUE THREAD

**Issue by jahway603** [tevador/RandomX#264]
Currently we are using RandomX in a production mainnet. Everything works fine on regular x86 architecture, but [we run into a linking error on aarch64 (ARM64) architecture](https://git.hush.is/hush/hush3/issues/202#issuecomment-4339).

Exactly what flags to cmake need to be given to make it cross-compile correctly for  aarch64 (ARM64) architecture?

**Comment by tevador** [comment]
I'm not familiar with the linker error you are getting.

AFAIK [Monero](https://github.com/monero-project/monero) is successfully cross-compiling RandomX for several platforms including aarch64, so you can have a look at the build config there.

**Comment by SChernykh** [comment]
Did you try googling your error? https://stackoverflow.com/questions/47948647/relocations-in-generic-elf-em-62-while-cross-compiling-from-linux-to-openwrt

**Comment by jahway603** [comment]
Thank you @tevador & @SChernykh both for your responses to this issue.

Yes, I have extensively searched for similar errors but didn't find anything that seemed to match exactly this error that also uses cmake. The linking error means that 2 different incompatible architectures are attempting to be linked together, that much is clear. Our code cross-compiled fine until we added randomx as a dependency, and we figured it would be best to reach out to you, the upstream, since other projects will likely run into the same issue. Originally our code used "cmake -DARCH=native .." to build randomx but we have also tried "cmake -DARCH=aarch64 .." . Since Monero uses cmake for the entire build system but our project uses make primarily (and only cmake for randomx) it's not quite as simple as "look at Monero".  We have read through https://github.com/tevador/RandomX/blob/master/CMakeLists.txt which is why we believed -DARCH=aarch64 would work, but it doesn't. There may be a bug. We are not asking you to look at our build system, we simply would like to know how to cross-compile randomx, by itself, from x86 to aarch64.

**Comment by jahway603** [comment]
Thank you @SChernykh & @tevador for your help. I was able to get RandomX working on aarch64 (ARM64) thanks to your suggestions. You are [both publicly thanked here](https://duke.hush.is/memos/5/) & I'm very excited to have this working for our Raspberry Pi and single board computer users.
