### ISSUE TITLE
Try to understand hashrate of epyc cpus

### ISSUE THREAD

**Issue by MXS2514** [tevador/RandomX#269]
After checking the RX benchmark of EPYC 7D12, it seems nearly same hashrate (23-25K) compared to other similar 32C64T CPUs, single slot, but only 4 RAM channels, others are 8 
So is randomx not optimized for 4+ RAM channels or 7D12 specific issue ?

Cpus compared: Epyc
7532 32C64T 9dies 256ML3
7452 32C64T 5dies 128ML3
7542 32C64T 5dies 128ML3
7d12 32C64T ?dies 128ML3

**Comment by SChernykh** [comment]
25 kh/s doesn't need 8 memory channels. Even dual channel systems, like Ryzen 9 7950X, can reach 25 kh/s with just two channels. It's just not a bottleneck at this hashrate.

**Comment by jindongjie** [comment]
> 25 kh/s doesn't need 8 memory channels. Even dual channel systems, like Ryzen 9 7950X, can reach 25 kh/s. It's just not a bottleneck at this hashrate. 8 channels start to really matter for hashrates above 50 kh/s.

How about 40kh/s ? i need to use 4 or even 8 memory channels? I already got a pair of DDR4 3200MHZ memory,I want to run algorithm under epyc CPU, i need buy more memory to reach 40kh/s?

**Comment by SChernykh** [comment]
You need 4 memory channels for 40 kh/s

**Comment by jindongjie** [comment]
> You need 4 memory channels for 40 kh/s

Big thanks!
