### ISSUE TITLE
Why fast mode is being used?

### ISSUE THREAD

**Issue by bl00mber** [tevador/RandomX#276]
Why fast mode is being used if the goal is to make the least amount of hashes?
Why light mode said to be not suitable for mining, if it does produce the same hash as fast mode?
I understand <ins>how</ins> fast mode used, that it is faster than light mode, and reasoning that it makes possible verification on systems with small memory, but not <ins>why</ins> it is needed if light mode does the same.

**Comment by tevador** [comment]
I'm not sure if this is a trolling attempt, but the goal of mining is to calculate as many hashes as possible, so obviously, miners want to use the *fast mode*. *Light mode* is for verification because it requires less memory.

**Comment by bl00mber** [comment]
@tevador where it is a trolling attempt? It is a perfectly valid question. Again, I _know_ how fast and light modes are used. I will say it another way: the goal is not to make the least amount of hashes, but to make PoW ASIC-resistant. "The goal of mining is to calculate as many hashes" - that is incorrect, the goal of mining is to validate proof of work. If the total number of hashes per second produced will decrease but total network complexity remain the same the PoW validation effect on network will be the same. Why fast mode cannot be restricted by default, if this PoW algorithm is CPU-hard, not memory-hard? What issues can happen if fast mode will be removed?

**Comment by SChernykh** [comment]
With current RandomX design, it's easier to remove "light mode" instead of fast mode, because fast mode is primary. Initialize the whole dataset using Argon2 hash, and that's it - light mode is not possible anymore.

Light mode was only added to make verification possible on low memory devices, and it was made deliberately slow and energy burning to discourage ASICs using it.

**Comment by tevador** [comment]
> this PoW algorithm is CPU-hard, not RAM-hard

So the whole question was misphrased. You are really asking why RandomX needs to be memory-hard.

CPUs have access to DRAM, so RandomX was designed to need DRAM (>2 GB) as explained in the [documentation](https://github.com/tevador/RandomX/blob/master/doc/design.md#14-memory-hardness). If the memory requirement was lowered to 256 MB, an ASIC could be built that doesn't need DRAM (it could use just on-chip memory).

The light mode is a secondary mode to allow hashes to be verified on devices with less than 2 GB of RAM (e.g. Raspberry Pi). The existence of the light mode makes no sense without the fast mode.

**Comment by bl00mber** [comment]
@tevador thanks for the response, I got that fast mode is primary and cannot be turned off, I see now that hypothetical mining using light mode on custom CPUs (it is probably should be a fully functional CPU) with integrated memory of 256 MB will yield 10x less hashrate than in fast mode, so manufacturer of light mode chips will have to spend 10x? more electricity to achieve the same hashrate.

**Comment by tevador** [comment]
> I see now that hypothetical mining using light mode on custom CPUs [...] with integrated memory of 256 MB will yield 10x less hashrate than in fast mode, so manufacturer of light mode chips will have to spend 10x? more electricity to achieve the same hashrate.

You can't make conclusions like this about custom hardware. The "light mode" ASIC is a completely different chip than the "fast mode" ASIC, so you can't say one is x-times faster than the other one like you can say about a CPU that can operate in both modes.

I recommend you to read the discussions in #11 and #31.
