### ISSUE TITLE
Comparison of verification time (CNv0, CN-R, RandomX, RandomX-light)

### ISSUE THREAD

**Issue by JustFranz** [tevador/RandomX#28]
Considering the ongoing discussions, I think a comparison between CNv-8, CN-R, RandomX and RandomX light block verification times could come in handy to clear up misconceptions and speed up the process. I don't know how to do CNv-8 and CN-R and compare them to the RandomX verification mode test.

Lock if deemed unnecessary.

**Comment by tevador** [comment]
I have posted the results here: https://github.com/monero-project/meta/issues/316#issuecomment-475651654

**Comment by tevador** [comment]
Reopening this for verification time related discussion since the linked monero issue is moving too quickly.
