### ISSUE TITLE
Error when compiling with clang

### ISSUE THREAD

**Issue by fuwa0529** [tevador/RandomX#29]
I tried to compile RandomX with clang by changing the CC and CXX variables in the makefile.

With clang-5, I got a compile error:
`src/asm/program_prologue_linux.inc:35:28: error: cannot use base register with variable reference movapd xmm13, xmmword ptr mantissaMask[rip]`

With clang-7, some linker error:
`obj/argon2_core.o: file not recognized: file format not recognized clang-7: error: linker command failed with exit code 1 (use -v to see invocation)`

gcc 7.4.0 can compile it with no problem.

Update:
I tried clang-6, got the same linker error as clang-7

**Comment by tevador** [comment]
I think someone tested with clang before on MacOS and had no issues compiling it.

The error from clang-7 probably means link time optimizations are not supported. Try to remove the `-flto` flag from all targets.

The error from clang-5 means this compiler has issues with rip-relative addressing. No way to fix this easily.

**Comment by fuwa0529** [comment]
> Try to remove the -flto flag from all targets.

Correct, clang-7 can build now.

**Comment by fuwa0529** [comment]
@tevador, should I close this?

**Comment by tevador** [comment]
Keep it open, we will fix the makefile for clang.

**Comment by tevador** [comment]
I have added a new build target for compilers that don't support link-time optimizations.

Use `make nolto`
