### ISSUE TITLE
Trying to compile RandomX on Sailfish OS (armv7hl, aarch64)

### ISSUE THREAD

**Issue by Cigydd** [tevador/RandomX#292]
Hello,

I'm trying to compile RandomX on Sailfish OS. It is a part of my aim to build the XMRig miner for my old Xperia X phone to not let it lie idle.

Trying on RandomX version 1.2.1 and the current development version (March 17th 2024).

- compiling directly on device
- GCC: 3.8.0
- GNU assembler (GNU Binutils) 2.32
  - assembler target: `armv7hl-meego-linux-gnueabi`
- `uname -a`: `Linux Sailfish 3.10.84 #1 SMP PREEMPT Mon Feb 13 15:53:09 UTC 2023 aarch64 GNU/Linux`

The `cmake -Dnative ..` part goes well.

But the `make` phase crashes with messages that come apparently from the assembler:

```
…
[ 73%] Building C object CMakeFiles/randomx.dir/src/jit_compiler_a64_static.S.o
/home/nemo/Installace/RandomX/src/jit_compiler_a64_static.S: Assembler messages:
/home/nemo/Installace/RandomX/src/jit_compiler_a64_static.S:112: Error: shift expression expected -- `sub sp,sp,192'
/home/nemo/Installace/RandomX/src/jit_compiler_a64_static.S:113: Error: bad instruction `stp x16,x17,[sp]'
/home/nemo/Installace/RandomX/src/jit_compiler_a64_static.S:114: Error: ARM register expected -- `str x19,[sp,16]'
/home/nemo/Installace/RandomX/src/jit_compiler_a64_static.S:115: Error: bad instruction `stp x20,x21,[sp,32]'
…
```

The whole `make` output is to be seen in a [gist](https://gist.github.com/Cigydd/b0ac5494af5f58af964617b2e9aee0b5).

I will gladly provide any additional info I can and am asked for.

**Comment by hyc** [comment]
armv7 is aarch32, not aarch64. You can't use that.

**Comment by Cigydd** [comment]
Hello @hyc , tried to specify several architectures, including `armv7`, `armv7hl`, `aarch32`, and (!) `x86_64`, and the result is basically the same all the time…
Here is something suspicious i see while running the cmake program. Is it benign?

```
[nemo@Sailfish build]$ cmake -DARCH=armv7hl ..
-- Setting default build type: Release
-- Performing Test _march=armv8_a+crypto_cxx
-- Performing Test _march=armv8_a+crypto_cxx - Success
-- Setting CXX flag -march=armv8-a+crypto
-- Performing Test _march=armv8_a+crypto_c
-- Performing Test _march=armv8_a+crypto_c - Success
-- Setting C flag -march=armv8-a+crypto
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nemo/Installace/RandomX/build
```

May it be that it tests something specific for the armv8 architecture?

**Comment by SChernykh** [comment]
You need to compile to armv8 (64-bit), otherwise it makes no sense to try mining - it will be less than 1 h/s hashrate. You also need to update GCC to at least GCC-7 to compile XMRig or RandomX.

**Comment by Cigydd** [comment]
The GCC>=7 condition is satisfied.
However, it seems that I have a 64bit/armv8 CPU & kernel but the compiler is for 32bit/armv7…
Yes, definitely. See a [question on the old Jolla Together site](https://together.jolla.com/question/207970/64-bit-platform/).
Please excuse me for my confusion. The Sony Xperia X device doesn't belong to the devices that got full 64bit support. The kernel is 64bit but the userspace is 32bit.
If I understand good, I can't compile for aarch64 on such a machine. Or I can compile but not run. Or am I wrong?
