### ISSUE TITLE
Crash on Apple Silicon

### ISSUE THREAD

**Issue by dr-bestore** [tevador/RandomX#293]
Hi guys, I'm encountering a crash when integrating randomx to a Swift project and using JIT flag to calculate hash on Apple Silicon device.

```c++
	template<class Allocator, bool softAes, bool secureJit>
	void CompiledVm<Allocator, softAes, secureJit>::execute() {
#ifdef __aarch64__
		memcpy(reg.f, config.eMask, sizeof(config.eMask));
#endif
		compiler.getProgramFunc()(reg, mem, scratchpad, RANDOMX_PROGRAM_ITERATIONS); // <- Thread 2: EXC_BAD_ACCESS (code=2, address=0x104374000)
	}
```

Does anyone has idea for this problem?

**Comment by SChernykh** [comment]
RandomX works on Apple silicon. Did you test `randomx-benchmark` from this repository, without any of your modifications? The error you get is caused by "executable" flag not set for the JIT code.

**Comment by dr-bestore** [comment]
Thanks for the reply!
Yes it works perfect. I checked the `compiler.code` which was set but seemed not working. btw I just linked the .a built from cmake&make without any modification, did I miss something for that?

**Comment by SChernykh** [comment]
You probably don't set SECURE_JIT flag when you set up RandomX VM, it's mandatory for Apple silicon.
