### ISSUE TITLE
mx register: inconsistency between specification and reference implementation - alignment

### ISSUE THREAD

**Issue by HayashidaMakoto** [tevador/RandomX#296]
[The specification](https://github.com/tevador/RandomX/blob/068f65339ab273023f56aee84de0b5ea8684ba8d/doc/specs.md#43-registers) states:
> ma and mx are the memory registers. Both are 32 bits wide. ma contains the memory address of the next Dataset read and mx contains the address of the next Dataset prefetch. The values of **ma and mx registers are always aligned to be a multiple of 64.**

However, the implementation does not perform the alignment, see [this line, commit 068f65339ab273023f56aee84de0b5ea8684ba8d](https://github.com/tevador/RandomX/blob/068f65339ab273023f56aee84de0b5ea8684ba8d/src/virtual_machine.cpp#L82). In fact, when printing the first value generated by the tests, we get: `0x8a8a6230`, which is not a multiple of 64.

We haven't gone through the documentation/code enough to decide if it is important.

Hayashida.

**Comment by tevador** [comment]
The alignment of `mx` is done for example here:

https://github.com/tevador/RandomX/blob/102f8acf90a7649ada410de5499a7ec62e49e1da/src/vm_interpreted.cpp#L87

You are *technically* correct that the C++ variable representing `mx` is not *always* correctly aligned, but it still simulates the virtual machine correctly (according to the specification) by aligning the value just before it's used to perform a read.

**Comment by HayashidaMakoto** [comment]
Ah, thank you for pointing this in the interpreter. Sorry for not having had a deeper look before opening the issue.

Closing.
