### ISSUE TITLE
why not add avx, avx2 and possibly avx512 use to randomx?

### ISSUE THREAD

**Issue by sfhdfshdfh** [tevador/RandomX#298]
i think one of the reasons why randomX was created was trying to implement asic resistance and possibly botnet resistance. i was surprised when i found out avx2 is not used not even avx while these are 10yo instructions and most cpus support these. u only have the oldschool 2080mb data set and another smaller one in ram. assuming it could stop malicious actors illegally accessing computers of others.
it's 2024 and randomX hasnt improved. 
if you implement avx, avx2 in slow mode and possibly avx512 in fast mode this will drop lots of compromised old servers/pcs around the world and the antminer x5. i believe monero team wanted to do some tweaks on their algo this time of the year to slightly improve cpu hashrates and weaken x5. i got a number of ryzens i should be able to mine xmr. those who have bought avx512-capable cpus should get a higher hashrate than non avx512 cpus.

**Comment by SChernykh** [comment]
Most CPUs in the world are ARM-based and those don't have AVX. RandomX is the minimal common denominator for x86, ARM and RISC-V CPUs.

**Comment by sfhdfshdfh** [comment]
well then let them use the slow mode without any avx. but add avx2 n maybe 512 to fast mode so that most botnets lose half of their hashrates. also those with modern cpus should get higher hashrate to compensate the loss they experience because of botnets.

**Comment by hyc** [comment]
The instruction set must be identical across all platforms. Your request is idiotic.
