### ISSUE TITLE
RandomX Argon2 usage

### ISSUE THREAD

**Issue by l1mey112** [tevador/RandomX#304]
As a small background, I am working on a JavaScript library to compute and mine RandomX hashes in a browser context by JITing WASM/JS, using validation mode to get around the memory requirement and using error free transforms to implement floating point rounding to get around the `CFROUND` instruction performantly.

I took a look at the spec for Argon2d hash function used to generate the cache, and I couldn't find information on a "memory fill" operation. I took a look at the source and could ascertain what it did exactly (except fill memory). I implement the hash functions as small loadable modules, and have been using [argon2.c](https://github.com/Daninet/hash-wasm/blob/master/src/argon2.c) as a base.

Can you provide me an understanding of what the innards of the "memory fill" function does, and how could I adjust a reference implementation of Argon2 to do this?

**Comment by SChernykh** [comment]
I think this function is here: https://github.com/tevador/RandomX/blob/master/src/argon2_ref.c
