### ISSUE TITLE
License Compatibility

### ISSUE THREAD

**Issue by iamamyth** [tevador/RandomX#33]
It would seem this code is presently licensed under GPLv3, which would require releasing any project including RandomX, such as Monero, under a GPLv3 license.

**Comment by tevador** [comment]
It should not be an issue. The only code dependency of RandomX is Argon2, which is licensed under CC0. The rest is my code that can be relicensed to be compatible with the Monero license.

**Comment by iamamyth** [comment]
The problem would be two-fold:

1. You can't re-license external contributions under a more permissive license. Arguably [this commit] (https://github.com/tevador/RandomX/commit/8ef8224270f529d60acf23213ceab5dd656b83e1#diff-25d902c24283ab8cfbac54dfa101ad31) creates re-licensing issues, but any others not authored by you certainly would.

2. Other non-GPLv3 projects which aren't Monero cannot proceed with RandomX at the moment, which stifles real-world deployment and testing. I understand that Wownero was considering using it, but, presently, they would have to re-license their whole project as GPLv3 to do so, which seems like a dead end.

Obviously you are free to license your work as you see fit, but there's a danger that the software becomes wholly incompatible with Monero the longer it continues with this GPLv3 license, which would be a shame.

**Comment by tevador** [comment]
1. The first linked commit added code that has since been removed from the codebase.

2. If @antanst gives his permission, I will relicense under the 3-clause BSD license. Would that be sufficient in your opinion?

**Comment by iamamyth** [comment]
> 2. If @antanst gives his permission, I will relicense under the 3-clause BSD license. Would that be sufficient in your opinion?

As I understand it, so long as all authors (in this case, you and antanst) consent to the new license, it should be sufficient.

**Comment by antanst** [comment]
@iamamyth Good point
@tevador Of course you have it, thank you for asking.

**Comment by tevador** [comment]
OK, thanks. For now I'm leaving it under GPLv3. I will revisit this issue after 30th April, which is the planned RandomX code freeze date.

**Comment by kayabaNerve** [comment]
So it's time to revisit this, correct?

**Comment by wowario** [comment]
If it would help thwart proprietary ASIC firmware development, I see no issue with relicensing Wownero as GPLv3 and reverting back to 3-clause BSD when/if Monero switches to RandomX. It is possible to take [BSD licensed code and, with or without making modifications, redistribute it adding GPL's requirements](https://law.stackexchange.com/a/4194/10464). @jwinterm what do you think?

**Comment by jwinterm** [comment]
There seems to be some dispute in that thread that you linked, @wowario, and IANAL, but sure I don't see any problem with trying it out on Wownero.

**Comment by kayabaNerve** [comment]
I'm a coin developer myself, and like BTC (despite not being a fork), I license my work under the MIT license. That's why my concern is with RandomX's license.

**Comment by iamamyth** [comment]
Although I am not a lawyer and nothing I say is or should be construed as legal advice, it's hard to see how "GPLv3 now, 3-clause BSD later" would seriously alter the course of ASIC development, as ASICs would presumably only ship once Monero had integrated the code, and Monero is licensed under the 3-clause BSD license. During ASIC development (and even, for that matter, first use), the manufacturer wouldn't be sharing the specs or devices with any third parties, meaning no one else would be entitled to them under GPL, and, once Monero ships, the license would be 3-clause BSD, so end-users would not be entitled to anything. Additionally, most ASICs are manufactured in China, which has a long history of ignoring IP laws, so, realistically, a GPLv3 license (either temporary, or indefinite) would seem to primarily have the effect of crowding out manufacturers who abide by IP laws, granting an advantage to those who do not, and thereby increasing manufacturing monopolization.

**Comment by kayabaNerve** [comment]
The source code being under the GPL license doesn't mean the algorithm itself is. To protect the algorithm, you'd need a patent. Anyone can reimplement RandomX and license their implementation however they want, as long as they didn't borrow code.

**Comment by hyc** [comment]
Definitely a valid point. Even so, it's more likely that someone will start from the existing code than start from a clean room implementation of the spec.

**Comment by kayabaNerve** [comment]
ASIC manufacturers are creating an implantation in hardware, with some custom software. My comment was this doesn't matter at all for ASIC development.

**Comment by thinkpol2** [comment]
> 2. If @antanst gives his permission, I will relicense under the 3-clause BSD license. Would that be sufficient in your opinion?

With the 1.x release, is this no longer true @tevador?

**Comment by kayabaNerve** [comment]
The original comment by @tevador was April 30th; I think the freeze actually happened May 1st.  That said, since he has has yet to comment, or apply a BSD-3 License... (again, even LGPL which has a linking safe harbor would be great).

**Comment by tevador** [comment]
RandomX is now licensed under the 3-clause BSD license.
