### ISSUE TITLE
RandomX Emergency Failsafe: Force ASICs to be useful with Random Lossless Data Compression Algorithms

### ISSUE THREAD

**Issue by MoneroChan** [tevador/RandomX#36]
Hi @tevador,  In the event RandomX Fails to deter ASICs, 
I've got an idea to extend the RandomX lifespan even further.

Emergency Failsafe / Backup proposal:

- Integrate "Random Lossless Data Compression Algorithms" into the RandomX Program sequence, forcing the creation of extremely useful and commoditized 'Lossless Data Compression ASICs'.

How This Might Work:

- If RandomX is declared as "Failed", and the devs choose to go ASIC friendly, 
- Lossless Data compression algorithms can be integrated into the RandomX VM program sequence (various Lossless Data Compression Algorithms to choose from).
- That will force ASIC manufacturers to make an Lossless data compression ASIC that can work with Random Data (coming from RandomX's VM Randomization engine)
- Because these ASICS can handle random data, Data can be re-routed through the ASIC for on the fly data compression in Real world applications outside mining.
- ASICs can't cheat as the Dataset is Randomly generated based on RandomX's engine.

**There would be Huge Benefits for the Entire computing industry**
- If ASICs can do "Random Lossless data compression" on the fly, it would be "Incredibly useful" for the entire computer industry.
- Lossless Data compression ASICs would be decentralized and heavily commoditized on every computer and phone on the planet, built into all computers, SSDs, HDDs, Phones, Servers, Data centres, TVs, Internet routers to reduce Data storange and bandwidth by doing lossless data compression on the fly in real time, Reducing Internet bandwidth, Youtube videos download, File sharing, SSD/HDD storage costs etc, 

I'm thinking this would help the world far more than SHA3.

Could this be done with RandomX's Randomization VM engine?

Thanks,

**Comment by tevador** [comment]
1. Random data cannot be losslessly compressed by definition. Most compression algorithms actually output more data than the input size if the input is random.
2. The output of RandomX is not 'random' in the sense of [Kolmogorov complexity](https://en.wikipedia.org/wiki/Kolmogorov_complexity) because it's generated from a 512-bit seed. Therefore the output of every RandomX program can be 'compressed' into 512 bits + the size of the RandomX binary.

**Comment by MoneroChan** [comment]
Yes that's true, the compression part's only useful outside random environments.

I guess even if RandomX uses the entire blockchain as a random data source, it would be used up to quickly too.

oh well...guess i'll have to think of something better.

Thanks Tevador,

**Comment by MoneroChan** [comment]
Yes that's true, the compression part's only useful outside random environments.

I guess even if RandomX uses the entire blockchain as a random data source, it would be used up to quickly too.

oh well...guess i'll have to think of something better.

Thanks Tevador,
