### ISSUE TITLE
Big endian CPU support

### ISSUE THREAD

**Issue by nioroso-x3** [tevador/RandomX#37]
Will you finish fixing the big endian problems? 
I want to start porting the JIT to ppc64le, and ppc64be too if you fix it, so I'd like to know if RandomX will stay little endian only.

**Comment by tevador** [comment]
Big endian still gives wrong results.

Could you provide me access to a BE machine for debugging? All I need is git and a reasonably recent version of gcc.

**Comment by nioroso-x3** [comment]
Paste a public ssh key, I'll give you access to my G5 with gentoo, it has gcc-6.4 and clang-7
You will be able to access it at tevador@nerv-la.ddns.net -p 223

**Comment by tevador** [comment]
```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAuZ865rvyyfRhgVErdTymU4UJKi+F8GYQkhvQ4o2Ba16ElDuOpvcDmssv3+dreZ4oO3D6fkXgguZZlnAZ/ooywfM/WQhDvz8DB1R5Zp28q4r3/+vBCFl70fFoZhJePNz1MikTz1hwEcwk1Vc/2H5CLfSlOEjGCSpKrJBfstLWiyvpkEa1YbSWyH4aG3oRLlLg4vZqU03rKByAjQP9eirlRu959C9/r/9iKRRlwsIYFlZsMGB5CuN6ejvO7EeCbg2Z+jfqANR9oaL1Mwe3AXe9aVpZWLUYBdOi6mXzGN554Fc+jQZhF6R9WuGv+ko/5QDxrCyxzsabfJrN2P/WuREi/w== tevador@laptop
```

Thanks.

**Comment by nioroso-x3** [comment]
Ok, you should be able to login now.

**Comment by tevador** [comment]
I have fixed some small bugs in the interpreter and BE now gives the corect results.

Tested on current dev branch 018c1a5222e19567b501f9325d50c126de171163

Light mode:
```
tevador@powermagi ~/RandomX $ bin/benchmark --verify --softAes
RandomX benchmark
 - light memory mode (256 MiB)
 - interpreted mode
 - software AES mode
 - small pages mode
Initializing ...
Memory initialized in 4.94757 s
Initializing 1 virtual machine(s) ...
Running benchmark (1000 nonces) ...
Calculated result: b69741719152625854031c2337ceae68c3030f2b9581a73acebaa69fc9b555fc
Reference result:  b69741719152625854031c2337ceae68c3030f2b9581a73acebaa69fc9b555fc
Performance: 2255.02 ms per hash
```
Full mode:
```
tevador@powermagi ~/RandomX $ bin/benchmark --mine --init 4 --softAes
RandomX benchmark
 - full memory mode (2 GiB)
 - interpreted mode
 - software AES mode
 - small pages mode
Initializing (4 threads) ...
Memory initialized in 541.689 s
Initializing 1 virtual machine(s) ...
Running benchmark (1000 nonces) ...
Calculated result: b69741719152625854031c2337ceae68c3030f2b9581a73acebaa69fc9b555fc
Reference result:  b69741719152625854031c2337ceae68c3030f2b9581a73acebaa69fc9b555fc
Performance: 9.29581 hashes per second
```

I'm still planning one slight change to the specification this weekend and I will use your machine to validate big endian compatibility.

After 1st May, the RandomX specification will be frozen, so you can start implementing the JIT compilers.

**Comment by nioroso-x3** [comment]
I increased the amount of huge pages, mining mode should work now.

**Comment by tevador** [comment]
Thanks. Interpreted mining mode now does about 42 H/s with 4 threads.

The interpreter code is now frozen and is not expected to change unless a bug is found. We still reserve the right for changes in the [configuration](https://github.com/tevador/RandomX/blob/dev/src/configuration.h) and for code refactoring.

**Comment by nioroso-x3** [comment]
Nice, when will you push the changes from dev to master?

**Comment by tevador** [comment]
The documentation has not been updated yet, so I cannot merge at the moment.

Also I'm expecting to push a bugfix later today (related to the CBRANCH instruction).

I think I should be able to merge dev into master before Sunday.

**Comment by tevador** [comment]
Merged into master. Thanks for access to your machine.

**Comment by tevador** [comment]
Refer to this commit to see how to integrate JIT compiler support: 3dd21ea93dd7b10e70fb4d9f1f9725fbb001f6e0

Your JIT compiler class signature must match the public methods of the `JitCompilerFallback` class.
