### ISSUE TITLE
largePages issue on Dell R820 4x E5-4640 Xeon / ubuntu v16.04

### ISSUE THREAD

**Issue by NicholasLMoser5** [tevador/RandomX#39]
Hello,  
Anytime I set the --largepages option, i get an error.  am I making a mistake?  thanks for your time and effort.
command to set hugepages:  sysctl -w vm.nr_hugepages=128

root@DELL-R820-E5-03:~/randomx/RandomX/bin# gcc-7 -v
Using built-in specs.
COLLECT_GCC=gcc-7
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.1.0-10ubuntu1~16.04.york0' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.1.0 (Ubuntu 7.1.0-10ubuntu1~16.04.york0)

root@DELL-R820-E5-03:~/randomx/RandomX/bin# ./benchmark --mine --largePages
RandomX benchmark
 - full memory mode (2080 MiB)
 - interpreted mode
 - hardware AES mode
 - large pages mode
Initializing (1 thread) ...
ERROR: Dataset allocation failed

root@DELL-R820-E5-03:~/randomx/RandomX/bin# ./benchmark --mine --jit
RandomX benchmark
 - full memory mode (2080 MiB)
 - JIT compiled mode
 - hardware AES mode
 - small pages mode
Initializing (1 thread) ...
Memory initialized in 28.6958 s
Initializing 1 virtual machine(s) ...
Running benchmark (1000 nonces) ...
Calculated result: 57eb2044a20f8d6d6ef75eba6d879af5b9850556cb5a7cb459d7b091bd8d63aa
Reference result:  57eb2044a20f8d6d6ef75eba6d879af5b9850556cb5a7cb459d7b091bd8d63aa
Performance: 396.985 hashes per second

root@DELL-R820-E5-03:~/randomx/RandomX/bin# ./benchmark --mine --jit --threads 40 --init 64
RandomX benchmark
 - full memory mode (2080 MiB)
 - JIT compiled mode
 - hardware AES mode
 - small pages mode
Initializing (64 threads) ...
Memory initialized in 3.993 s
Initializing 40 virtual machine(s) ...
Running benchmark (1000 nonces) ...
Calculated result: 57eb2044a20f8d6d6ef75eba6d879af5b9850556cb5a7cb459d7b091bd8d63aa
Reference result:  57eb2044a20f8d6d6ef75eba6d879af5b9850556cb5a7cb459d7b091bd8d63aa
Performance: 2440.3 hashes per second

root@DELL-R820-E5-03:~/randomx/RandomX/bin# ./benchmark --mine --jit --threads 40 --init 64 --nonces 1000000
RandomX benchmark
 - full memory mode (2080 MiB)
 - JIT compiled mode
 - hardware AES mode
 - small pages mode
Initializing (64 threads) ...
Memory initialized in 4.16322 s
Initializing 40 virtual machine(s) ...
Running benchmark (1000000 nonces) ...
Calculated result: 70236ad5491adcfbb5d3136601b8dcf8859ab7f061c35b5bff58e7b04da32de0
Performance: 6118.03 hashes per second

root@DELL-R820-E5-03:~/randomx/RandomX/bin# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             4
NUMA node(s):          4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Xeon(R) CPU E5-4640 0 @ 2.40GHz
Stepping:              7
CPU MHz:               1388.062
CPU max MHz:           2800.0000
CPU min MHz:           1200.0000
BogoMIPS:              4803.03
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0,4,8,12,16,20,24,28,32,36,40,44,48,52,56,60
NUMA node1 CPU(s):     1,5,9,13,17,21,25,29,33,37,41,45,49,53,57,61
NUMA node2 CPU(s):     2,6,10,14,18,22,26,30,34,38,42,46,50,54,58,62
NUMA node3 CPU(s):     3,7,11,15,19,23,27,31,35,39,43,47,51,55,59,63
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts

root@DELL-R820-E5-03:~/randomx/RandomX/bin# ./benchmark --mine --jit --largePages --threads 40 --init 64 --nonces 1000000
RandomX benchmark
 - full memory mode (2080 MiB)
 - JIT compiled mode
 - hardware AES mode
 - large pages mode
Initializing (64 threads) ...
ERROR: Dataset allocation failed

root@DELL-R820-E5-03:~/randomx/RandomX/bin# uname -a
Linux DELL-R820-E5-03 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@DELL-R820-E5-03:~/randomx/RandomX/bin# free -m
              total        used        free      shared  buff/cache   available
Mem:          15971         444       14863           9         663       15006
Swap:         16318           0       16318

root@DELL-R820-E5-03:~/randomx/RandomX/bin# cat /proc/meminfo
MemTotal:       16354676 kB
MemFree:        15219988 kB
MemAvailable:   15367052 kB
Buffers:           36828 kB
Cached:           481796 kB
SwapCached:            0 kB
Active:           417548 kB
Inactive:         140912 kB
Active(anon):      42720 kB
Inactive(anon):     9168 kB
Active(file):     374828 kB
Inactive(file):   131744 kB
Unevictable:        3652 kB
Mlocked:            3652 kB
SwapTotal:      16710652 kB
SwapFree:       16710652 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:         43520 kB
Mapped:            33532 kB
Shmem:              9632 kB
Slab:             160804 kB
SReclaimable:      62612 kB
SUnreclaim:        98192 kB
KernelStack:       10704 kB
PageTables:         2940 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    24756916 kB
Committed_AS:     481120 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:     14336 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:     128
HugePages_Free:      128
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      134252 kB
DirectMap2M:     6092800 kB
DirectMap1G:    12582912 kB
root@DELL-R820-E5-03:~/randomx/RandomX/bin#

**Comment by tevador** [comment]
> HugePages_Total: 128
> Hugepagesize: 2048 kB

Your system doesn't have enough hugepages.  Since each huge page is 2 MiB, you need about ~1250 hugepages to fit the cache, dataset and all scratchpads.

Run
```
sudo sysctl -w vm.nr_hugepages=1250
```
Then rerun the test with the `--largePages` option.

**Comment by NicholasLMoser5** [comment]
Thank you, working now!!
