### ISSUE TITLE
ARM Rounding

### ISSUE THREAD

**Issue by tevador** [tevador/RandomX#4]
I've been doing some portability tests and found out that the ARM instruction for conversion between integer and floating point (`VCVT`) uses a hardcoded rounding mode rather than the rounding mode that is set in the FPSCR register. [Reference on page 4-22.](http://infocenter.arm.com/help/topic/com.arm.doc.dui0489e/DUI0489E_arm_assembler_reference.pdf).

This causes a discrepancy between the results from x86 and ARM (confirmed with Raspberry Pi 3).

Possible solutions:
1. Keep the current integer to float conversion. This would force ARM to fix the rounding in software. Possible high impact on performance for ARM.
2. Perform the conversion always in the default rounding mode. This would force x86 to switch rounding modes between conversion and the actual operation (addition, subtraction etc.). Possible high impact on performance for x86.
3. Remove the FROUND instruction altogether and only use the default rounding mode round-to-nearest. This would have no impact on performance but would decrease ASIC resistance.
4. Remove the conversion step from FPU instructions and treat the arguments directly as floating point values. Possible issues with NaN, inifinity and denormal values. Unknown impact on performance and randomness of the results.

Not sure which solution is the best. Thoughts?

**Comment by SChernykh** [comment]
> Integer or fixed-point to floating-point conversions use round to nearest

This one is worse, it limits us to only one rounding mode. But we can limit integers to the range -2^24 <= N <= 2^24 before conversion and rounding will never happen.

**Comment by SChernykh** [comment]
There are also `_mm_cvt_roundi32_ss` and `_mm_cvt_roundss_i32` instructions which allow to set rounding mode, but it's AVX-512.

**Comment by hyc** [comment]
That's only the vector form of the instruction. The scalar instruction can use the specified rounding mode.
(Page 4-81)

**Comment by tevador** [comment]
@hyc
> VCVT{R}{cond}.type.F64 Sd, Dm
> VCVT{R}{cond}.type.F32 Sd, Sm
> VCVT{cond}.F64.type Dd, Sm
> VCVT{cond}.F32.type Sd, Sm
>
> The first two forms of this instruction convert from floating-point to integer.
> The third and fourth forms convert from integer to floating-point.

As far as I can see, there is no option to set the rounding mode for integer -> float conversion.

@SChernykh 
I will test limiting the integer range to fit into mantissa without rounding. AVX-512 is supported only by a handful of CPUs, so it's not a usable option.

**Comment by hyc** [comment]
@SChernykh limiting the range to avoid rounding sounds best.

**Comment by tevador** [comment]
So it seems to be solved by limiting integers to 52/53 bits. All test cases are now passed both on x86 and ARM.

I'm using the following functions to convert an integer to double:

```c++
static inline double convertToDouble(int64_t x) {
	return (double)(x & -2048L);
}

static inline double absConvertToDouble(int64_t x) {
	return (double)(x & 9223372036854773760L);
}
```
`convertToDouble` keeps only the high-order 52 bits plus sign. `absConvertToDouble` keeps only the high-order 52 bits and clears the sign (this is used for square root). Performance impact should be limited.

Using the high-order bits has the additional benefit that denormal results are now impossible since the lowest non-zero value is 2048, which is normal even when divided by DBL_MAX.
