### ISSUE TITLE
Can't start benchmark

### ISSUE THREAD

**Issue by Helmeboi** [tevador/RandomX#49]
At first I tried to manually compile it using the code below:

```
sudo apt-get update
sudo apt-get install build-essentials
git clone https://github.com/tevador/RandomX.git
cd RandomX
cmake .
make
cd bin
./benchmark
```

This has resulted in
> ERROR: Dataset allocation failed
Then trying it a second time resulted in
> ERROR: Cache allocation failed

So I tried to install the latest precompiled release which gave me this
> ./benchmark: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./benchmark)

And I fixed that using `sudo apt-get install --only-upgrade libstdc++6` Then it started giving me
> ERROR: Dataset allocation failed

again.

Not sure what's going on here.

**Comment by tevador** [comment]
Can you post the full command line you are using to run the benchmark?

'Dataset allocation failed' can mean one of two things:

* You are using the `--largePages` option, but large page support is not enabled in your system.
* You have less than ~2.5 GiB of free virtual memory.

**Comment by Helmeboi** [comment]
The problem was with the virtual memory, I completely messed up the vram assignment on the vm.
Thanks, keep it up!
