### ISSUE TITLE
cmake: /wmmintrin.h:61:1: error: inlining failed in call to always_inline

### ISSUE THREAD

**Issue by moneroexamples** [tevador/RandomX#54]
Current CMakeLists.txt has some issues, which make randomx difficult to use as a module in other project. 

```
n file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:43:0,
                 from /root/RandomX/src/intrin_portable.h:89,
                 from /root/RandomX/src/soft_aes.h:32,
                 from /root/RandomX/src/aes_hash.cpp:29:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h: In function 'rx_vec_i128 aesenc(rx_vec_i128, rx_vec_i128) [with bool soft = false; rx_vec_i128 = __vector(2) long long int]':
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:61:1: error: inlining failed in call to always_inline '__m128i _mm_aesenc_si128(__m128i, __m128i)': target specific option mismatch
 _mm_aesenc_si128 (__m128i __X, __m128i __Y)
 ^
In file included from /root/RandomX/src/aes_hash.cpp:29:0:
/root/RandomX/src/soft_aes.h:40:65: error: called from here
  return soft ? soft_aesenc(in, key) : rx_aesenc_vec_i128(in, key);
```

The error is due to the fact that `ARCH_ID` is not set as this variable is specific to monero. Maybe as a fallback, if not  explicitly set by the parent project  it could be set to `${CMAKE_HOST_SYSTEM_PROCESSOR}`?

Also there is no `cmake_minimum_required` provided which results in warnings when build randomx using cmake. 

Possible updated version of the CMakeLists.txt is here: 
https://github.com/moneroexamples/RandomX/blob/update_cmake/CMakeLists.txt

The `cmake_minimum_required` provided is same as for the monero.

With the changes, randomx can also be build using cmake:

```
cd RandomX
mkdir build && cd build
cmake ..
make 
```

**Comment by tevador** [comment]
Fixed in PR #56
