### ISSUE TITLE
"Operations that preserve entropy" 🤔

### ISSUE THREAD

**Issue by veorq** [tevador/RandomX#61]
*Issue reported in the context of Kudelski Security's audit*

The design document states:

> RandomX uses all primitive integer operations that preserve entropy: addition (IADD_RS, IADD_M), subtraction (ISUB_R, ISUB_M, INEG_R), multiplication (IMUL_R, IMUL_M, IMULH_R, IMULH_M, ISMULH_R, ISMULH_M, IMUL_RCP), exclusive or (IXOR_R, IXOR_M) and rotation (IROR_R, IROL_R).

Here "preserve entropy" is probably meant as "is invertible if one of the operands is fixed". However this is not the case for multiplication. I suggest to clarify that part.

**Comment by tevador** [comment]
It was not meant in the literal sense of being invertible, but simply preserving the output entropy close to 64 bits.

In terms of Shanon's entropy, multiplication reduces the output randomness by much less than 1 bit. Other operations like bitwise AND, OR and logical shift reduce entropy significantly.

I will rephrase the statement.

**Comment by SChernykh** [comment]
> In terms of Shanon's entropy, multiplication reduces the output randomness by much less than 1 bit.

I actually got curious and did a quick test. Multiplication result (low 16 bits) of two random 16-bit numbers (each has 16 bits of entropy) has ~15.7111 bits of entropy by Shannon's definition. So < 0.3 bits of entropy is lost in each multiplication. High 16 bits of multiplication result even have ~15.9995 bits of entropy, so almost nothing is lost in IMUL_HI, ISMUL_HI instructions.

Testing program is here: http://cpp.sh/5olo4

**Comment by veorq** [comment]
Yeah it's more about the worst case (x*0) than the average case.

**Comment by tevador** [comment]
The highest chance of multiplication by 0 is with the `IMUL_R` instruction if `dst == src` and `imm32 == 0`. The chance of this is 1 in 32 billion. The other cases have a much lower chance on the order of 2<sup>-64</sup>.
