### ISSUE TITLE
Potential division by zero in random_reciprocal()

### ISSUE THREAD

**Issue by veorq** [tevador/RandomX#63]
*Issue reported in the context of Kudelski Security's audit*

Division by zero here if `divisor` is zero:

https://github.com/tevador/RandomX/blob/1276d67d2f594ea4a8e9cde28253b1a74769aeb9/src/reciprocal.c#L46-L50

I suggest to check for `divisor == zero` and return an appropriate value.

**Comment by tevador** [comment]
It is never called with zero input:

https://github.com/tevador/RandomX/blob/bc2aae0f61a5b15472753e0dda399410fd450a4f/src/vm_interpreted.cpp#L447-L454

https://github.com/tevador/RandomX/blob/8a5ead5ce3e3671861dc68ab675fe151d07d215d/src/jit_compiler_x86.cpp#L583-L589

Both check for zero by calling the `isPowerOf2` function, which actually returns true for 0 and powers of 2.

SuperscalarHash likewise doesn't permit 0 input: 

https://github.com/tevador/RandomX/blob/2706a8b7533860900b33ac69899471e5127a4872/src/superscalar.cpp#L482-L484

**Comment by veorq** [comment]
Right had noticed mitigations against NaN cases in the specs, so that's a non-issue. Worth adding an assert for unit tests maybe?

**Comment by tevador** [comment]
Added an assert in #88.
