### ISSUE TITLE
Unseen compiler quirks, UNPORTABLE to any other language

### ISSUE THREAD

**Issue by graplea90** [tevador/RandomX#72]
**I have been studying the design. However during testing, some compiler quirks have popped up. My suggestion is to stop deploying until another implementation ( in any other programming language) is completed and results verified.**

```

#include <stdio.h>
#include <stdlib.h>

int main() {


    // if blake generator is given this key,  "RandomX example key" and  keylen is set to strlen(key) and  trace is set to on
    // we see the following compiler play in action
    // please note strlen,  as api-example1.c uses sizeof(key), which unknowingly/knowingly includes  null char as part of key
  
    // the first data that is emitted by the generator is as follows, under the test condition

    // (a) cf77cada % 8 = 2  used to select source register for imul_r,  and register 2 is selected
    // (b) 61005a17 % 7 = 4  used to selected dest register ,   register 5 is selected, since 2 is already selected

    // (c) ece5893b % 7 = 4  used to select source register,  probably compiler play should be 6 , HOW ??  , register 4 is selected
    // (d) e306a5bb % 6 = 3  used to select destination register , register  3 is selected

 
    // as u can see, case (c) will generate 4 if sign bit if ignored, otherwise in all cases it 
    printf("\nassumming code processes as signed int\n\n");
    int input = 0xcf77cada;
    printf("(a) 0x%08X %% 8  %2d (signed) %2d (unsigned)  (should be 2)\n",input, input % 8, abs(input)%8);
    
    input = 0x61005a17;
    printf("(b) 0x%08X %% 7  %2d (signed) %2d (unsigned) (should be 4)\n",input, input % 7, abs(input)%7);

    input = 0xece5893b;
    printf("(c) 0x%08X %% 7  %2d (signed) %2d (unsigned) (should be 6)\n",input, input % 7, abs(input)%7);

    input = 0xe306a5bb;
    printf("(d) 0x%08X %% 6  %2d (signed) %2d (unsigned) (should be 3)\n", input,input % 6, abs(input)%6);


    {
    printf("\nassumming code processes as unsigned int, 3 rows match, however case c trigger wrong  \n\n");
    unsigned int input = 0xcf77cada;
    printf("(a) 0x%08X %% 8  %2d (signed) %2d (unsigned)  (should be 2)\n",input, input % 8, (input)%8);
    
    input = 0x61005a17;
    printf("(b) 0x%08X %% 7  %2d (signed) %2d (unsigned) (should be 4)\n",input, input % 7, (input)%7);

    input = 0xece5893b;
    printf("(c) 0x%08X %% 7  %2d (signed) %2d (unsigned) (should be 6)  RandomX FAILED but code prints index is 4 how (not possible until top bit is ignored (maybe compiler quirk) \n",input, input % 7, (input)%7);

    input = 0xe306a5bb;
    printf("(d) 0x%08X %% 6  %2d (signed) %2d (unsigned) (should be 3)\n", input,input % 6, (input)%6);
    }

}
```

Save the above program and run as below
g++ proof_design_or_compiler_issue.cpp ; ./a.out

Case 'C' occurs in RandomX which can be triggered as follows
Replace api-example with below code

```#include "../randomx.h"
#include <stdio.h>
#include <string.h>

int main() {
	const char myKey[] = "RandomX example key";
	const char myInput[] = "RandomX example input";
	char hash[RANDOMX_HASH_SIZE];

	randomx_cache *myCache = randomx_alloc_cache(RANDOMX_FLAG_DEFAULT);
	randomx_init_cache(myCache, &myKey, strlen( myKey));
	randomx_vm *myMachine = randomx_create_vm(RANDOMX_FLAG_DEFAULT, myCache, NULL);

	randomx_calculate_hash(myMachine, &myInput, sizeof myInput, hash);

	randomx_destroy_vm(myMachine);
	randomx_release_cache(myCache);

	for (unsigned i = 0; i < RANDOMX_HASH_SIZE; ++i)
		printf("%02x", hash[i] & 0xff);

	printf("\n");

	return 0;
}
```

also, replace this function for debug output
https://github.com/tevador/RandomX/blob/8ff1bf027abf351f7763e52b55f018b69e0e77f0/src/superscalar.cpp#L331

```static bool selectRegister(std::vector<int>& availableRegisters, Blake2Generator& gen, int& reg) {
		int index;
		if (availableRegisters.size() == 0)
			return false;

		if (availableRegisters.size() > 1) {
            int t = gen.getInt32();
            printf("getInt32 %d  len %d   %x \n", t,availableRegisters.size(),t );
			index = t % availableRegisters.size();
		}
		else {
			index = 0;
		}
		printf("reg index %d\n",index);
		reg = availableRegisters[index];
		return true;
	}
```

Now run the example which shows compiler quirk in action.
provided code show what should have been the output.
the first superscale program generated and second instruction from 4444 ( which is first decode buffer) print statements will confirm our findings.
my g++ version g++ (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0  
arch is 64 bits intel cpu.

Also note that the superscalar program generator is much more complex and there maybe more similiar quirks. An alternate implementation in any other language (go, python etc) should be developed and the results compared, otherwise no blockchain would consider this. Since they will have hardcoded dependency on specific C++ compiler .Also note that, if this is a compiler quirk (looks like it) and randomx is shipped, we will soon land ourselves in mess.Since this is crypto related, we should double check everything.If quirks happen in production, GOD save the devs. :)

**Comment by SChernykh** [comment]
These are not the compiler quirks. The remainder operator (%) in C/C++ is not the same as modulo operation (%) in "school math". But it's well defined in C standard since C99 and in C++ standard since C++03.

**Comment by SChernykh** [comment]
But I agree it's a problem because `index` can be negative as a result: http://cpp.sh/8mdhw

**Comment by SChernykh** [comment]
@graplea90 You were wrong, genInt32() return uint32_t (unsigned int 32), so there is no problem with negative values. Perhaps this function should be renamed though.

**Comment by SChernykh** [comment]
@graplea90 I did your "steps to reproduce" with one change: `uint32_t t = gen.getInt32();` and I get index 6 from 0xece5893b as expected.

**Comment by tevador** [comment]
> ` (c) ece5893b % 7 = 4  used to select source register,  probably compiler play should be 6 , HOW ??  , register 4 is selected`

I checked this case in the debugger and the result is `index = 6` and register r7 is selected correctly (`availableRegisters` contain `0, 1, 2, 3, 4, 6, 7`).

![reg007](https://user-images.githubusercontent.com/37503146/59691072-c11c3b00-91e2-11e9-87fb-9ed43226ebe9.png)

Note that the modulo operation on line 337 is unsigned because both operands are unsigned.

**Comment by hyc** [comment]
@graplea90 By the way, your sample test code is also incorrect.

>  int input = 0xcf77cada;
    printf("(a) 0x%08X %% 8  %2d (signed) %2d (unsigned)  (should be 2)\n",input, input % 8, abs(input)%8);
    
abs(input) doesn't yield the same number since it must truncate to return a positive value.

**Comment by tevador** [comment]
> Also note that the superscalar program generator is much more complex and there maybe more similiar quirks. An alternate implementation in any other language (go, python etc) should be developed and the results compared, otherwise no blockchain would consider this. Since they will have hardcoded dependency on specific C++ compiler

This is not true.

All C++ compilers must produce the same result unless the code contains operations that the C++ standard classifies as 'undefined behavior' or 'implementation-specific'.

**Comment by graplea90** [comment]
modulus operator is the same.This is what i am trying to say, i am seeing different results. all implementations must  give the same results( atleast on most common amd64 arch). As i am trying to understand the implementation, i have come to this conclusion. see detailed tracing.

```
checking s reg 0 available 
checking s reg 1 available 
checking s reg 2 available 
checking s reg 3 available 
checking s reg 4 available 
checking s reg 5 
checking s reg 6 available 
checking s reg 7 available returning int32 ece5893b
getInt32 -320501445  len 7   ece5893b 
reg index 4
; src = r4

checking d reg 0 cycle 1  canReuse_ 0  src_ 4available 
checking d reg 1 cycle 1  canReuse_ 0  src_ 4available 
checking d reg 2 cycle 1  canReuse_ 0  src_ 4available 
checking d reg 3 cycle 1  canReuse_ 0  src_ 4available 
checking d reg 4 cycle 1  canReuse_ 0  src_ 4
checking d reg 5 cycle 1  canReuse_ 0  src_ 4
checking d reg 6 cycle 1  canReuse_ 0  src_ 4available 
checking d reg 7 cycle 1  canReuse_ 0  src_ 4available returning int32 e306a5bb
getInt32 -486103621  len 6   e306a5bb 
reg index 3
dst = r3
```
As you can see above, i am trying to hunt it down but it consistantly is the same. If the superscalar program has different regs, then surely the final output hash is most probably not the same.
Have anyone compared that the same hash is generated on 2 different platforms  with same inputs ?
Have you published some hashes for reference so that the output can be compared  on different platforms/archs/implementations ?

This behaviour exists on linux mint if it helps.

**Comment by SChernykh** [comment]
>  i am seeing different results.

Because you use `int` in the code you added! genInt32() returns unsigned int! Fix it first (in your testing code) then test again.

**Comment by SChernykh** [comment]
> Have anyone compared that the same hash is generated on 2 different platforms with same inputs ?

Yes, Windows, Linux, MacOS on x86, Linux on ARM. I think we also tested PowerPC and had some issues with big-endian compatibility, but they were fixed.

**Comment by graplea90** [comment]
Fixed. Thanks.  Any plans for alternate implementations for easier deployments ?

**Comment by SChernykh** [comment]
There is no need in that. C/C++ implementation is enough if reference hash vectors are provided (which is in our plans). Any ambiguities will be resoled with reference vectors. But if there is any place in the code which is undefined/implementation defined behavior in C/C++, you can open another Github issue.

**Comment by graplea90** [comment]
Thanks

**Comment by SChernykh** [comment]
@tevador It would still be nice to rename genInt32() into genUInt32() since current name is misleading.
