### ISSUE TITLE
Developer logical error

### ISSUE THREAD

**Issue by graplea90** [tevador/RandomX#78]
Please check this line https://github.com/tevador/RandomX/blob/8ff1bf027abf351f7763e52b55f018b69e0e77f0/src/vm_interpreted.cpp#L632

The variable created is not used, instead a constant value is used in following. Can the developer explain this whether it is a typo. If it's a typo, it will change the reference vectors.
Once the code goes in production, fixing such errors are impossible, since they will change the reference vectors.
the project looks good.however, having 2 implementations will make sure the implementation bugs are not present.I would again request for a rewrite.
Holla !

**Comment by SChernykh** [comment]
This is fixed in https://github.com/tevador/RandomX/pull/73

**Comment by tevador** [comment]
>  it will change the reference vectors

Unused code cannot change the behavior of the program by definition.
