### ISSUE TITLE
ERROR: Dataset allocation failed with large pages mode enabled

### ISSUE THREAD

**Issue by kio3i0j9024vkoenio** [tevador/RandomX#79]
Testing current release on a HP DL580 Server with 4x Xeon E7-8837 processors. System has 32GB memory (8GB on each processor).

Xeon E7-8837 Specs:
http://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%20E7-8837.html

This is the command:
miner@DL580-G7-3:~/RandomX/bin$ ./benchmark --mine --largePages

and the results:
RandomX benchmark
 - full memory mode (2080 MiB)
 - interpreted mode
 - hardware AES mode
 - large pages mode
Initializing (1 thread) ...
ERROR: Dataset allocation failed

**Comment by tevador** [comment]
Please post the result of `cat /proc/meminfo`.

**Comment by kio3i0j9024vkoenio** [comment]
miner@DL580-G7-3:~/RandomX/bin$ cat /proc/meminfo                                                                                                                                            
MemTotal:       32915392 kB                                                                                                                                                                  
MemFree:        28156800 kB                                                                                                                                                                  
MemAvailable:   31124176 kB                                                                                                                                                                  
Buffers:          219960 kB                                                                                                                                                                  
Cached:          3029364 kB                                                                                                                                                                  
SwapCached:            0 kB                                                                                                                                                                  
Active:          1697940 kB                                                                                                                                                                  
Inactive:        2102160 kB                                                                                                                                                                  
Active(anon):     552668 kB                                                                                                                                                                  
Inactive(anon):    12416 kB                                                                                                                                                                  
Active(file):    1145272 kB                                                                                                                                                                  
Inactive(file):  2089744 kB                                                                                                                                                                  
Unevictable:          32 kB                                                                                                                                                                  
Mlocked:              32 kB                                                                                                                                                                  
SwapTotal:       8376316 kB                                                                                                                                                                  
SwapFree:        8376316 kB                                                                                                                                                                  
Dirty:                 0 kB                                                                                                                                                                  
Writeback:             0 kB                                                                                                                                                                  
AnonPages:        550844 kB                                                                                                                                                                  
Mapped:           201504 kB                                                                                                                                                                  
Shmem:             14304 kB                                                                                                                                                                  
Slab:             390692 kB                                                                                                                                                                  
SReclaimable:     295944 kB                                                                                                                                                                  
SUnreclaim:        94748 kB                                                                                                                                                                  
KernelStack:       12592 kB                                                                                                                                                                  
PageTables:        26076 kB                                                                                                                                                                  
NFS_Unstable:          0 kB                                                                                                                                                                  
Bounce:                0 kB                                                                                                                                                                  
WritebackTmp:          0 kB                                                                                                                                                                  
CommitLimit:    24702940 kB                                                                                                                                                                  
Committed_AS:    3707032 kB                                                                                                                                                                  
VmallocTotal:   34359738367 kB                                                                                                                                                               
VmallocUsed:           0 kB                                                                                                                                                                  
VmallocChunk:          0 kB                                                                                                                                                                  
HardwareCorrupted:     0 kB                                                                                                                                                                  
AnonHugePages:         0 kB                                                                                                                                                                  
ShmemHugePages:        0 kB                                                                                                                                                                  
ShmemPmdMapped:        0 kB                                                                                                                                                                  
CmaTotal:              0 kB                                                                                                                                                                  
CmaFree:               0 kB                                                                                                                                                                  
HugePages_Total:     128                                                                                                                                                                     
HugePages_Free:      128                                                                                                                                                                     
HugePages_Rsvd:        0                                                                                                                                                                     
HugePages_Surp:        0                                                                                                                                                                     
Hugepagesize:       2048 kB                                                                                                                                                                  
DirectMap4k:      301120 kB                                                                                                                                                                  
DirectMap2M:     8077312 kB                                                                                                                                                                  
DirectMap1G:    25165824 kB

**Comment by tevador** [comment]
> HugePages_Total: 128

You don't have enough HugePages. RandomX needs a minimum of ~1200 for mining.

```
sudo sysctl -w vm.nr_hugepages=1200
```

**Comment by kio3i0j9024vkoenio** [comment]
Thanks.

I will try 2048.

The 128 was what previously was necessary for Cryptonight CPU mining.

**Comment by kio3i0j9024vkoenio** [comment]
With 2048 HugePages it still fails

miner@DL580-G7-3:~/RandomX/bin$ ./benchmark --mine --largePages --jit
RandomX benchmark
 - full memory mode (2080 MiB)
 - JIT compiled mode
 - hardware AES mode
 - large pages mode
Initializing (1 thread) ... 
ERROR: Dataset allocation failed

Another config setting that was necessary for Cryptonight CPU mining was:

"* soft memlock 262144" and "* hard memlock 262144"

being added to /etc/security/limits.conf

Do the above also need to be changed?

cat /proc/meminfo
MemTotal:       32915368 kB                                                                                                                                                                  
MemFree:        31363468 kB                                                                                                                                                                  
MemAvailable:   31402740 kB                                                                                                                                                                  
Buffers:           34816 kB                                                                                                                                                                  
Cached:           412824 kB                                                                                                                                                                  
SwapCached:            0 kB                                                                                                                                                                  
Active:           645588 kB                                                                                                                                                                  
Inactive:         222236 kB                                                                                                                                                                  
Active(anon):     421984 kB                                                                                                                                                                  
Inactive(anon):    14980 kB                                                                                                                                                                  
Active(file):     223604 kB                                                                                                                                                                  
Inactive(file):   207256 kB                                                                                                                                                                  
Unevictable:          32 kB                                                                                                                                                                  
Mlocked:              32 kB                                                                                                                                                                  
SwapTotal:       8376316 kB                                                                                                                                                                  
SwapFree:        8376316 kB                                                                                                                                                                  
Dirty:                 4 kB                                                                                                                                                                  
Writeback:             0 kB                                                                                                                                                                  
AnonPages:        420356 kB                                                                                                                                                                  
Mapped:           181956 kB                                                                                                                                                                  
Shmem:             16780 kB                                                                                                                                                                  
Slab:             126424 kB                                                                                                                                                                  
SReclaimable:      48020 kB                                                                                                                                                                  
SUnreclaim:        78404 kB                                                                                                                                                                  
KernelStack:       11536 kB                                                                                                                                                                  
PageTables:        24668 kB                                                                                                                                                                  
NFS_Unstable:          0 kB                                                                                                                                                                  
Bounce:                0 kB                                                                                                                                                                  
WritebackTmp:          0 kB                                                                                                                                                                  
CommitLimit:    24702928 kB                                                                                                                                                                  
Committed_AS:    3243180 kB                                                                                                                                                                  
VmallocTotal:   34359738367 kB                                                                                                                                                               
VmallocUsed:           0 kB                                                                                                                                                                  
VmallocChunk:          0 kB                                                                                                                                                                  
HardwareCorrupted:     0 kB                                                                                                                                                                  
AnonHugePages:         0 kB                                                                                                                                                                  
ShmemHugePages:        0 kB                                                                                                                                                                  
ShmemPmdMapped:        0 kB                                                                                                                                                                  
CmaTotal:              0 kB                                                                                                                                                                  
CmaFree:               0 kB                                                                                                                                                                  
HugePages_Total:     128                                                                                                                                                                     
HugePages_Free:      128                                                                                                                                                                     
HugePages_Rsvd:        0                                                                                                                                                                     
HugePages_Surp:        0                                                                                                                                                                     
Hugepagesize:       2048 kB                                                                                                                                                                  
DirectMap4k:      239680 kB                                                                                                                                                                  
DirectMap2M:     6041600 kB                                                                                                                                                                  
DirectMap1G:    27262976 kB

**Comment by hyc** [comment]
Your /proc/meminfo clearly shows you only have 128 hugepages, not 2048.

**Comment by kio3i0j9024vkoenio** [comment]
Okay I see that HugePages_Total: 128 in the above?

I had changed /etc/sysctl.conf with:

vm.nr_hugepages=2048

and rebooted.

Why did HugePages_Total: 128 not change to 2048?

**Comment by kio3i0j9024vkoenio** [comment]
Okay doing the: sudo sysctl -w vm.nr_hugepages=1200 worked.

I am not sure why the vm.nr_hugepages=2048 in /etc/sysctl.conf didn't.

I will change it to 1200 in /etc/sysctl.conf and reboot to see if it sticks.

**Comment by kio3i0j9024vkoenio** [comment]
Okay. Problem solved.

Changing /etc/sysctl.conf to vm.nr_hugepages=1200 and rebooting now works.

cat /proc/meminfo now shows:

HugePages_Total:    1200                                                                                                                                                                     
HugePages_Free:     1200                                                                                                                                                                     
HugePages_Rsvd:        0                                                                                                                                                                     
HugePages_Surp:        0                                                                                                                                                                     
Hugepagesize:       2048 kB                                                                                                                                                                  

Using vm.nr_hugepages=2048 must have exceeded some limit.

**Comment by kio3i0j9024vkoenio** [comment]
Failure again occurred with HugePages_Total: 1200 when trying to benchmark on all four processors.

seq 0 3 | xargs -P 0 -I node numactl -N node ./benchmark --mine --largePages --jit --nonces 100000 --init 8 --threads 8

Setting sudo sysctl -w vm.nr_hugepages=1500 Failed
Setting sudo sysctl -w vm.nr_hugepages=2048 Failed
Setting sudo sysctl -w vm.nr_hugepages=4096 Failed
Setting sudo sysctl -w vm.nr_hugepages=6144 Works

HugePages_Total:    6144
HugePages_Free:     6144
HugePages_Rsvd:          0
HugePages_Surp:          0
Hugepagesize:        2048 kB

miner@DL580-G7-3:~/RandomX/bin$ seq 0 3 | xargs -P 0 -I node numactl -N node ./benchmark --mine --largePages --jit --nonces 100000 --init 8 --threads 8                                      
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
Memory initialized in 7.60939 s                                                                                                                                                              
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Memory initialized in 7.6721 s                                                                                                                                                               
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Memory initialized in 7.67612 s                                                                                                                                                              
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Memory initialized in 7.68426 s                                                                                                                                                              
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2193.56 hashes per second                                                                                                                                                       
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2188.84 hashes per second                                                                                                                                                       
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2185.41 hashes per second                                                                                                                                                       
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2168.51 hashes per second                                                                                                                                                       
miner@DL580-G7-3:~/RandomX/bin$ seq 0 3 | xargs -P 0 -I node numactl -N node ./benchmark --mine --largePages --jit --nonces 100000 --init 8 --threads 8                                      
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
Memory initialized in 7.62292 s                                                                                                                                                              
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Memory initialized in 7.65701 s                                                                                                                                                              
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Memory initialized in 7.66755 s                                                                                                                                                              
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Memory initialized in 7.68804 s                                                                                                                                                              
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2194.18 hashes per second                                                                                                                                                       
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2191.11 hashes per second                                                                                                                                                       
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2185.33 hashes per second                                                                                                                                                       
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2173.02 hashes per second
