### ISSUE TITLE
Number of Large Pages necessary for quad processors slows down H/s on one instance

### ISSUE THREAD

**Issue by kio3i0j9024vkoenio** [tevador/RandomX#80]
My test system is a HP DL580 with Quad Xeon E7-8837 Processors. 8GB of PC3-10600R is attached to each Processor (NUMA) for a system total of 32GB.

Test #1:

sudo sysctl -w vm.nr_hugepages=1200

miner@DL580-G7-3:~/RandomX/bin$ ./benchmark --mine --largePages --jit --threads 28 --nonces 100000                                                                                           
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (1 thread) ...                                                                                                                                                                  
Memory initialized in 38.189 s                                                                                                                                                               
Initializing 28 virtual machine(s) ...                                                                                                                                                       
Running benchmark (100000 nonces) ...                                                                                                                                                        
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 7193.61 hashes per second                                                                                                                                                       

Test #2

miner@DL580-G7-3:~/RandomX/bin$ seq 0 3 | xargs -P 0 -I node numactl -N node ./benchmark --mine --largePages --jit --nonces 100000 --init 8 --threads 8                                      
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
ERROR: Dataset allocation failed                                                                                                                                                             
ERROR: Dataset allocation failed                                                                                                                                                             
ERROR: Dataset allocation failed                                                                                                                                                             
ERROR: Dataset allocation failed                                                                                                                                                             

This failed because of too few Large Pages. I had to go to 4800 for this test to work

miner@DL580-G7-3:~/RandomX/bin$ seq 0 3 | xargs -P 0 -I node numactl -N node ./benchmark --mine --largePages --jit --nonces 100000 --init 8 --threads 8                                      
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (8 threads) ...                                                                                                                                                                 
Memory initialized in 7.57606 s                                                                                                                                                              
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Memory initialized in 7.65632 s                                                                                                                                                              
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Memory initialized in 7.66377 s                                                                                                                                                              
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Memory initialized in 7.67908 s                                                                                                                                                              
Initializing 8 virtual machine(s) ...                                                                                                                                                        
Running benchmark (100000 nonces) ...                                                                                                                                                        
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2191.14 hashes per second                                                                                                                                                       
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2189.07 hashes per second                                                                                                                                                       
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2185.16 hashes per second                                                                                                                                                       
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 2171.41 hashes per second  
                                                                                                                                                     
Rerunning the first test with 4800 Large Pages cuts the hash rate in half:

miner@DL580-G7-3:~/RandomX/bin$ ./benchmark --mine --largePages --jit --threads 28 --nonces 100000                                                                                           
RandomX benchmark                                                                                                                                                                            
 - full memory mode (2080 MiB)                                                                                                                                                               
 - JIT compiled mode                                                                                                                                                                         
 - hardware AES mode                                                                                                                                                                         
 - large pages mode                                                                                                                                                                          
Initializing (1 thread) ...                                                                                                                                                                  
Memory initialized in 38.3122 s                                                                                                                                                              
Initializing 28 virtual machine(s) ...                                                                                                                                                       
Running benchmark (100000 nonces) ...                                                                                                                                                        
Calculated result: 9b22794882187000d62c6d2b228fab5e585767aaaa5eb74905b0c7c00fcbdad8                                                                                                          
Performance: 3471.44 hashes per second                                                                                                                                                       

The 4800 Large Pages slowed down the hash rate by 50% vs 1200 Large Pages.

I wonder if having the 4800 Large Pages that was required for the Quad Processor test also slowed it down where it too was hindering the hash rate?

Hopefully the future RandomX released miners will not require four times the Large Page size.

**Comment by tevador** [comment]
RandomX requires ~1200 hugepages because each hugepage is 2 MiB and RandomX requires 256 + 2080 + 16 = 2352 MiB (8 threads).

For NUMA, you ideally need to allocate the whole Dataset on each node to eliminate slow memory accesses across nodes. That's why you can get ~8800 H/s with 4 instances of the benchmark. This is a fundamental property of RandomX and cannot be removed.

As to why the last benchmark was much slower, I'm guessing that the OS allocated the whole Dataset on one node, so the hashrate was limited by dual channel memory to ~3000 H/s.

**Comment by kio3i0j9024vkoenio** [comment]
[quote]As to why the last benchmark was much slower, I'm guessing that the OS allocated the whole Dataset on one node, so the hashrate was limited by dual channel memory to ~3000 H/s.[/quote]

What I believe that is happening is that when 1200 Large Pages are allocated that 300 of the Large Pages are mapped to each of the four processors and that each processor's local memory gets about 25% of the Dataset.

But when 4800 Large Pages are allocated 1200 of the Large Pages are mapped to each of the four processors and that only one of the processor's local memory gets 100% of the Dataset.

That means that memory access from the other three processors need to do at least one hop through another processor to access the Dataset.

That would explain the massive 52.1% slowdown.

**Comment by tevador** [comment]
> What I believe that is happening is that when 1200 Large Pages are allocated that 300 of the Large Pages are mapped to each of the four processors and that each processor's local memory gets about 25% of the Dataset.
>
>But when 4800 Large Pages are allocated 1200 of the Large Pages are mapped to each of the four processors and that only one of the processor's local memory gets 100% of the Dataset.

This observation is most likely correct.

> That means that memory access from the other three processors need to do at least one hop through another processor to access the Dataset.

However, this is true for both of the above cases.

Case 1 (25% of Dataset per node): 75% of accesses of each node must access another CPU's memory.

Case 2: (100% of Dataset on Node 1): 0% of accesses of Node 1 and 100% of accesses of Nodes 2-4 must access another CPU's memory. Overall, 75% of accesses.

The only difference is that in Case 2, all of the memory accesses go through the memory controller of Node 1, which is what causes the bottleneck.

**Comment by kio3i0j9024vkoenio** [comment]
#1: Can a RandomX CPU miner that uses NUMA work without accessing the Dataset memory via hops through other processors?

#2: Or do all the threads need to access the whole Dataset?

If it is #2 above then I can see that the best hashrates for a quad processor server would be to run four individual instances of RandomX with each affined to different processors. That way each processor would access their dataset from their local memory.

This is how I have been testing on the HP DL580 with quad Xeon E7-8837's:

sudo sysctl -w vm.nr_hugepages=4800

seq 0 3 | xargs -P 0 -I node numactl -N node ./benchmark --mine --largePages --jit --nonces 100000 --init 8 --threads 8

Is this correct in my understanding that each of the four RandomX benchmark programs are running on a unique processor and will only access local memory for that processor?

http://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%20E7-8837.html

Second question is since a Xeon E7-8837 has eight cores, 8x 256 KB L2 Cache, 24MB L3 Cache is the options for RandomX "--init 8 --threads 8" optimal.

If not what would optimal values be?

**Comment by tevador** [comment]
> Can a RandomX CPU miner that uses NUMA work without accessing the Dataset memory via hops through other processors?

Yes, by allocating one Dataset per NUMA node.

> Or do all the threads need to access the whole Dataset?

Yes.

> Is this correct in my understanding that each of the four RandomX benchmark programs are running on a unique processor and will only access local memory for that processor?

Yes.

> is the options for RandomX "--init 8 --threads 8" optimal

Most likely, since each CPU has 8 cores and 8 threads.

**Comment by kio3i0j9024vkoenio** [comment]
On the subject "--init 8 --threads 8" settings being optimal because the E7-8837 has eight cores.

Is the L3 cache important for RandomX?

The Xeon E7-8837 has 24MB of L3 cache and only having 8 threads I wonder if it is being fully utilized.

**Comment by kio3i0j9024vkoenio** [comment]
I will start my new question about optimal values for "init and threads" in another thread as the original issue was resolved.
