### ISSUE TITLE
Floating point CFROUND instruction,Dangerous Waters

### ISSUE THREAD

**Issue by graplea90** [tevador/RandomX#81]
Floating point round has always been in issues, where repeat calculations are required across software/hardware platforms.
see this

1. https://scungao.github.io/papers/fb.pdf
2. https://www.exploringbinary.com/incorrectly-rounded-conversions-in-gcc-and-glibc/
3. https://www.cockroachlabs.com/blog/rounding-implementations-in-go/

Randomx rounding modes CFROUND are exposed on few platforms. for eg.  python, go, java does not provide access to hardware rounding modes. so it would be great if we drop the CFROUND and choose something else, FMUL etc for future proofing.  Instead of hardware rounding, even software rounding  would be okay.  bugs are rare to found, see this https://cryptojedi.org/crypto/#ed25519 but they exists.
I am expecting randomx to be purely software implementable and thus this will allow randomx to be used/ported in android java apps, javascript, .NET, python,go etc. 

Possible fixes
1. Implement software rounding  which emulates HW: this is easier said than done.so javascript and other software implementation can use it as backup
2. Remove the FROUND instruction altogether and only use the default rounding mode round-to-nearest. we can choose something else.

we have to provide atleast language portability for wide variety of use cases to be possible.

Thanks.

**Comment by SChernykh** [comment]
First link is about trigonometric/logarithm/exponential functions which are not required to be precise/correctly rounded by IEEE standard. RandomX uses only functions which must have correct rounding in all modes (+,-,*,/,sqrt). Second link is about converting from FP numbers represented as decimal string to FP numbers as binary, this is not used in RandomX. Third link is about Go language, not relevant here.

Everything regarding rounding modes and FP operations in RandomX is strictly defined in IEEE-754 standard. if some other language doesn't support it, it's not RandomX's problem.

To reiterate it: all RandomX operations are strictly defined and have only 1 possible output for each possible input. Any Turing-complete programming language can have RandomX implementation. Performance of such implementation depends on how many RandomX features are supported directly by this language, again it's not RandomX's problem if some language performs poorly.

**Comment by SChernykh** [comment]
> Implement software rounding which emulates HW: this is easier said than done.so javascript and other software implementation can use it as backup

This was already done multiple times before. Software floating point implementations exist, most of them are IEEE-754 compatible.

**Comment by tevador** [comment]
Yes, there are fully functional software implementations, for example [Berkeley SoftFloat](http://www.jhauser.us/arithmetic/SoftFloat.html), which use only integer operations, so they can be ported to any reasonable programming language.

We actually planned to include a SoftFloat implementation as a backup for the reference interpreter, but we haven't found any platform yet that doesn't give the correct results.

Quote from readme:

>The reference implementation has been validated on the following platforms:
> * x86 (32-bit, little-endian)
> * x86-64 (64-bit, little-endian)
> * ARMv7+VFPv3 (32-bit, little-endian)
> * ARMv8 (64-bit, little-endian)
> * PPC64 (64-bit, big-endian)

**Comment by graplea90** [comment]
Third link was mentioned to showcase the difficulty for implementing Round function. Rest of RandomX is portable to most other programming languages. Due to this instruction, the portability to any programming language severely decreases (read NONE except c/c++). Please NOTE that IEEE 784 IP cores are available for fpgas https://www.xilinx.com/support/documentation/ip_documentation/floating_point/v6_0/ds816_floating_point.pdf    Therefore, i would recommed to drop this instruction and improve portability/usability rather than stick with it. ASIC resistance must come from the design and not on some specific instruction which is too hard to implement.

**Comment by SChernykh** [comment]
Different rounding modes mean more logic to implement for ASIC -> more chip area -> less ASIC efficiency. They have to fully implement IEEE-754 operations and all rounding modes. This was a deliberate design decision for RandomX. Whether or not it is hard to implement RandomX is of less importance. Smaller ASIC advantage is a top priority here, no exceptions.

**Comment by graplea90** [comment]
If this is the idea, then i would suggest to increase the VM opcode count to say 300 or 3000 or 30000 instructions (this will increase chip area for sure). On second thoughts, why not  use  intel instruction set and use qemu/ bochs as interpreter, This will definitely increase the ASIC to processor levels, so most (read ALL) of the ASIC designers are pushed out of the game.Also note that since X86 instruction set is mostly patent, so we can be sure that except intel/AMD we will not see better ASICs for sure, since they already are producing the best ASICs. Buddy, we are talking ASIC resistance based on crypto (indirectly memory latency).  What i am trying to suggest is this instruction has more disadvantages  and less advantages.

**Comment by tevador** [comment]
> Except c/c++/asm most languages do not allow even changing the default mode

RandomX is targeting CPU hardware, not a specific programming language. CPUs implement all 4 rounding modes in silicon.

**Comment by SChernykh** [comment]
First, I'm not your buddy. For all we know, you can work for ASIC manufacturers and try to push for simpler RandomX version. Second, RandomX has a VM with generalized instructions specifically to avoid x86 patents dependency.

**Comment by hyc** [comment]
@graplea90 

> If this is the idea, then i would suggest to increase the VM opcode count to say 300 or 3000 or 30000 instructions

Don't be stupid. The design.md doc already describes the design constraints that dictated the size of the programs and choice of instruction sets. Posting suggestions that ignore these constraints is just a waste of time.

**Comment by graplea90** [comment]
If you are hurt, Sorry for calling you buddy (my bad).I thought we are working towards a common goal of ASIC resistance.Together with blockchains( blockchains also use languages other than C/C++), I also have the idea to push it more in obscure places such as DDOS protection for form pages (will need javascript implementation) and so on. It's for these reasons that i am trying it to be portable yet compliant. It's for this evaluation that i am going thorugh code line by line. If changing a single instruction will defeat ASIC resistance, then the project is not worth looking into.i was also thinking it as a universal ASIC resistance, which you can stick anywhere for results. Portability/usability is what helps in long term. i do not wish to see RandomX 2.0 for atleast another 2-3 years. i believe in KISS ( keep it simple stupid). for ASICs, IP cores  are availble which implement full IEEE 754 ( drag and drop) so disadvantage to them, On the other side, you have portability hell for non C/C++ languages. I suggest we give a deep thinking about it, as we have time. We are losing more than gains.

**Comment by SChernykh** [comment]
> If changing a single instruction will defeat ASIC resistance, then the project is not worth looking into

Removing rounding modes doesn't defeat ASIC resistance, but it does reduce it. We've been tuning RandomX for quite some time, so any change will make it less resistant unless this change is well thought and has good reasoning.
