### ISSUE TITLE
Uninitialized entropy buffer?

### ISSUE THREAD

**Issue by veorq** [tevador/RandomX#82]
I'm probably missing something but I don't see where/how  `entropyBuffer` is initialized prior to `getEntropy()` calls in  `randomx_vm::initialize()`:

https://github.com/tevador/RandomX/blob/1276d67d2f594ea4a8e9cde28253b1a74769aeb9/src/program.hpp#L53-L66

**Comment by SChernykh** [comment]
It's filled here: https://github.com/tevador/RandomX/blob/master/src/virtual_machine.cpp#L130
Not very obvious though.

**Comment by tevador** [comment]
The whole structure (both `entropyBuffer` and `programBuffer`) is initialized here:

https://github.com/tevador/RandomX/blob/f7c99c5b580987a2d4793bac3d073702b7cb81e9/src/virtual_machine.cpp#L128-L131

`generateProgram` is always called before `randomx_vm::initialize`.

This corresponds to step 7 from the [documentation](https://github.com/tevador/RandomX/blob/master/doc/specs.md#2-algorithm-description).

**Comment by veorq** [comment]
Of course, thanks for the quick response.
