### ISSUE TITLE
Potential out-of-bound write in fillAes1Rx4

### ISSUE THREAD

**Issue by veorq** [tevador/RandomX#83]
There should probably be a check that  `outputSize % 64 == 0`, otherwise the function will write out of the allocated memory (same for 4Rx4): 

https://github.com/tevador/RandomX/blob/master/src/aes_hash.cpp#L137-L148

**Comment by tevador** [comment]
Calls to both functions are made with compile-time constants:

https://github.com/tevador/RandomX/blob/f7c99c5b580987a2d4793bac3d073702b7cb81e9/src/virtual_machine.cpp#L123-L131

`ScratchpadSize` must be a power of 2 greater than or equal to 64, which is enforced by several `static_asserts` in [common.hpp](https://github.com/tevador/RandomX/blob/91cd35ff13aa3c8fa77ebe6cd863708ea6c6add3/src/common.hpp).

`sizeof(program) % 64 == 0` is enforced here:

https://github.com/tevador/RandomX/blob/f7c99c5b580987a2d4793bac3d073702b7cb81e9/src/program.hpp#L70

**Comment by veorq** [comment]
Looks good, thanks!
