### ISSUE TITLE
BLAKE2 return values unchecked

### ISSUE THREAD

**Issue by veorq** [tevador/RandomX#84]
Unlikely that something goes wrong but better to check that `blake2b()` returns 0, otherwise nothing would be written to `tempHash`

https://github.com/tevador/RandomX/blob/master/src/randomx.cpp#L236-L246

**Comment by tevador** [comment]
The validity of the parameters passed to `blake2b` can be verified at compile time, so it should never fail.

https://github.com/tevador/RandomX/blob/2706a8b7533860900b33ac69899471e5127a4872/src/blake2/blake2b.c#L315-L346

We could add an `assert(ret == 0);` in randomx.cpp, but I think it's redundant.

**Comment by tevador** [comment]
Added `assert` in #88.
