### ISSUE TITLE
Benchmarking tool may corrupt MSCORMMC.DLL - not tested on latest version.

### ISSUE THREAD

**Issue by mistfpga** [tevador/RandomX#85]
Hi,

Im new to GitHub in general and so sorry if this isn't the right place. I will write up a full bug report should it be needed.

Running two instances of the benchmarking tool causes dotnet file corruption and blue screens.

It might be worth putting a warning on the release page for the windows tool that you need to make sure you are up to date on everything or you might corrupt dotnet. - After this bug is triggered you cannot run the tool at all without a blue screen "Stop Code: Memory Management"

I have put the fix for this at the end of this report.

I will be putting full version numbers, steps to reproduce and retest with the latest benchmarking tool when I can build a new test environment.  (the version of the benchmark tool is the one I forked on my GitHub)

I think, although I am not 100% sure that this was a cache bug specific to intel processors. I will investigate further.  here is the system specs that I saw the issue.  Will test on ryzen when I work out what patch fixes the issue. (I can now run two instances without issue)

Name Intel Core i7 3540M
Codename Ivy Bridge
Specification Intel® Core™ i7-3540M CPU @ 3.00GHz
Package (platform ID) Socket 1023 FCBGA (0x4)
CPUID 6.A.9
Extended CPUID 6.3A
Core Stepping E1/L1

A Number of dotnet files corrupted. specifically MSCORMMC.DLL which makes sense.
This might have happened because I was missing two updates for recent dotnet.

In order to get these update I needed to install dotnet 4.8. - This also appears to gives a hash rate increase. don’t know why.

run system file checker ( sfc /scannow ) This will fix the massive cpu usage.
reboot to apply the file fixes
http://go.microsoft.com/fwlink/?LinkId=2085155
then go through windows updates for a while.
should be fixed.

An additional bonus of having all this up to date is that you get significant hashrate increase. Version numbers to come.

**Comment by tevador** [comment]
RandomX has nothing to do with .NET. It's a native C++ library/application.

**Comment by mistfpga** [comment]
I understand this and I apologies for not having time to investigate this further yet.

To be clear:

You code does not contain a bug, and their is no fix that you can do to your code. I was suggesting adding a warning, something along the lines of "Due to memory access issues within windows please make sure you are running the latest version of windows (1903) and the dotnet framework (4.8 with security updates)."

 I did both the 1903 and 4.8 to fix dotnet update the same time.  so cannot say for certain where the issue is, however your code will under certain circumstances expose a bug in the underlying kernel resource allocation framework.  I can post crash dump analysis (not publicly because it contains kernel memory space)

This is why the corruption of mscormmc.dll (issues with these dlls are not specific to dotnet, they are used by the mmc.) makes sense, it is used by the kernel. 

The dotnet corruption might be an artefact. it might be a kernel issue in windows that was addressed with the 1903 update, that just happened to corrupt my dotnet install, this would be more troubling because it might corrupt any program trying to use the mmc.

I cant tell until I test fully. which is why I apologise for the rubbish bug report. I haven't had time to get you the info that would help you identify the issue with windows and why the disclaimer is so broad. I know this isnt too helpful. sorry.

**Comment by tevador** [comment]
I just tested running 2 instances of the benchmark on my laptop (Intel Core i7-8550U, Windows 10 1803) - no issues whatsoever.

 Are you sure it's not a hardware problem in your computer (faulty RAM or hard drive)?

**Comment by mistfpga** [comment]
yes, I can run two instances fine now. This hardware is stable, not overclocked.  I was pushing it really hard with the benchmark and it would always throttle. The performance update is really strange, before I got best results from --init 4 --threads 3 , now it is as the readme recommends and best at --threads 2.

I have changed the title to refect your information.

I will investigate as soon as possible.  but due to the nature I need to make sure I get the stuff done on this laptop before I can roll back the updates and start again.

I still have the kernel dumps though.  I have given them a brief look over, but im missing quite a few windows symbols.  I will try to get this worked out tomorrow. (UTC) and then get this issue closed off.

**Comment by mistfpga** [comment]
I have adjusted the title again.

> Intel Core i7-8550U
Can you try running 4 instances please.

Here is the basic data with symbols. (the minidump with symbols overview is at the end)  Looking into this further it seems it might be specific to this cpu and the shared memory between the gpu/cpu.

I have uninstalled all the 1903 updates that were installed but cannot rollback 1903, to see what 1803 issues were unpatched before the 1903 update.
I will have to load from an old backup this will take a while for me to do.

Im not sure of the protocol, do I close as not able to reproduce, then reopen? or do I leave it open until I get more time? I will either close or update with reproduction steps by tomorrow EOB UTC. (unless you want to do it before then.)

fwiw:

This is not the initial crashdump but a subsequent one cause by just running one instance of the tool after the bug has been triggered. - I had it set to overwrite :/

VIDEO_MEMORY_MANAGEMENT_INTERNAL (10e)
The video memory manager encountered a condition that it can't recover from. By crashing,
the video memory manager is attempting to get enough information into the minidump such that
somebody can pinpoint what lead to this condition.
Arguments:
Arg1: 000000000000002a, The subtype of the bugcheck:
Arg2: ffffba0903008000
Arg3: ffffba0907cca3d0
Arg4: ffffffffc4e1376a

Debugging Details:
------------------
DUMP_CLASS: 1
DUMP_QUALIFIER: 401
BUILD_VERSION_STRING:  18362.1.amd64fre.19h1_release.190318-1202
SYSTEM_MANUFACTURER:  Dell Inc.
SYSTEM_PRODUCT_NAME:  Latitude E6230
SYSTEM_SKU:  Latitude E6230
SYSTEM_VERSION:  01
BIOS_VENDOR:  Dell Inc.
BIOS_VERSION:  A16
BIOS_DATE:  10/13/2016
BASEBOARD_MANUFACTURER:  Dell Inc.
BASEBOARD_PRODUCT:  0Y47PX
BASEBOARD_VERSION:  A00
DUMP_TYPE:  1
BUGCHECK_P1: 2a
BUGCHECK_P2: ffffba0903008000
BUGCHECK_P3: ffffba0907cca3d0
BUGCHECK_P4: ffffffffc4e1376a
BUGCHECK_STR:  0x10e_2a
CPU_COUNT: 4
CPU_MHZ: bae
CPU_VENDOR:  GenuineIntel
CPU_FAMILY: 6
CPU_MODEL: 3a
CPU_STEPPING: 9
CPU_MICROCODE: 6,3a,9,0 (F,M,S,R)  SIG: 20'00000000 (cache) 20'00000000 (init)
DEFAULT_BUCKET_ID:  CODE_CORRUPTION
PROCESS_NAME:  System
CURRENT_IRQL:  0
ANALYSIS_SESSION_HOST:  *******
ANALYSIS_SESSION_TIME:  06-25-2019 09:09:00.0976
ANALYSIS_VERSION: 10.0.15063.137 amd64fre
LAST_CONTROL_TRANSFER:  from fffff807331841a0 to fffff80725fbc8a0

<nipped stack and memory layout>


MODULE_NAME: memory_corruption
IMAGE_NAME:  memory_corruption
FOLLOWUP_NAME:  memory_corruption
DEBUG_FLR_IMAGE_TIMESTAMP:  0
MEMORY_CORRUPTOR:  LARGE
FAILURE_BUCKET_ID:  MEMORY_CORRUPTION_LARGE
BUCKET_ID:  MEMORY_CORRUPTION_LARGE
PRIMARY_PROBLEM_CLASS:  MEMORY_CORRUPTION_LARGE
TARGET_TIME:  2019-06-23T17:49:39.000Z
OSBUILD:  18362
OSSERVICEPACK:  0
SERVICEPACK_NUMBER: 0
OS_REVISION: 0
SUITE_MASK:  272
PRODUCT_TYPE:  1
OSPLATFORM_TYPE:  x64
OSNAME:  Windows 10
OSEDITION:  Windows 10 WinNt TerminalServer SingleUserTS
OS_LOCALE:  
USER_LCID:  0
OSBUILD_TIMESTAMP:  unknown_date
BUILDDATESTAMP_STR:  190318-1202
BUILDLAB_STR:  19h1_release
BUILDOSVER_STR:  10.0.18362.1.amd64fre.19h1_release.190318-1202
ANALYSIS_SESSION_ELAPSED_TIME:  2850
ANALYSIS_SOURCE:  KM
FAILURE_ID_HASH_STRING:  km:memory_corruption_large
FAILURE_ID_HASH:  {e29154ac-69a4-0eb8-172a-a860f73c0a3c}
Followup:     memory_corruption

**Comment by mistfpga** [comment]
Hi,

I managed to get this file corruption happen once more on a fully patched machine - But no blue screen no noticeabe issues with windows or the benchmarking tool, even through continual stress testing after the inital corruption.

Using this command periodically through testing
`sfc  /VERIFYFILE="C:\WINDOWS\Microsoft.NET\Framework\v1.0.3705\mscormmc.dll"`

I did run a full sfc /scannow check after noticing this and this was the only issue.

After a couple of days I got this in my logs,

>2019-06-25 20:06:10, Info                  CSI    0000023f Hashes for file member [l:12]'mscormmc.dll' do not match.

> Expected: {l:32 ml:33 b:0a7002ddb80379b6e5965c91e0286cd87db22bfdc61b0d1e743e5eeb8b570edc}.

> Actual: {l:32 b:6081ecf5a17f618e1efb0d76843f59b0c57e4df4dd211b61f46aa9ce364d0d69}.

>2019-06-25 20:06:10, Info                  CSI    00000240 [SR] Repairing corrupted file \??\C:\WINDOWS\Microsoft.NET\Framework\v1.0.3705\\mscormmc.dll from store

Note: This timestamp was not from when the corruption happened, but from when it was fixed. Lots of testing carried on in between that time, which I experienced no unusual behaviour with the tool or windows.

It seems these errors are associated in someway

>ERROR: Dataset allocation failed
>ERROR: JIT compilation is not supported or cache allocation failed

I am closing as unable to reproduce. (I have done this testing on ryzen too). - It is either specific to my system hand how it was configured or it is a really rare corner case (off by one, int overflow, etc.)

I will reopen if I can find concrete reproduction steps.

**Comment by msp01** [comment]
nice project

**Comment by ljcool2006** [comment]
> Hi,
> 
> I managed to get this file corruption happen once more on a fully patched machine - But no blue screen no noticeabe issues with windows or the benchmarking tool, even through continual stress testing after the inital corruption.
> 
> Using this command periodically through testing `sfc /VERIFYFILE="C:\WINDOWS\Microsoft.NET\Framework\v1.0.3705\mscormmc.dll"`
> 
> I did run a full sfc /scannow check after noticing this and this was the only issue.
> 
> After a couple of days I got this in my logs,
> 
> > 2019-06-25 20:06:10, Info                  CSI    0000023f Hashes for file member [l:12]'mscormmc.dll' do not match.
> 
> > Expected: {l:32 ml:33 b:0a7002ddb80379b6e5965c91e0286cd87db22bfdc61b0d1e743e5eeb8b570edc}.
> 
> > Actual: {l:32 b:6081ecf5a17f618e1efb0d76843f59b0c57e4df4dd211b61f46aa9ce364d0d69}.
> 
> > 2019-06-25 20:06:10, Info                  CSI    00000240 [SR] Repairing corrupted file ??\C:\WINDOWS\Microsoft.NET\Framework\v1.0.3705\mscormmc.dll from store
> 
> Note: This timestamp was not from when the corruption happened, but from when it was fixed. Lots of testing carried on in between that time, which I experienced no unusual behaviour with the tool or windows.
> 
> It seems these errors are associated in someway
> 
> > ERROR: Dataset allocation failed
> > ERROR: JIT compilation is not supported or cache allocation failed
> 
> I am closing as unable to reproduce. (I have done this testing on ryzen too). - It is either specific to my system hand how it was configured or it is a really rare corner case (off by one, int overflow, etc.)
> 
> I will reopen if I can find concrete reproduction steps.

Funny how you say that it's specific to your system; I found this GitHub issue via a Google search and even though I have never installed RandomX to my knowledge, my mscormmc.dll was also corrupt.
