### ISSUE TITLE
RandomX is only using 6 of the 12 cores in an AMD Opteron 6234

### ISSUE THREAD

**Issue by kio3i0j9024vkoenio** [tevador/RandomX#89]
On a DELL R815 with quad Opteron 6234 I can only see 6 of the 12 cores being utilized in each processor.

Opteron 6234 Specs: http://www.cpu-world.com/CPUs/Bulldozer/AMD-Opteron%206234.html

numactl -N 0 ./randomx-benchmark --mine --largePages --jit --nonces 10000 --init X --threads X
where X is 12, 8, 6 and 4 for the following benchmark runs 

--init 12 --threads 12 produces: Performance: 957.634 hashes per second
--init 8 --threads 8 produces: Performance: 1039.64 hashes per second
--init 6 --threads 6 produces: Performance: 1094.64 hashes per second
--init 4 --threads 4 produces: Performance: 877.766 hashes per second

I am using nmon CPU utilization to see what cores are active during a benchmark run

With 12, 8 or 6 threads only 6 of the 12 cores of an Opteron 6234 are active.
With 4 threads only 4 of the 12 cores of an Opteron 6234 are active.

So clearly the threads are limited to 6 for the Opteron 6234.

Is this a bug or is it because the FPU of the Opteron 6234 are (shared between two cores in each module).

Is there any way to improve the performance of RandomX for this Opteron 6234?

**Comment by tevador** [comment]
> numactl -N 0

This command will cause the program to run only on the first NUMA node, i.e. cores 0-5. You have to run 2 copies: one with `-N 0` and one with `-N 1`.

**Comment by kio3i0j9024vkoenio** [comment]
I am well aware that numactl -N 0 only runs on the first NUMA node. I am only trying testing one processor (thus one NUMA node) for now.

an Opterons 6234 has 12 cores and 12 threads, L2 Cache of 6 x 2 MB 16-way set associative shared exclusive caches, L3 Cache of 2 x 8 MB up to 64-way set associative shared caches.

In your reply you state: "first NUMA node, i.e. cores 0-5". But the Opteron 6234 has 12 cores and 12 threads.

Are those 12 cores somehow broken down to be two NUMA nodes?

If that is the case then to fully test all Opterons I would need to do this command:

seq 0 7 | xargs -P 0 -I node numactl -N node ./randomx-benchmark --mine --largePages --jit --nonces 100000 --init 6 --threads 6

Is that correct?



seq 0 3 | xargs -P 0 -I node numactl -N node ./randomx-benchmark --mine --largePages --jit --nonces 100000 --init 6 --threads 6

**Comment by kio3i0j9024vkoenio** [comment]
Again editing does not work for me. Ignore the last seq command. Is this the correct command to fully test a Dell R815 with quad Opteron 6234's:


seq 0 7 | xargs -P 0 -I node numactl -N node ./randomx-benchmark --mine --largePages --jit --nonces 100000 --init 6 --threads 6

**Comment by kio3i0j9024vkoenio** [comment]
Thanks for the help. I was unaware that the Opterons were split to be two NUMA nodes each.

seq 0 7 | xargs -P 0 -I node numactl -N node ./randomx-benchmark --mine --largePages --jit --nonces 100000 --init 6 --threads 6

Produces these results:

Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f                                                                                                          
Performance: 1068.57 hashes per second                                                                                                                                                       
Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f                                                                                                          
Performance: 1067.57 hashes per second                                                                                                                                                       
Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f                                                                                                          
Performance: 1067.37 hashes per second                                                                                                                                                       
Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f                                                                                                          
Performance: 1067.33 hashes per second                                                                                                                                                       
Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f                                                                                                          
Performance: 1066.09 hashes per second                                                                                                                                                       
Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f                                                                                                          
Performance: 1066.65 hashes per second                                                                                                                                                       
Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f                                                                                                          
Performance: 1066.14 hashes per second                                                                                                                                                       
Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f                                                                                                          
Performance: 1064.69 hashes per second                                                                                                                                                       

Or a total of 8534 H/s for the DELL R815 with 4x Opteron 6234's.

**Comment by mistfpga** [comment]
Opteron's are not quite as simple as xeons unfortunately. You might find better results lowering the threads.  Unless you do some special configurations (beyond the scope of this comment) you only get 14mb of L3 cache. (2x7 iirc, I would need to check the data sheet again.)

You might be able to make better use of you memory too buy dropping to 3 threads (depending on how you have it configured). I don't know if you were aware of this and have already tested for it.  I haven't started on my Opteron testing yet.

Hope this helps.

**Comment by kio3i0j9024vkoenio** [comment]
The L3 cache on an Opteron 6238 is 16MB so the 14MB you state fits nicely in it.

I tried the 3 threads you mention but the hashrate drops to 776 H/s per node.

seq 0 1 | xargs -P 0 -I node numactl -N node ./randomx-benchmark --mine --largePages --jit --nonces 10000 --init 3 --threads 3

With 6 threads I am getting 1093 H/s per node

seq 0 1 | xargs -P 0 -I node numactl -N node ./randomx-benchmark --mine --largePages --jit --nonces 10000 --init 6 --threads 6

One thing I had forgotten is that these Opteron's don't always run at their max P State even if running full out 100% per core.

Doing sudo ./TurionPowerControl -psmax 1
and rerunning the 6 thread test

seq 0 7 | xargs -P 0 -I node numactl -N node ./randomx-benchmark --mine --largePages --jit --nonces 100000 --init 6 --threads 6

Results in 1178 H/s per node or 9424 H/s overall which is a 10.4% gain over the 8534 H/s I was getting earlier.

**Comment by mistfpga** [comment]
Thanks for the P-state reminder. I completely forgot about that too.

Those opterons have this issue (1mb of L3 Cache is assigned to HT Assist per cpu) - you may or may not be able to disable this depending on your hardware/processor and or performance.

I cant find the original source for this, but it is from when I was maintaining servers. - it is on the Wikipedia article too though.

Bulldozer
> Interlagos models have 16 MB of L3 cache (2x8 MB) but only 14 MB is visible with the HT Assist feature activated using 2 MB as a directory cache

Piledriver
> Abu Dhabi models have 16 MB of L3 cache (2x8 MB) but only 14 MB is visible with the HT Assist feature activated using 2 MB as a directory cache.

**Comment by kio3i0j9024vkoenio** [comment]
I have had HT Assist disabled since I started Monero mining back in March 2018. I had read it somewhere in the - Building Cheap Miners : My "Secret" - bitcointalk forum.

With RandomX the L3 Cache of 16MB is overkill for the 12 core Opterons as the 256KB L2 Cache is the limitation. That is why 6 threads per NUMA node is optimal.

For 16 core Opterons The 16MB L3 Cache should be useful.

I have a pair of Opteron 6276's coming and I will install them in a SuperMicro 1533 CSE-745 for testing.

**Comment by kio3i0j9024vkoenio** [comment]
Just upgraded one R815 from quad 12-core Opteron 6238's to quad 12-core Opteron 6248's and retested.

sudo ./TurionPowerControl -psmax 1

seq 0 7 | xargs -P 0 -I node numactl -N node ./randomx-benchmark --mine --largePages --jit --nonces 100000 --init 6 --threads 6

4x 12-core Opteron 6238's produces 1178 H/s per node or 9424 H/s overall

4x 12-core Opteron 6348's produces 1326.5 H/s per node or 10612 H/s overall +12.6% higher

The clock speed difference between the 6238 (2900 MHz) and the 6348 (3100 MHz) is 200 MHz. That works out to be 6.9% faster for the 6348 so the additional 5.7% gain for the 6348 must be because of architectural changes.
