### ISSUE TITLE
Low performance for the amd epic 7351p

### ISSUE THREAD

**Issue by zeno39** [tevador/RandomX#91]
Hi tevador, I have a question. I have a AMD epic 7351p 16core 32 thread 8 channels.
If i launch the script randomX i have juste 4000h/s and max 5000
I have 256 go in ddr4 i think it's not a problem, do you have any idea ? Probably my configuration is not good

**Comment by tevador** [comment]
Please post the full command line you use for testing.

**Comment by zeno39** [comment]
randomx-benchmark.exe --mine --init 16 --threads 32 --nonces 100000 --largePages --jit

**Comment by SChernykh** [comment]
EPYC CPUs are 4 NUMA nodes per socket IIRC. You need to run 4 benchmark instances, each with 8 threads and assigned to corresponding NUMA node.

**Comment by zeno39** [comment]
Assigned where ?

**Comment by SChernykh** [comment]
numactl on Linux, I don't know how it's done on Windows.

**Comment by zeno39** [comment]
4core ans 8 thread per instance ?

**Comment by tevador** [comment]
Your CPU consists of 4 NUMA nodes, each node being 4 cores.

Unfortunately, the bechmark doesn't support running in NUMA mode at the moment (see issue #22), but you can estimate the performance by running only 1 node and multiplying by 4:

```
randomx-benchmark.exe --mine --init 4 --threads 4 --affinity 15 --nonces 10000 --largePages --jit
```

This doesn't need to give optimal performance either, it depends on how Windows will allocate the memory.

**Comment by zeno39** [comment]
I have juste 681 h/s

**Comment by SChernykh** [comment]
Try `--affinity 255` and everything else the same.

**Comment by tevador** [comment]
Sorry, should be `--affinity 170`.

**Comment by zeno39** [comment]
1000 h/s

**Comment by zeno39** [comment]
--seed maybe ? And i have 32 threads ans 64mo why i use just 4 threads per launcher ?

**Comment by tevador** [comment]
You can try `--threads 8 --affinity 255`

**Comment by zeno39** [comment]
1345

**Comment by zeno39** [comment]
I think i have to wait for the adapted scripts

**Comment by mistfpga** [comment]
To force an application to use NUMA on windows server / win 10 (i think, I have not double checked, but from win 7 onwards NUMA has been a part of windows)

The most important part is to read the example of how to use CoreInfo

This also article references SSAS but dont worry it, the Windows System Resource Manager/WSRM, or the hyper-x stuff in that article.

https://techcommunity.microsoft.com/t5/DataCAT/Forcing-NUMA-Node-affinity-for-Analysis-Services-Tabular/ba-p/305188

CoreInfo - https://docs.microsoft.com/en-gb/sysinternals/downloads/coreinfo

This shows what cores are assigned to what nodes and roughly what performance costs for each cpu to access each bank. The source code to this might be available from before microsoft acquired sysinternals.

Once you have done this, either apply this hotfix (if it applies to you) or skip this step if it doesn't.
https://support.microsoft.com/en-gb/help/2028687/you-cannot-specify-a-numa-node-when-you-create-a-process-by-using-the

Now you can run benchmark instances per node with something like

[code]
start /NUMA [n] "Numa" cmd \k benchmark.exe --mine --jit --largePages --init 8 --threads 8 --nonces 10000
[/code]

For each NUMA node you have.  Also adjust the --init and --threads for your hardware.
the /k parameter means the cmd prompt will stay open even after the benchmark has finished.

This might be all you need but you will probably need to set the affinity too.  You can work out which cores are on which banks from CoreInfo.

Then use a command like:

[code]
start /AFFINITY [h] /NUMA [n] "Numa [n]" cmd \k benchmark.exe --mine --jit --largePages --init 8 --threads 8 --nonces 10000
[/code]

Again for each node you want to have where [h] is the hex mask and [n] is the numa node.

Affinity is a hex mask not a direct cpu number. So to go the full range of possible combinations on my 2c/4t thread processor 0-F are acceptable values. 0001 - 1111. 

Now you can put it all in a batch file with one line per node.

Note: You might need to fiddle with your largePages set up too, not 100% sure on that yet.

**Comment by Jabroni** [comment]
Heres my results of the benchmark for a 7351p

OS: Proxmox 5.3
Memory: 8x 16GB 2400Mhz (so all slots are used)

Ran directly on hypverisor OS

[code]
root@pm:~# sudo sysctl -w vm.nr_hugepages=4800
vm.nr_hugepages = 4800
root@pm:~# seq 0 3 | xargs -P 0 -I node numactl -N node ./randomx-benchmark --mine --largePages --jit --nonces 100000 --init 8 --threads 8
[/code]



My results were
[code]
Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f
Performance: 2645.11 hashes per second
Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f
Performance: 2646.72 hashes per second
Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f
Performance: 2637.67 hashes per second
Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f
Performance: 2173.49 hashes per second
[/code]

So thats ~10,100 H/s if I sum the result of each NUMA job

**Comment by russoj88** [comment]
> Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f
> Performance: 2645.11 hashes per second
> Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f
> Performance: 2646.72 hashes per second
> Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f
> Performance: 2637.67 hashes per second
> Calculated result: d6660144e9a2e68bf47d7cc8afc206672e72f82dfff69fe0d974531e85f7504f
> Performance: 2173.49 hashes per second

Any idea why the fourth node had worse performance?

**Comment by Jabroni** [comment]
> 
> Any idea why the fourth node had worse performance?

Could be because I did had some vms and dockers running while doing these benchmarks, its my home server so those vms and dockers load is low, but that could count on the difference

**Comment by russoj88** [comment]
Thanks for the reply.  I assume getting performance for a node and then multiplying by the node count is accurate (enough), but want to make sure.
