### ISSUE TITLE
Testing changes against multiple environments

### ISSUE THREAD

**Issue by mistfpga** [tevador/RandomX#94]
Hi,

I know there are similar issues to this, like:
https://github.com/tevador/RandomX/issues/3
https://github.com/tevador/RandomX/issues/25

This is slightly different to those.

I have a suite of perl scripts that run a lot of benchmarking/[performance tests and collate the results. I am very familiar with cpu design, L-cache layouts and ram/processor bottle necks (probably not as familiar as yourselves though).

These could help in assessing the impact of changes like 
https://github.com/tevador/RandomX/pull/77

Across various CPU/Ram designs. (dimms v simms, rank ordering, etc)

I have 3 dedicated (soon to be a fourth) test environments for RandomX - these are purpose built as to avoid spurious issues. 
basic overview to keep this short:
- i7 Mobile DDR3 dual channel
- Ryzen 2600 DDR4 dual channel
- Dual socket Opteron server DDR3 quad channel (NUMA, etc)
- Dual socket Xeon DDR4 quad channel (NUMA, etc)

All do/will run windows and linux.

Would it be helpful for me performance test the benchmarking tool against each platform each release of it in various hardware configs of the above machines and various parameters and update with what differences I notice from release to release.  (I will be doing this anyway, it is just do you want the information? and if you do, how would you like it presented)

So I would go back and put my timings, etc in issue 3 and similar tickets, then, if their is significant change, I just update a single ticket test result changes. I can also do specific tests if you have any against the above hardware.

I will be getting ARM hardware and adding that in, as well an AMD FX processor (it has no L3 cache.) And I have quite a bit of hardware in between (i3's i5's of various ages)

This testing is not designed to generate more work, nor to be destructive testing. but to assess the impact across various platforms of changes. so more conformance testing than anything. 

I am also happy to smoke test stuff too.

Hope I can be of help.

**Comment by tevador** [comment]
> Would it be helpful for me performance test the benchmarking tool against each platform

Of course, go ahead. You can also include the CN/R hashrate for comparison (use [xmrig](https://github.com/xmrig/xmrig)).
