### ISSUE TITLE
LIBSTC++ error on RHEL 7.x

### ISSUE THREAD

**Issue by jims23211** [tevador/RandomX#97]
Unable to run randomx-benchmark (v1.04 or 1.03) due to missing libraries that are not a part of RHEL 7.x  error below.

[jamesstern@unknown000C291789AD Downloads]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)

[jamesstern@unknown000C291789AD Downloads]$ ./randomx-benchmark --mine --jit --largePages --threads 8 --init 8
./randomx-benchmark: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./randomx-benchmark)
./randomx-benchmark: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./randomx-benchmark)
[jamesstern@unknown000C291789AD Downloads]$ 

Recommend you compile using earlier version GLIBCXX_3.4.19

[jamesstern@unknown000C291789AD lib64]$ strings libstdc++.so.6|grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.14
GLIBC_2.4
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by tevador** [comment]
The precompiled Linux binaries were build with GCC 8.1. The required symbols are part of GCC 5.1 and newer (according to [this list](http://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html)), which is a reasonably old version. Hoever, it seems that RHEL 7 only ships with GCC 4.8: https://access.redhat.com/solutions/19458

The solution is to build the binaries yourself.
